### ISSUE TITLE
网站使用被动事件侦听器以提升滚动性能

### ISSUE THREAD

**Issue by cleverboy32** [fengyuanchen/viewerjs#102]
![image](https://user-images.githubusercontent.com/17595456/30526846-3d0722e2-9c54-11e7-907e-68342b5fac8b.png)

**Comment by gdh1995** [comment]
不该启用被动事件监听，因为被动模式下无法“阻止”鼠标滚轮/触摸板滚动事件，滚动事件会从viewerjs的对话框冒泡到document进而造成页面滚动。

避免这个warning的做法是，主动声明`passive: false`，比如我这个修改： https://github.com/fengyuanchen/viewerjs/compare/master...gdh1995:for-vimium-c#diff-8901833d3b25d2f3ac53c873df0fdaf5R56

@fengyuanchen 我想知道能不能像我的修改那样，判断浏览器是否支持wheel事件，支持的话就不监听mousewheel、DOMMouseScroll了，我觉得这么做可以让getEventListener的结果更干净些。

而且MDN上说了，监听wheel后，就不会产生并派发mousewheel事件了。
