### ISSUE TITLE
基于插件的思考，外面浮层也能拖动

### ISSUE THREAD

**Issue by chenddong** [fengyuanchen/viewerjs#105]
期望实现外侧浮层的拖动效果，能否实现类似qq图片的展示效果，希望能联系到作者，探讨进步。

**Comment by chenddong** [comment]
![20170826114](https://user-images.githubusercontent.com/24601268/30841410-de1e67fc-a2ae-11e7-948c-546d6310306c.png)

**Comment by fengyuanchen** [comment]
I think this case is over-designed. But you can fork one and implement it by yourself.
