### ISSUE TITLE
Should symmetric operations be considered?

### ISSUE THREAD

**Issue by fanxinqi** [fengyuanchen/viewerjs#106]
#104 
从有paly按钮状态【点击play按钮】到全屏播放状态，是一个操作（即paly按钮状态==>全屏播放状态）而键盘【esc按钮】也是一个操作，也是应该从全屏状态到未点击paly按钮状态（即全屏播放状态==>paly按钮状态），而不是两次esc， 是否考虑对称操作。

**Comment by fengyuanchen** [comment]
v0.8.0已修复改问题。
