### ISSUE TITLE
viewerjs_1.default is not a constructor when importing through npm package

### ISSUE THREAD

**Issue by nicooler** [fengyuanchen/viewerjs#110]
Hi there,

In short:
I am trying to use your package through a second npm package in an Angular 4 application and I am getting this error:

> Uncaught TypeError: viewerjs_1.default is not a constructor

In more detail:
Inside my npm package I created an Angular component that imports your package like this
`
import * as Viewer from "viewerjs";
import {
    ChangeDetectorRef,
    Component,
    ElementRef,
    Input,
    ViewChild
} from "@angular/core";

@Component({
    selector: "image-viewer",
    templateUrl: "./image-viewer.component.html"
})
export class ImageViewerComponent {

    @ViewChild("image") imageElement: ElementRef;
    @Input() imageUrl: string;
    @Input() thumbUrl: string;

    loadImage: boolean = false;
    viewer: Viewer = null;

    constructor(private cd: ChangeDetectorRef) {
    }

    ...

    openViewer(): void {
        this.loadImage = true;
        this.cd.detectChanges();
        if (this.viewer === null) {
            this.viewer = new Viewer(
                this.imageElement.nativeElement,
                {
                    navbar: false
                });
            this.viewer.show();
        }
    }

}

`
When the openViewer() function is called from the application that has imported my npm package this error is shown:

`Subscriber.js:242 Uncaught TypeError: viewerjs_1.default is not a constructor
    at ImageViewerComponent.webpackJsonp.416.ImageViewerComponent.openViewer (image-viewer.component.js:16)
    at fullscreen-image.component.ts:27
    at SafeSubscriber._next (event.service.ts:19)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:238)
    at SafeSubscriber.next (Subscriber.js:185)
    at Subscriber._next (Subscriber.js:125)
    at Subscriber.next (Subscriber.js:89)
    at Subject.next (Subject.js:55)
    at EventService.webpackJsonp.478.EventService.notify (event.service.ts:30)
    at ImageComponent.webpackJsonp.1170.ImageComponent.openFullscreen`

When I put the component directly into the parent application it works just fine, so my guess is the wrapping destroyes sth.

Do you have any idea?

Thanks for your help.

Cheers
Nico

**Comment by fengyuanchen** [comment]
Why not use `import Viewer from "viewerjs"`?

**Comment by nicooler** [comment]
I tryed that too, it does not change anything. I saw that lodash is using that import like 
> import * as Viewer form "viewerjs";

But that did not help.

**Comment by fengyuanchen** [comment]
I think it is not a problem of Viewer.js. Please check your build system to fix it.

**Comment by KennethMa** [comment]
@nicooler 
``` typescript
import Viewer from 'viewerjs/dist/viewer.esm'
import 'viewerjs/dist/viewer.min.css'
```

**Comment by fengyuanchen** [comment]
```txt
dist/
├── viewer.css
├── viewer.min.css   (compressed)
├── viewer.js        (UMD)
├── viewer.min.js    (UMD, compressed)
├── viewer.common.js (CommonJS, default)
└── viewer.esm.js    (ES Module)
```
