### ISSUE TITLE
Method to fill the container

### ISSUE THREAD

**Issue by matteoferigo** [fengyuanchen/viewerjs#111]
Hi, I'm looking for a method which sets the original zoom (when the viewer loads the image for the first time).
Is it available? How can I do that?

Thanks

**Comment by fengyuanchen** [comment]
Try the `reset` method.

**Comment by matteoferigo** [comment]
Reset method will reset everything (for example rotation), and I just want to reset zoom
Is it possible to get the initial zoom value on ready event? It's helpful as well

Thanks

**Comment by fengyuanchen** [comment]
Try the `toggle` method.

**Comment by matteoferigo** [comment]
Toggle is switching from full-size of the image to the full-size of the container. I just want to switch to the full-size of the container

**Comment by matteoferigo** [comment]
Ok, I catched the original ratio during viewed event:

```
viewed ({target: {viewer}}) {
     originalRatio = viewer.initialImageData.ratio
}
```

and then I used `viewer.zoomTo(originalRatio)` to set the container full-size
