### ISSUE TITLE
viewerjs 与 懒加载可以实现吗

### ISSUE THREAD

**Issue by Drazen08** [fengyuanchen/viewerjs#117]
如果使用动态加载图片的话，使用update方法，在100-110张图片的时候就会出现图片挂掉的情况，可以通过什么思路来修改吗，比如懒加载之类的

**Comment by iygnol** [comment]
这个有一个处理方法：使用一个占位图替代，然后js控制把要显示的img的src替换过来，再update一下就可以了，我之前也遇到图片太多挂掉的情况。
我的具体做法：
1、所有的图片初始化都是占位图；
2、把展示的大图前后5张小图（共最多11张）加载出来；
3、每次选中一张新图片，执行2

**Comment by iygnol** [comment]
对了，我用的是jquery版本的

**Comment by fengyuanchen** [comment]
默认展示缩略图，再通过`url`参数设置原图查看地址。

**Comment by me1a** [comment]
@fengyuanchen 这样的话， 请求是发出去了，没有懒加载的效果了

**Comment by fengyuanchen** [comment]
目前不支持。
