### ISSUE TITLE
最新版， 在移动端单指左右或上下滑动都是伸缩图片?

### ISSUE THREAD

**Issue by hyguang** [fengyuanchen/viewerjs#121]
使用最新版， 在移动端单指左右或上下滑动都是伸缩图片?
初始化情况：toolbar只显示了放大缩小、选择和翻转6个按钮
出现的问题：刚进入页面时（刷新页面），第一次左或右滑动，可以正常切换图片；第二次开始的左右或上下啊滑动都是只能放大缩小图片。向右、向上滑动放大；向左，向下滑动缩小；向下滑动缩小的同时图片逐步往上移。
求大神指教。

**Comment by fengyuanchen** [comment]
请确认能否在[这里](https://fengyuanchen.github.io/viewerjs)复现，如果不行，可能要检查你自己的代码了。。

**Comment by hyguang** [comment]
HTML:
    <div class="img-list photoContent clearfix">
        <ul id="img-box1" class="images">
            <foreach name="res['pic'][1]" item="pic">
                <li class="photoBox" id="<{$pic.imgurl}>">
                    <div class="cover"></div>
                    <div class="img-warp-div">
                        <?php $file_type = get_file_type($pic['imgurl']) ; ?>
                        <if condition="$file_type eq 'image' ">
                            <img src="<?php echo get_img_host(); ?><{$pic.imgurl}>" alt="<{$pic.imgurl}>">
                        <else/>
                            <img class="not-picture" src="__PUBLIC__/img/<{$file_type}>.jpg" alt="<{$pic.imgurl}>">
                        </if>
                    </div>
                    <i class="icon-tick"></i>
                </li>
            </foreach>
        </ul>
    </div>

js:
const options = {
        toolbar: {
            zoomIn: {
                show:true,
                size: 'large'
            },
            zoomOut: {
                show:true,
                size: 'large'
            },
            oneToOne: false,
            reset: false,
            prev: false,
            play: false,
            next: false,
            rotateLeft: {
                show:true,
                size: 'large'
            },
            rotateRight: {
                show:true,
                size: 'large'
            },
            flipHorizontal: {
                show:true,
                size: 'large'
            },
            flipVertical: {
                show:true,
                size: 'large'
            },
        },
        movable: true
    };
viewer1 = new Viewer(document.getElementById('img-box1'), options);
viewer2 = new Viewer(document.getElementById('img-box2'), options);
viewer3 = new Viewer(document.getElementById('img-box3'), options);

**Comment by hyguang** [comment]
抱歉, 刚才HTML含有PHP, 显示有问题, 重新发一下;
HTML:
    <ul id="img-box1" class="images img-box1">
                
                <li class="photoBox" id="图片id">
                    <div class="cover"></div>
                    <div class="img-warp-div">
                            <img src="..." alt="...">
                    </div>
                    <i class="icon-tick"></i>
                </li>
                
        </ul>

js:
const options = {
        toolbar: {
            zoomIn: {
                show:true,
                size: 'large'
            },
            zoomOut: {
                show:true,
                size: 'large'
            },
            oneToOne: false,
            reset: false,
            prev: false,
            play: false,
            next: false,
            rotateLeft: {
                show:true,
                size: 'large'
            },
            rotateRight: {
                show:true,
                size: 'large'
            },
            flipHorizontal: {
                show:true,
                size: 'large'
            },
            flipVertical: {
                show:true,
                size: 'large'
            },
        },
        movable: true
    };
    viewer1 = new Viewer(document.getElementById('img-box1'), options);
    viewer2 = new Viewer(document.getElementById('img-box2'), options);
    viewer3 = new Viewer(document.getElementById('img-box3'), options);

**Comment by hyguang** [comment]
`<ul id="img-box1" class="images">
            <foreach name="res['pic'][1]" item="pic">
                <li class="photoBox" id="<{$pic.imgurl}>">
                    <div class="cover"></div>
                    <div class="img-warp-div">
                        <?php $file_type = get_file_type($pic['imgurl']) ; ?>
                        <if condition="$file_type eq 'image' ">
                            <img src="<?php echo get_img_host(); ?><{$pic.imgurl}>" alt="<{$pic.imgurl}>">
                        <else/>
                            <img class="not-picture" src="__PUBLIC__/img/<{$file_type}>.jpg" alt="<{$pic.imgurl}>">
                        </if>
                    </div>
                    <i class="icon-tick"></i>
                </li>
            </foreach>
        </ul>`

**Comment by hyguang** [comment]
https://fengyuanchen.github.io/viewerjs/ 直接用手机的浏览器打开您所给的地址(左侧)测试, 可以复现, 得到跟我所描述的一样, 不好意思, 只有QQ浏览器会出现这个情况

**Comment by fengyuanchen** [comment]
那个浏览器我就没有办法了。。
