### ISSUE TITLE
IE8下_createClass中Object.defineProperty异常问题

### ISSUE THREAD

**Issue by zajianTA** [fengyuanchen/viewerjs#124]
IE8下Object.defineProperty只能对文档对象有效，所以在IE8下viewer.js中1819行会异常，参考链接如下
[Object.defineProperty](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty)
我魔改了一下：
`if ("value" in descriptor){
          target[descriptor.key] = descriptor.value;
          target[descriptor.key].writable = true;
          target[descriptor.key].enumerable = descriptor.enumerable || false;
          target[descriptor.key].configurable = true;
        }`

**Comment by fengyuanchen** [comment]
https://github.com/fengyuanchen/viewerjs#browser-support
