### ISSUE TITLE
toolbar icon 可以修改吗

### ISSUE THREAD

**Issue by junhui75165** [fengyuanchen/viewerjs#125]
如何修改toolbar下的icon图标，自己定制点击效果

**Comment by fengyuanchen** [comment]
https://github.com/fengyuanchen/viewerjs/blob/master/examples/custom-toolbar.html

**Comment by Choigakay** [comment]
The page is not found~

**Comment by fengyuanchen** [comment]
@Choigakay https://fengyuanchen.github.io/viewerjs/examples/custom-toolbar.html
