### ISSUE TITLE
Background click to perform viewer.hide()

### ISSUE THREAD

**Issue by mikegk** [fengyuanchen/viewerjs#126]
I just tried to add an event listener to make the background clickable and to leave the current viewer output.
`var body = document.getElementsByClassName('body')[0];
        body.addEventListener('click',function(){
            viewer.hide();
        },true);`
I also tried to fire the event without propagination which made the footer toolbar also launch the .hide() method.
Is there any way to escape the current view by clicking outside the picture but not onto the thumbs or the toolbar buttons?

**Comment by fengyuanchen** [comment]
The [latest version](https://github.com/fengyuanchen/viewerjs/releases/tag/v1.0.0-beta.1) had supported this.
