### ISSUE TITLE
Additional options 

### ISSUE THREAD

**Issue by AlgyTaylor** [fengyuanchen/viewerjs#13]
Hi,

Viewer.js is awesome :+1: 

But ... would it be possible to have some options for which transitions it allows? For example, when I'm changing through images, I don't like zooming out then back in again, I just want it to go from one, to the next, to the next, ... but the rest of the time, I think the transitions add some niceness to it (particularly in zooming), so would it be possible to state which ones I can do that?

Also, I don't know if this is already posssible (I thought 'scalable' would do it, but no ...), but I'd like to disable the ability to flip the image?  I have some images with text on, so they become useless if flipped (in fact worse, because some of the data - they are graphs - will be wrong and might be misinterpretted), so I'd rather not offer the option to do it!

Great work by the way!

**Comment by fengyuanchen** [comment]
1) In order to keep the library small and simple, I cannot provide all the available options, so I'd like to provide the basic options only.
2) Set the `scalable` option to `false` will disable image flipping.

**Comment by AlgyTaylor** [comment]
Thanks :+1:
