### ISSUE TITLE
Sliding not works on devices with iOS

### ISSUE THREAD

**Issue by Stafox** [fengyuanchen/viewerjs#133]
I found a bug, which I reproduced on several mobile Apple's devices (iPhone 6, iPhone 7 Plus, both iOS 11.2) in Safari.

**How to reproduce:**
It easy to reproduce using this demo: https://fengyuanchen.github.io/viewerjs/

Just open an image and then swipe to the left or to the right. First swipe is ok, but at the second it starts to zoom image instead of switching to the next image.

If I disable zoom, nothing happens, sliding just not works.

It was reproduced using the latest release: https://github.com/fengyuanchen/viewerjs/releases/tag/v1.0.0-beta.1

Here a video how it looks: https://youtu.be/SVo3y-tJCVk
Let's me know if you need more details.

**Comment by Stafox** [comment]
@fengyuanchen Could you confirm that issue exists?

**Comment by Stafox** [comment]
@fengyuanchen Looks like it didn't help

**Comment by Stafox** [comment]
The problem somewhere here:
```
if (e.changedTouches) {
      each(e.changedTouches, (touch) => {
        pointers[touch.identifier] = getPointer(touch);
      });
    } else {
      pointers[e.pointerId || 0] = getPointer(e);
    }

    let action = options.movable ? ACTION_MOVE : false;

    if (Object.keys(pointers).length > 1) {
      action = ACTION_ZOOM;
    } else if ((e.pointerType === 'touch' || e.type === 'touchstart') && this.isSwitchable()) {
      action = ACTION_SWITCH;
    }
```

For some reason pointer was added to `pointers` twice. And condition `Object.keys(pointers).length > 1` always return `true`. So action defines as ZOOM.

**Comment by Stafox** [comment]
I tried to add condition
```
if (Object.keys(pointers).length > 1 && options.zoomable) {
```

But it doesn't help. Starting from second slide functionality stopped to work. It's a little bit hard to debug, because I'm not able to reporduce it using Chrome on PC.

**Comment by Tammeny** [comment]
@Stafox Have you solved the problem?

**Comment by Stafox** [comment]
@Tammeny not yet. I'll spent one or two hours more, if there is no sucess I'll search for another viewer lib.

**Comment by Tammeny** [comment]
@fengyuanchen 你好，这个问题我也有遇到，如何处理？

**Comment by Stafox** [comment]
@fengyuanchen I think better to reopen this issue.

**Comment by Tammeny** [comment]
@Stafox Agree.

**Comment by heke2929** [comment]
@Stafox Agree 2.

**Comment by bdevika** [comment]
@Stafox Agree

**Comment by XiaoChengji** [comment]
> @Stafox Agree, it is not working in newer version of os ipad device ->13.1

Me too. Do you resolve this problem?

**Comment by bdevika** [comment]
@XiaoChengji , No

**Comment by XiaoChengji** [comment]
@bdevika I resolved this problem，Because it uses the PointerEvent if the broswer support the PointerEvent, you change to a touchEvent event that will resolve this problem.

origin
`
var HAS_POINTER_EVENT = IS_BROWSER ? 'PointerEvent' in WINDOW : false;
`

edit
`
var HAS_POINTER_EVENT = false;
`

![image](https://user-images.githubusercontent.com/14002295/65859831-a3db3900-e39b-11e9-91a1-0d9ba0d0942f.png)

**Comment by fengyuanchen** [comment]
I just have a test on an iPhone 8 device with iOS 12.4.1 system, and it works fine on Safari browser with the latest version (1.3.6 currently) of Viewer.js.

PS: `PointerEvent` is the standard event for all modern devices.

**Comment by fengyuanchen** [comment]
For iOS 13+, see #321.
