### ISSUE TITLE
Support Exif orientation

### ISSUE THREAD

**Issue by Bishop** [fengyuanchen/viewerjs#134]
For my purposes I replaced https://github.com/fengyuanchen/viewerjs/blob/517055fe6467f1fc6bd14976fa1ba046bd2cc2a4/dist/viewer.js#L1009-L1011 by
```javascript
      // HACK: read exif and rotate image
      new Exif(image, {
        interoperability: false,
        gps: false,
        done: function(tags) {
          imageData.exif = tags;

          var rotates = { 6: 90, 3: 180, 8: -90 };

          if (tags.Orientation && rotates[tags.Orientation]) {
            _this2.imageData.rotate = rotates[tags.Orientation];
            _this2.initialImageData.rotate = rotates[tags.Orientation];
          }

          if (isFunction(callback)) {
            callback();
          }
        },
        fail: function() {
          if (isFunction(callback)) {
            callback();
          }
        }
      });
```

To implement clean and configurable solution it need to many changes, and in exif lib api too. Maybe you can do it.

**Comment by sunnychan16** [comment]
Is there any plan on supporting this soon?

**Comment by jjhi11** [comment]
Wondering this as well!

**Comment by dogrocker** [comment]
This form uppy, How they rotated thumbnail.
https://github.com/transloadit/uppy/pull/1532

**Comment by wkdhkr** [comment]
```css
img {
    image-orientation: from-image;
}
```

works for me.

**Comment by dogrocker** [comment]
> ```css
> image-orientation
> ```

I see this not suppprt in chrome.
https://developer.mozilla.org/en-US/docs/Web/CSS/image-orientation

**Comment by wkdhkr** [comment]
https://caniuse.com/#feat=css-image-orientation

Available from version 81.
