### ISSUE TITLE
Viewer is not defined

### ISSUE THREAD

**Issue by AdrianKuriata** [fengyuanchen/viewerjs#136]
Hi, i have a problem, i installed viewer with npm, everything is loaded, but when i try use it i getting error: `Viewer is not defined`
This is my code:
`var viewer = new Viewer(document.getElementById('card-img-top'));`

I installed newest beta version, could you help me with that? This is really important.

**Comment by fengyuanchen** [comment]
```js
import Viewer from 'viewerjs/dist/viewer.esm';
```

Or

```js
const Viewer = require('viewerjs');
```

**Comment by bradburydoom** [comment]
I am also getting this error but I did not install using npm.  I just downloaded the files and included them in my html. Do I have to install via npm? I'm not currently using it and would like to avoid it.
