### ISSUE TITLE
[Bug] Inline mode: When container of the viewer changes size, the viewer doesn't change with it

### ISSUE THREAD

**Issue by brunoais** [fengyuanchen/viewerjs#138]
When the original images are not displayed and then the container is resized by CSS changes or by using javascript, it does not adjust to the new container sizes.

However, if the height + width calculation is overridden to be automatic, it works just fine in the situations of the test.

Examples + Test cases:
[Vertically](https://codepen.io/anon/pen/OQOPKQ)
[Horizontally]( https://codepen.io/anon/pen/WMXveg)

You can test with the absolutely placed button I placed to toggle between automatic and given measurements and you can click anywhere in the body for the sizes to change.

**Comment by fengyuanchen** [comment]
After you change the container size manually, you can trigger a resize event on window to update the viewer, or just call the internal `resize` method.

**Comment by brunoais** [comment]
@fengyuanchen Please do mention that in the documentation.
Also, why does the size of the container have to be set explicitely?

**Comment by fengyuanchen** [comment]
I saw you were using CSS Grid Layout in your demo, but IE9 does not support them.

**Comment by brunoais** [comment]
Is it working like that inherently caused by the grid display?
