### ISSUE TITLE
[Feature request] Allow disabling the explicit size for the viewer in the .view-container element

### ISSUE THREAD

**Issue by brunoais** [fengyuanchen/viewerjs#139]
Related to #138, I request for an option which allows the viewer to not set the `width` and `height` explicitly and, instead, allow them to be set in either the user style sheet or even by the browser itself.

**Comment by fengyuanchen** [comment]
It is hard to do this in inline mode as the viewer is placed over the target element.

**Comment by fengyuanchen** [comment]
The size the of the inline viewer is inherit from its parent element (container), so just change the size of parent element.

**Comment by brunoais** [comment]
I've noticed that that is not what happens.
If I resize the container of viewerjs (inline), it doesn't react to the resize unless I dispatch a resize (DOM) event or `.update()` and the width+height stay set with the previous values.

I'm not using `v.1.0.0` so I'll test again with that version and then I'll call back

**Comment by fengyuanchen** [comment]
You can call the internal `resize` method instead of trigger a resize event on window.

**Comment by keshrath** [comment]
```
.viewer-container {
  width: 100% ! important;
  height: 100% ! important;
}
```
