### ISSUE TITLE
[Feature Request] Display a loading animation when original images is loading

### ISSUE THREAD

**Issue by vimcaw** [fengyuanchen/viewerjs#140]
Generally, it takes some time to load the image, especially for larger images, but at that time there was only a grey background, that is a bit weird. I think it is best to add a loading animation.
Such as: [loaders\.css](https://github.com/ConnorAtherton/loaders.css), [css\-loaders](https://github.com/lukehaas/css-loaders)
![image](https://user-images.githubusercontent.com/21964227/36795717-b6f6c08e-1cde-11e8-8251-0a9fde6506ed.png)

**Comment by fengyuanchen** [comment]
This has been implemented in `1.0.0-rc`.
