### ISSUE TITLE
TypeError: Cannot read property 'naturalWidth' and 'naturalHeight' of null

### ISSUE THREAD

**Issue by dcaruana90** [fengyuanchen/viewerjs#141]
On LOC 1640, there is no check to see if the image has a .naturalWidth and .naturalHeight. There seems to be no issues from this exception being thrown due to not displaying the subtext under the image. But it is thrown in my application due to the image not having those fields set. A simple null check around this should prevent this exception being thrown

**Comment by fengyuanchen** [comment]
Try the latest version please.
