### ISSUE TITLE
配置项和方法有中文文档么  可以建立一个交流群么

### ISSUE THREAD

**Issue by leefreeF** [fengyuanchen/viewerjs#142]

**Comment by leefreeF** [comment]
现在在vue中引用  看不懂githab里面的英文  使用起来  会报错  又不知道怎么解决

**Comment by leefreeF** [comment]
html：
<el-table-column align="center" prop="created_at" label="查看凭证" width="100">
    <template slot-scope="scope">
      <viewer :images="images">
        <img v-for="src in images" :src="src" :key="src">
      </viewer>
    </template>
</el-table-column>

script：
import Viewer  from 'v-viewer'
import Vue from 'vue'
Vue.use(Viewer ,{ name: 'vuer' })



已经在main.js里面引入了

**Comment by fengyuanchen** [comment]
```js
import Viewer from 'viewerjs';
import 'viewerjs/dist/viewer.css';
```
