### ISSUE TITLE
Feature request: Add 'zoom' or 'zoomed' event

### ISSUE THREAD

**Issue by romines** [fengyuanchen/viewerjs#144]
It would be useful to have an event fire when a 'zoom' occurs.

I would like to use viewer.js in a larger component that displays map images and allows users to drop a pin on a location. The pin can be absolutely positioned over the Viewer instance, but if the image is dragged or zoomed the pin would need to be placed again. This could be done if an event was emitted for 'zoom' and 'drag' (although 'drag' is less important to me).

I am happy to try this and give you a PR if you are open to the idea.

Perhaps the same timing could be used as when the `.viewer-tooltip` is updated.

Thank you for a very useful image viewer!

**Comment by Rlcolli4** [comment]
+1 we are trying something similar using the viewers (we have a viewer that displays a transparent image of what a user draws over another viewer) and we need the viewer with the users drawing to scale and move appropriately when the child viewer is zoomed in or out, moved, etc. This could be done in this event as well

**Comment by fengyuanchen** [comment]
You can listen on the native `transitionend` event as `zoomed`.

**Comment by Rlcolli4** [comment]
I tried `transitionend` the same way I set up viewed and that did not fire for us on pan or zoom.
