### ISSUE TITLE
Show modal only in container

### ISSUE THREAD

**Issue by lensz** [fengyuanchen/viewerjs#145]
Hello everybody,

I don't seem to understand the `container`-option viewerjs provides.

I thought this would mean, that the viewerjs-modal wouldn't open above the whole viewport of the page but rather only in that specified container.

For illustration purposes two screenshots of my current situation:
This is the situation on the page. I have a 100px container div that should house the viewer-modal in the end. and another div that houses the images at the moment.
![scrot_2018-03-08_14-22-39_screenshot](https://user-images.githubusercontent.com/263263/37153302-80b81244-22dc-11e8-8cf3-89289d481816.png)

This is the situation after clicking on the image. We now see, that the viewer modal is above the whole page instead of only covering the container.
![scrot_2018-03-08_14-22-57_screenshot](https://user-images.githubusercontent.com/263263/37153303-80ecc1b0-22dc-11e8-9602-658e8900981d.png)

This is a created image with what I really tried to accomplish:
![scrot_2018-03-08_14-36-54_screenshot](https://user-images.githubusercontent.com/263263/37153815-34582f40-22de-11e8-81b0-a34c3f52bb47.png)

Is this desired behaviour?

Sorry, but the docs don't make that clear to me.

regards and thanks for the help!

whole source:
(I am using vue, webpack and [v-viewer](https://github.com/mirari/v-viewer), but I think my issue is regarding viewerjs)
```
<template>
    <div>
        <div class="vcontainer">
        </div>
        <div class="images" v-viewer="{ container: '.vcontainer', fullscreen: false, navbar: false, toolbar: { zoomIn: true, zoomOut: true, oneToOne: true, reset: true, rotateLeft: true, rotateRight: true } }">
            <img src="https://fengyuanchen.github.io/viewerjs/images/tibet-2.jpg" />
        </div >
    </div>
</template>

<script>
</script>

<style scoped lang="less">
@import '~viewerjs/dist/viewer.css';

.vcontainer {
    height: 100px;
    margin-bottom: 10px;
}

img {
    width: 100%;
}
</style>

```

**Comment by fengyuanchen** [comment]
The container here is just used to put the elements of the viewer, and the viewer is still shown in full page after open.
