### ISSUE TITLE
support auto import css 

### ISSUE THREAD

**Issue by onpaik** [fengyuanchen/viewerjs#147]
use @import '~viewerjs/src/index.css',  style can not show normal;

**Comment by fengyuanchen** [comment]
Just import the compiled CSS file:

```css
@import 'viewerjs/dist/viewer.css';
```

**Comment by onpaik** [comment]
@fengyuanchen   ok, this way can work, add perfix wave line(~)
```javascript
  @import '~viewerjs/dist/viewer.css'
```
