### ISSUE TITLE
Viewer.show(immediate) is not optional

### ISSUE THREAD

**Issue by KSSLR** [fengyuanchen/viewerjs#148]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[X] Documentation issue or request
</code></pre>

## Current behavior
Viewer.show() gives compile error with 1.0.0rc

## Expected behavior
Viewer.show() should default to show(false) as documented

## Environment

<pre><code>
Viewer.js version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

**Comment by fengyuanchen** [comment]
Are you sure? How to reproduce?

**Comment by KSSLR** [comment]
You can see it in the type definitions:
declare class Viewer {
  constructor(element: Element, options?: Viewer.Options);
  destroy(): Viewer;
  exit(): Viewer;
  full(): Viewer;
  hide(immediate: boolean): Viewer;
  move(offsetX: number, offsetY?: number): Viewer;
  moveTo(x: number, y?: number): Viewer;
  next(loop?: boolean): Viewer;
  play(fullscreen?: boolean): Viewer;
  prev(loop?: boolean): Viewer;
  reset(): Viewer;
  rotate(degree: number): Viewer;
  rotateTo(degree: number): Viewer;
  scale(scaleX: number, scaleY?: number): Viewer;
  scaleX(scaleX: number): Viewer;
  scaleY(scaleY: number): Viewer;
  **show(immediate: boolean): Viewer;**
  stop(): Viewer;
  toggle(): Viewer;
  tooltip(): Viewer;
  update(): Viewer;
  view(index?: number): Viewer;
  zoom(ratio: number, hasTooltip?: boolean): Viewer;
  zoomTo(ratio: number, hasTooltip?: boolean): Viewer;
}

The documentation says it's optional, so it should be show(immediate?: boolean): Viewer

**Comment by fengyuanchen** [comment]
Got it. Thanks.
