### ISSUE TITLE
Toolbar customization 

### ISSUE THREAD

**Issue by macroramesh6** [fengyuanchen/viewerjs#15]
1st of all thanks for the awesome and lightweight lib.  I have implemented viewerjs and works fine. I would like to customize `toolbar`.  eg: I don't want `rotate` and `flip` option in a `toolbar`. Can viewerjs provide this option from next realise?

**Comment by fengyuanchen** [comment]
You can try to set both the `rotatable` and `scalable` options to `false`.

**Comment by macroramesh6** [comment]
@fengyuanchen Thanks a lot. so I will close this issue :)
