### ISSUE TITLE
Latest release constructor no longer supports options being passed in

### ISSUE THREAD

**Issue by dcaruana90** [fengyuanchen/viewerjs#150]
- Removed node_modules directory
- Ran NPM Install
- Once NPM install was complete, ran tests against codebase. 
- Discovered that the latest version no longer supported passing in options to constructor and could not resolve via the documentation how to fix this issue. Found that rolling back to 1.0.0-beta.1 resolved issue.

code sample:
this.viewer = new Viewer(imagesElement, {...options...});

**Comment by fengyuanchen** [comment]
Please check your own code first.
