### ISSUE TITLE
The first argument is required and must be an element.

### ISSUE THREAD

**Issue by Ucer** [fengyuanchen/viewerjs#151]
```
 <div>
        <img id="imagea" :src="user_avatar" alt="Picture">
 </div>

```

```              
   var viewer = new Viewer(document.getElementById('imagea'), {
        inline: true,
        viewed: function() {
            viewer.zoomTo(1);
        }
    });
```
在 vue 中可能是节点还未被渲染，所以 document.getElementById('imagea') 的值一直是空的

**Comment by fengyuanchen** [comment]
在Vue里面使用，需要在`mounted`钩子函数里面初始化Viewer.js

**Comment by pavankumardasireddy** [comment]
> 在Vue里面使用，需要在`mounted`钩子函数里面初始化Viewer.js

@fengyuanchen 
我是新手，我也有同样的问题，请你告诉我如何在`mounted`钩子函数中初始化Viewer.js。

**Comment by mwb7** [comment]
What about when i have multiple images in a table ? How i call them? What will be my container in that case? 
How i call this?
const gallery = new Viewer(document.getElementById('element'));
as in my case container is multiple TDs of table

**Comment by fengyuanchen** [comment]
@mwb7 Just initialize viewer in the table element.

```js
const gallery = new Viewer(document.getElementById('table'));
```
