### ISSUE TITLE
new Viewer只能一次否则报错

### ISSUE THREAD

**Issue by hduhdc** [fengyuanchen/viewerjs#156]
var viewer = new Viewer(document.getElementById('images'), {
          // inline: true,
          viewed: function() {
            // viewer.zoomTo(1);
          }
        });
        viewer.show();
Cannot read property 'length' of undefined

**Comment by fengyuanchen** [comment]
你确定？

**Comment by hduhdc** [comment]
我写了demo确实可以多次new，但是如果img的src是动态渲染的时候就会报错。
ncaught TypeError: Cannot read property 'length' of undefined
    at addClass (webpack-internal:///./node_modules/viewerjs/dist/viewer.esm.js:352)
    at Viewer.open (webpack-internal:///./node_modules/viewerjs/dist/viewer.esm.js:2473)
    at Viewer.show (webpack-internal:///./node_modules/viewerjs/dist/viewer.esm.js:1527)
    at Viewer.show (webpack-internal:///./node_modules/viewerjs/dist/viewer.esm.js:1506)
    at Viewer.view (webpack-internal:///./node_modules/viewerjs/dist/viewer.esm.js:1652)

我的代码是这样写的。
new Promise((resolve, reject) => {
        this.getArrayListActive(resolve);
      }).then(() => {
        this.$nextTick(() => {
          this.caculatePicture();
           // this.getViewEditRemark()
        })
      })
  getViewEditRemark() {

      let that = this;
      that.picturesManageModule.viewerObjCard = new Viewer(document.getElementById('imagesContainer'), {
        // inline: true,
        viewed: function() {
          // viewer.zoomTo(1);
        },
        url: "data-original",
        toolbar: {
          zoomIn: 4,
          zoomOut: 4,
          oneToOne: 4,
          reset: 4,
。。。。。。

**Comment by hduhdc** [comment]
@ @fengyuanchen 
new Viewer(this.$refs.imagesContainer, {
        
            viewed: function() {
           
            },
            url: "data-original",
            toolbar: {
              zoomIn: 4,。。。。。
this.$refs.imagesContainer我能拿到dom，我看到imagesContainer里面的图片dom结构没有层级关系吧。
 <ul id="imagesContainer" ref="imagesContainer" class="docs-pictures pic-list clearfix">
        <li v-for="(item,index) in picturesManageModule.arrayList" @click.stop="preview(item)">
          <div v-if="item.fileType==1">
            <div class="pic-box">
              <a class="img-choose" @click.stop="select($event,item)"></a>
              <img :src="item.smallPhotoUrl" :data-original="item.bigPhotoUrl" width="100%" height="100%">

**Comment by hduhdc** [comment]
@fengyuanchen  
<ul id="imagesContainer" ref="imagesContainer" class="docs-pictures pic-list clearfix">
        <li v-for="(item,index) in picturesManageModule.arrayList" @click.stop="preview(item)">
          <div v-if="item.fileType==1">
            <div class="pic-box">
              <a class="img-choose" @click.stop="select($event,item)"></a>
              <img :src="item.smallPhotoUrl" :data-original="item.bigPhotoUrl" width="100%" height="100%">
这是容器

**Comment by hduhdc** [comment]
` <ul id="imagesContainer" ref="imagesContainer" class="docs-pictures pic-list clearfix">
        <li v-for="(item,index) in picturesManageModule.arrayList" @click.stop="preview(item)">
          <div v-if="item.fileType==1">
            <div class="pic-box">
              <a class="img-choose" @click.stop="select($event,item)"></a>
              <img :src="item.smallPhotoUrl" :data-original="item.bigPhotoUrl" width="100%" height="100%">`

**Comment by hduhdc** [comment]
` <ul id="imagesContainer" ref="imagesContainer" class="docs-pictures pic-list clearfix">
        <li v-for="(item,index) in picturesManageModule.arrayList" @click.stop="preview(item)">
          <div v-if="item.fileType==1">
            <div class="pic-box">
              <a class="img-choose" @click.stop="select($event,item)"></a>
              <img :src="item.smallPhotoUrl" :data-original="item.bigPhotoUrl" width="100%" height="100%">`
这是容器
