### ISSUE TITLE
Feature Request: Dynamically start viewer on a provided index

### ISSUE THREAD

**Issue by dcaruana90** [fengyuanchen/viewerjs#158]
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ X ] Feature request
[ ] Documentation issue or request

## Current behavior

I am calling the destroy method on my viewer and creating a new one given a new set of options. The viewer upon creation resets to first image in the array. Confirmed this is the behavior on the demo website as well. I viewed an image further in the array and changed the options via the check boxes to the left of the viewer.

## Expected behavior

I would like a means of recreating the viewer and not have to make a second call to get back to the image in the array I was previously viewing. That way visually it does not look like the viewer "skipped" back to the first image.

## Environment
Viewer.js version: 1.0.0-rc.1

Browser:
- [ X ] Chrome (desktop)
- [ X ] Chrome (iOS)
- [ X ] Safari (desktop)
- [ X ] Safari (iOS)

**Comment by fengyuanchen** [comment]
Just use the `view` method to show the target image you want. For example, view the the third image:

```js
viewer.view(2);
```
