### ISSUE TITLE
Maintain Zoomed Area When Next Image

### ISSUE THREAD

**Issue by JCarlos12** [fengyuanchen/viewerjs#159]
I was wondering if there was a way to maintain the zoom and move to when viewing next image.

I have no idea how to get the images current x and y as well. And I also see that there are no events for next or zoom. Are these possible events to be added in the future?

Thanks in advance

**Comment by fengyuanchen** [comment]
You can cache zoom data within the `zoomed` event and restore it within the `viewed` event.
