### ISSUE TITLE
Ability to exclude certain images from a set.

### ISSUE THREAD

**Issue by thoughtAddict** [fengyuanchen/viewerjs#164]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report 
[X ] Feature request
[ ] Documentation issue or request
</code></pre>

I have a DIV with an "id" of "_grid_":

```
<div class="grid" id="grid">
    <div><img src="picture-1.jpg" alt="Picture 1" class="publicImage"></div>
    <div><img src="picture-2.jpg" alt="Picture 2" class="publicImage"></div>
    <div><img src="picture-3.jpg" alt="Picture 3" class="publicImage"></div>
    <div><img src="picture-4.jpg" alt="Picture 4" class="privateImage"></div>
 </div>
```

I was wondering if it would be possible to exclude certain IMG tags from within that "grid" DIV from the Viewer.

Perhaps something like this:

```
    var imageGalleryViewer = new Viewer(document.getElementById('grid'), {
        tooltip: false,
        navbar: false,
        interval: 10000,
        exclude: ".privateImage"
      });
```
I've been able to run ViewerJS alongside the "masonry.desandro.com" Masonry JS lib, and it's working great.   

Thanks for the help, (and the excellent Viewer library).

Jon

**Comment by fengyuanchen** [comment]
Just use the `filter` option: https://github.com/fengyuanchen/viewerjs#filter

**Comment by thoughtAddict** [comment]
Not sure how I missed that, but thanks (much) for pointing it out.

Jon

**Comment by VenkateshBaddepuri** [comment]
@fengyuanchen ,  I am using viewerJS and How can I add filter method to exclude certain class of images?
