### ISSUE TITLE
Error: The first argument is required and must be an element.

### ISSUE THREAD

**Issue by Vanadiy** [fengyuanchen/viewerjs#169]
## Error creating Viewer Element

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## Current behavior

Uncaught Error: The first argument is required and must be an element.
at new Viewer (viewer.esm.js:2645)

## Minimal reproduction of the problem with instructions

Use ReactJs

```
import Viewer from 'viewerjs/dist/viewer.esm'
import 'viewerjs/dist/viewer.min.css'

var viewer = new Viewer(<img id='defaultWOPIView' src = {this.hostweburl+this.state.previewFile.path}/>)
return viewer
```

or

```
let element = React.createElement('img', {id: 'defaultWOPIView', src: this.hostweburl+this.state.previewFile.path}, '')
var viewer = new Viewer(element)
return viewer
```

## Environment

<pre><code>
Viewer.js version: 1.0.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

</code></pre>

**Comment by fengyuanchen** [comment]
https://github.com/fengyuanchen/viewerjs#syntax
