### ISSUE TITLE
为什么点击两次后才起作用了

### ISSUE THREAD

**Issue by xiaojun515688** [fengyuanchen/viewerjs#172]
/**
         * 图片预览
         */
        $(document).on('click', '.img-style', function () {
            var current = this;
            var formId = $(current).attr("data-form-id");
            var galley = document.getElementById('form-' + formId);
            var viewer = new Viewer(galley, {
                url: 'data-original',
                toolbar: {
                    oneToOne: true,
                    rotateLeft: 4,
                    rotateRight: 4,
                    prev: function () {
                        viewer.prev(true);
                    },
                    play: true,
                    next: function () {
                        viewer.next(true);
                    }
                },
            });
        });

**Comment by fengyuanchen** [comment]
看你这代码，每次点击都创建一个Viewer实例，这样没有问题吗？

**Comment by xiaojun515688** [comment]
因为照片存在不同的div中啊，我这里相当于是有分组的tab选项卡

**Comment by xiaojun515688** [comment]
照片和装照片的div都是动态生成的

**Comment by xiaojun515688** [comment]
如果初始化创建一个viewer，我要换不同的galley 应该怎么弄

**Comment by xiyuan-fengyu** [comment]
在  var viewer = new Viewer(...);
之后调用 viewer.show(); 就可以在第一次点击后就可以显示
如果不需要在多次点击中共享 viewer，需要在隐藏 viewer时销毁掉

**Comment by LiuLiuniuniu** [comment]
```
        let _id = document.getElementById("xx");
            let viewer =  new Viewer(_id,{
              toolbar: false,
              navbar: false,
            });
            viewer.show(); 
```

**Comment by LiuLiuniuniu** [comment]
弄好了；
```
mounted() {
     this.initViewer();
},
```

```
    initViewer() {
            let _id = document.getElementById("article-content");
            this.viewer =  new Viewer(_id,{
              navbar: true,
              toolbar: true,
              show(){  // 动态加载图片后，更新实例
                this.viewer.update();
              },
            });
          },
```

## 点击图片

```
 imageChang(e){
            if (e.target.nodeName == 'IMG') {
              this.viewer.show();
            }
          },
