### ISSUE TITLE
移动端是否有双击打开大图，单击关闭的事件？

### ISSUE THREAD

**Issue by lintiansheng** [fengyuanchen/viewerjs#173]
就是一般移动端的事件，在图列表中。点击图片，放大。双击放大图片。再点击关闭

**Comment by fengyuanchen** [comment]
双击事件在大多数手机端浏览器上不被支持。The `dblclick` event is not supported in most mobile browsers.

> https://developer.mozilla.org/en-US/docs/Web/Events/dblclick
