### ISSUE TITLE
Add option to enable "pan limit boundary"

### ISSUE THREAD

**Issue by MiNiCo88** [fengyuanchen/viewerjs#174]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report 
[x] Feature request
[x] Documentation issue or request
</code></pre>

## Current behavior

Hello everyone, there is a way to enable the pan limit boundary avoiding the image output from the screen view?

## What is the motivation / use case for changing the behavior?

When i move an image, i don't want that image can go out of the screen view

## Environment

<pre><code>
Viewer.js version: X.Y.Z

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX

Others:

</code></pre>

**Comment by jewelcai** [comment]
Any update on this issue? Or is there some existing way to handle this ?

**Comment by xdanif** [comment]
Ok, I can control this, but what is the correct behavior?

1. Do not allow image to leave anything off the screen?
2. Do not allow the image to exit more than 50% of the screen?

**Comment by fengyuanchen** [comment]
Check out this example: [Moving range limit](https://fengyuanchen.github.io/viewerjs/examples/moving-range-limit.html).
