### ISSUE TITLE
iphone7使用这个插件预览图片，不能向左或向右滑动下一张图片

### ISSUE THREAD

**Issue by lintiansheng** [fengyuanchen/viewerjs#176]
不能向左或向右滑动下一张图片，左滑或右滑是放大图片的，今天才发现的，之前并没有这个问题

**Comment by fengyuanchen** [comment]
你用的哪个版本，哪个浏览器？

**Comment by lintiansheng** [comment]
使用的是这个版本：/*!
 * Viewer.js v0.10.0
 * https://github.com/fengyuanchen/viewerjs
 *
 * Copyright (c) 2015-2017 Chen Fengyuan
 * Released under the MIT license
 *
 * Date: 2017-11-05T04:38:31.466Z
 */
我是使用在移动端的。之前是没有这个问题的。可以左向左或向右滑动下一张图片，突然就不可以了，出现了这个问题:ios左滑或右滑是放大图片的，andoird是正常的。使用的微信开发页面的

**Comment by fengyuanchen** [comment]
请使用最新版。
