### ISSUE TITLE
zoom and zoomed event cant't fire

### ISSUE THREAD

**Issue by Cuixote** [fengyuanchen/viewerjs#180]
I'm try to fire the zoom(zoomed) event in two way:
```
new Viewer(el, {
  zoom() {
    console.log('zoom')
  }
})
```

```
el.addEventListener('zoom', () => {
  console.log('zoom')
})

new Viewer(el)
```

but noting loged when I'm zooming.

## version

viewerjs/1.1.0

## env

macOS 10.13.5

chrome 67

touchpad

**Comment by fengyuanchen** [comment]
Did you zoom the image at least once?
