### ISSUE TITLE
options.url does not handle async calls

### ISSUE THREAD

**Issue by exnihilo-creatio** [fengyuanchen/viewerjs#184]
## I'm submitting a...
<pre><code>[x ] Feature request</code></pre>

## Current behavior

When using the `options.url` as a function, it does not handle async calls.

## Expected behavior

That a `options.url` function works when `options.url` is marked as `async`, or atleast promises.

## Minimal reproduction of the problem with instructions
```
new Viewer(el, {
  async url() {
     return getimgsrcajax();
  }
})
```

## What is the motivation / use case for changing the behavior?

I need to make a backend call to retrieve a base64 string that is too large on first load.

## Environment

Latest version per `1.1.0`.

Assuming all browsers

**Comment by fengyuanchen** [comment]
You should use `async` with `await`:

```js
new Viewer(el, {
  async url() {
     return await getimgsrcajax();
  },
});
```

**Comment by exnihilo-creatio** [comment]
@fengyuanchen `await` is not needed if the function returns a function that itself returns a promise. Either way it does not work, because the code itself does not presume that promises can be returned, especially how the code `foreach`es over the images found in the list.

**Comment by fengyuanchen** [comment]
The `url` option does not support async call.
