### ISSUE TITLE
How do I make the viewer's image fill the parent container with an adaptive width

### ISSUE THREAD

**Issue by hejunMeki** [fengyuanchen/viewerjs#188]
你好，我在项目里想用你这个插件。我将toolbar工具栏的功能提取出来放到了其它位置，只在viewer里面显示图片，怎么设置可以让viewer里的图片自适应父容器的宽度啊？？？？图片如下，希望图片自适应填充线框里的dev父容器。
![image](https://user-images.githubusercontent.com/12829232/42500376-b4fb8566-8463-11e8-89bd-97e6ceba6613.png)

<script type="text/javascript">
		var viewer = new Viewer(document.getElementById('images'),{
			inline: true,   
			toolbar: false,   
			navbar: false,  
			scalable: false,
			backdrop: false
		});
	</script>

**Comment by hejunMeki** [comment]
Look forward to your reply!Thanks!

**Comment by fengyuanchen** [comment]
https://github.com/fengyuanchen/viewerjs/blob/master/.github/CONTRIBUTING.md#question-or-problem
