### ISSUE TITLE
option to style the close button in the upper right hand corner

### ISSUE THREAD

**Issue by bradburydoom** [fengyuanchen/viewerjs#190]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report 
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
Viewer.js version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

**Comment by fengyuanchen** [comment]
Why not just override the button style in CSS directly?

```css
.viewer-button {
  /* Your custom styles here */
}
```
