### ISSUE TITLE
什么时候能支持一下iframe啊，子页面用这个组件导致页面拖得很长

### ISSUE THREAD

**Issue by wangrui192** [fengyuanchen/viewerjs#191]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
Viewer.js version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

**Comment by fengyuanchen** [comment]
Cannot support that. Sorry!
