### ISSUE TITLE
在查看图片的时候，拖拽文件进入到界面，界面就会跳转，请问我该如何禁掉呢，万分感谢。

### ISSUE THREAD

**Issue by li986390329** [fengyuanchen/viewerjs#192]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
Viewer.js version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

**Comment by fengyuanchen** [comment]
八杆子打不着的问题都来这里问？！

> https://developer.mozilla.org/en-US/docs/Web/Events/dragover
