### ISSUE TITLE
Load Image Sources with JQuery

### ISSUE THREAD

**Issue by ericfang11** [fengyuanchen/viewerjs#195]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report 
[x ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

Currently, I am trying to load a different set of images with a JQuery request. Within my html, I have a set of images that is supposed to replace the current set after clicking a button. I have the syntax all the same, but once it loads, the viewer closes and bugs out.

## Expected behavior

Once clicked, I want the player to load the correct set of images.

## Environment

<pre><code>
Viewer.js version: X.Y.Z

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>
Just wondering, is this possible?

**Comment by fengyuanchen** [comment]
You should destroy the existing viewer instance before replace images, and then start a new viewer instance.
