### ISSUE TITLE
Ajax Load More Creating Multiple Lightbox

### ISSUE THREAD

**Issue by awplige** [fengyuanchen/viewerjs#196]
## I'm submitting a...

Ajax Code
<code>
viewer = new Viewer(document.getElementById('image_gallery'));
viewer.destroy(document.getElementById('image_gallery'));
viewer = new Viewer(document.getElementById('image_gallery'));
</code>

On Page Load
<code>
viewer = new Viewer(document.getElementById('image_gallery'));
</code>

<pre>
[x] Documentation issue or request
</pre>

## Current behavior
It's opeing multiple lightbox instance.

## Expected behavior
It should be open single light box with all images. After click on load more button.

## Environment
Viewer.js version: Latest

Thanks

**Comment by fengyuanchen** [comment]
I guess you don't use it in a right way.

**Comment by awplige** [comment]
Can you please tell us the structure for the load more.

We really need help.

Thanks

**Comment by fengyuanchen** [comment]
When you load more images, you should destroy the existing viewer insance first.
