### ISSUE TITLE
Viewer as independent image viewer

### ISSUE THREAD

**Issue by ishabi** [fengyuanchen/viewerjs#2]
Right now viewer works on top <img tag to get initialized. To get viewer load image, it needs original image to be loaded first. Do you have any plan to make this as independent viewer? I like viewer and like to make this to load images from a link, rather loading image in a image tag then load viewer. Do you have any suggestion for that?

**Comment by fengyuanchen** [comment]
I don't understand what you mean exactly. 

Viewer can work on a single image as:

```html
<img id="image" src="path/to/image.jpg">
```

```js
var image = document.getElementById('image');
var options = {};
var viewer = new Viewer(image, options);
```

**Comment by ishabi** [comment]
I like to bring viewer into screen without a thumbnail rendered upfront. Here what I understand is a two step process, (1) load/render image or thumbnail first (2) Select or using viewer.show() bring the viewer image to screen. I like to make it like, bring the viewer to screen without an image pre-rendered.

**Comment by fengyuanchen** [comment]
Show thumbnail is optional!. 

Please read the description about the `url` option: https://github.com/fengyuanchen/viewerjs#url

**Comment by b2bstudio** [comment]
Basically what ishabi is saying I think is;


<a href="#" class="docs-galley">view gallery</a>

<div class="docs-galley">
          <ul class="docs-pictures clearfix">
            <li><img data-original=image_01.jpg" src="image_01.jpg"></li>
            <li><img data-original="image_02.jpg" src="image_02.jpg"></li>
            <li><img data-original="image_03.jpg" src="image_03.jpg"></li>
          </ul>
</div>

Is this something you would know how to do?

**Comment by ishabi** [comment]
Yes, Thank you @b2bstudio, having a link and bringing the image in the transparent modal would be good.

**Comment by b2bstudio** [comment]
I have figured it out with css;

on first li put <li style="display:block">

and add display:none to

.docs-pictures > li {
    border: 1px solid transparent;
    display: none;
    float: left;
    height: 33.3%;
    margin: 0 -1px -1px 0;
    overflow: hidden;
    width: 33.3%;
}

then only the first image shows as a thumbnail, click the thumbnail and all the pics show in light-box.
