### ISSUE TITLE
Free Rotation and Custom Controls

### ISSUE THREAD

**Issue by MrGorki** [fengyuanchen/viewerjs#20]
It will be a great feature if there will be free rotate buttons on the toolbar which will do ++degree or --degree rotation on both sides. It seems the plugin already has the appropriate API to achieve this but I couldn't figure out to add these kind of custom buttons on the toolbar. 

Also if button customization will be allowed users can easily design such features with this kind of powerful API. Great work!

**Comment by fengyuanchen** [comment]
Support to custom toolbar buttons now (v0.9.0).
