### ISSUE TITLE
How to custom the title

### ISSUE THREAD

**Issue by liuhaoliang** [fengyuanchen/viewerjs#200]
I try to edit the title,but failed.How can i custom the title for every preview image?Can you give me an example?

<img width="499" alt="2018-09-03 10 48 12" src="https://user-images.githubusercontent.com/16020037/44965195-e5b26980-af66-11e8-9fda-7257ca74ceb2.png">
@fengyuanchen

**Comment by fengyuanchen** [comment]
```js
const options = {
  title: (image, imageData) => `${image.alt} (${imageData.naturalWidth} × ${imageData.naturalHeight})`
};
```
