### ISSUE TITLE
删除图片列表中的一张照片，再显示另外一张照片时发生了removeClass错误

### ISSUE THREAD

**Issue by CongAn** [fengyuanchen/viewerjs#201]
## 我提交了一个BUG

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

我为大图查看时增加一个删除按钮。
在用户点击删除的按钮的时，照片列表里的元素被删除了，此时需要切换上一张或者下一张大图显示。
调用`viewer.update() && viewer.view(index)`来显示，它反馈了一个错误：
TypeError: Cannot read property 'length' of undefined
    at removeClass (viewer.esm.js?7659:486)
    at Viewer.view (viewer.esm.js?7659:1821)
    at Viewer.update (viewer.esm.js?7659:2556)

如果需要demo错误，请留言，我会尽快复现一个demo。

## Expected behavior

在删除列表中的图片后，能正常展示另外一张图片

## What is the motivation / use case for changing the behavior?

在浏览图片的同时，需要更改图片列表中的元素，删除、添加等操作。
可能我更需要的是一个以数据为驱动的大图展示，我在vue上实现。

## Environment

<pre><code>
Viewer.js version: 1.2.0

Browser:
- [x] Chrome (desktop) version 版本 68.0.3440.106（正式版本） （64 位）
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>
查阅到可能需要更改代码的地方为 `viewer.esm.js` 文件 1821行
```js
    this.image = image;
    removeClass(this.items[this.index], CLASS_ACTIVE);  // 也许这里先确认 this.items[this.index] 元素是否存在再执行 removeClass 方法
    addClass(item, CLASS_ACTIVE);
```

**Comment by fengyuanchen** [comment]
建议你仅删除原始页面上的图片，然后调用 `viewer.update()` 来更新 Viewer 图片列表，而不是直接删除 Viewer 中的图片。

**Comment by CongAn** [comment]
@fengyuanchen 重新尝试了代码，发现了更具体的BUG表现，当我打开 Viewer ，直接删除最后一张图片时调用`viewer.update()`必定会出现错误`Cannot read property 'length' of undefined`。

删除非最后一张时，第一次删除时正常的，会自动切换下一张图片的大图，但是连续删除第二张时并不会切换。这也是我采用`viewer.update() && viewer.view(index)`调用方式的原因。

如果有疑问，请留言，我会尽快复现一个demo。

**Comment by fengyuanchen** [comment]
请提供demo。

**Comment by fengyuanchen** [comment]
这个问题应该已经修复了。
