### ISSUE TITLE
iframe 中调用viewer 在顶层显示时图片不居中

### ISSUE THREAD

**Issue by wellenChen** [fengyuanchen/viewerjs#206]
效果图：

![tim 20180919165305](https://user-images.githubusercontent.com/17840438/45742880-85d9e500-bc2d-11e8-9fd7-9b9f8544fa49.png)

iframe中的代码：
<pre><code>
var vd = new viewer(document.getElementById(pId),
                                            {
                                                url: 'layer-src',//原图路径
                                                container: $("body", top.window.document)[0],
                                                loop: true,//循环
                                                scalable: false,//反转
                                                toolbar: {
                                                    zoomIn: 1,
                                                    zoomOut: 1,
                                                    oneToOne: 0,
                                                    reset: 0,
                                                    prev: 1,
                                                    play: {
                                                        show: 1,
                                                        size: 'large',
                                                    },
                                                    next: 1,
                                                    rotateLeft: 1,
                                                    rotateRight: 1,
                                                    flipHorizontal: 1,
                                                    flipVertical: 1,
                                                },
                                                hidden: function () {
                                                    vd.destroy()
                                                }
                                            });
</code></pre>
请问该如何解决这问题？

**Comment by fengyuanchen** [comment]
能否提供一个在线Demo？

**Comment by Frank-MJ** [comment]
> 效果图：
> 
> ![tim 20180919165305](https://user-images.githubusercontent.com/17840438/45742880-85d9e500-bc2d-11e8-9fd7-9b9f8544fa49.png)
> 
> iframe中的代码：
> 
> ```
> 
> var vd = new viewer(document.getElementById(pId),
>                                             {
>                                                 url: 'layer-src',//原图路径
>                                                 container: $("body", top.window.document)[0],
>                                                 loop: true,//循环
>                                                 scalable: false,//反转
>                                                 toolbar: {
>                                                     zoomIn: 1,
>                                                     zoomOut: 1,
>                                                     oneToOne: 0,
>                                                     reset: 0,
>                                                     prev: 1,
>                                                     play: {
>                                                         show: 1,
>                                                         size: 'large',
>                                                     },
>                                                     next: 1,
>                                                     rotateLeft: 1,
>                                                     rotateRight: 1,
>                                                     flipHorizontal: 1,
>                                                     flipVertical: 1,
>                                                 },
>                                                 hidden: function () {
>                                                     vd.destroy()
>                                                 }
>                                             });
> ```
> 
> 请问该如何解决这问题？

请问图片居中的问题，你解决了吗？

**Comment by wellenChen** [comment]
> > 效果图：
> > ![tim 20180919165305](https://user-images.githubusercontent.com/17840438/45742880-85d9e500-bc2d-11e8-9fd7-9b9f8544fa49.png)
> > iframe中的代码：
> > ```
> > 
> > var vd = new viewer(document.getElementById(pId),
> >                                             {
> >                                                 url: 'layer-src',//原图路径
> >                                                 container: $("body", top.window.document)[0],
> >                                                 loop: true,//循环
> >                                                 scalable: false,//反转
> >                                                 toolbar: {
> >                                                     zoomIn: 1,
> >                                                     zoomOut: 1,
> >                                                     oneToOne: 0,
> >                                                     reset: 0,
> >                                                     prev: 1,
> >                                                     play: {
> >                                                         show: 1,
> >                                                         size: 'large',
> >                                                     },
> >                                                     next: 1,
> >                                                     rotateLeft: 1,
> >                                                     rotateRight: 1,
> >                                                     flipHorizontal: 1,
> >                                                     flipVertical: 1,
> >                                                 },
> >                                                 hidden: function () {
> >                                                     vd.destroy()
> >                                                 }
> >                                             });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 请问该如何解决这问题？
> 
> 请问图片居中的问题，你解决了吗？

修改了源码
![image](https://user-images.githubusercontent.com/17840438/121321168-70a6c680-c940-11eb-909e-cbf75d55ed49.png)

![image](https://user-images.githubusercontent.com/17840438/121321285-8ae0a480-c940-11eb-899c-2389f9cc41fb.png)

**Comment by fengyuanchen** [comment]
建议在顶层窗口中，引入 Viewer.js 的脚步和样式，然后在 iframe 内部直接调用顶层 Viewer.js （仅限同域）:

```js
// In iframe
const viewer = new window.top.Viewer(imagesWithinIfrmae);
```
