### ISSUE TITLE
多次new Viewer好像有问题

### ISSUE THREAD

**Issue by specYyt** [fengyuanchen/viewerjs#207]
我的使用场景是这样的
![tim 20180923193256](https://user-images.githubusercontent.com/30110741/45927552-98268c80-bf67-11e8-807e-7cd2ce211ac6.png)
每当点击一个下拉栏里的选项，都会发送ajax请求后台返回相应的图片，在返回完图片后，我就new Viewer，但是当我点击另一个选项的时候，new出来的Viewer放大时变成了下面的样子
![tim 20180923193557](https://user-images.githubusercontent.com/30110741/45927584-fce1e700-bf67-11e8-967b-b3975264dd2e.png)
同时控制台会报错
![tim 20180923193716](https://user-images.githubusercontent.com/30110741/45927593-1c790f80-bf68-11e8-8573-d01df9713c73.png)
我不是很懂前端，请你有空帮忙看下

**Comment by specYyt** [comment]
![tim 20180923194109](https://user-images.githubusercontent.com/30110741/45927630-b04adb80-bf68-11e8-93ff-8843a590a649.png)

**Comment by fengyuanchen** [comment]
在第二次 new Viewer 之前需要注销之前的 Viewer 实例：`viewer.destroy()`
