### ISSUE TITLE
Can you support setting custom backdrop color?

### ISSUE THREAD

**Issue by mygu** [fengyuanchen/viewerjs#209]
## Can you support setting custom backdrop color?

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report 
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

Now, the `backdrop` option can only support `true` or `false`

## Expected behavior

I want to set the `backdrop` option custom background color, it's look like:

```javascript
var viewer = new Viewer(element, {
  backdrop: 'rgba(255, 255, 255, 0.7)'
});
```

## What is the motivation / use case for changing the behavior?

The current default background color is not friendly to some transparent images

![20181010110706](https://user-images.githubusercontent.com/3753924/46711270-2b590500-cc7e-11e8-8190-26bd71cd617b.png)

## Environment

<pre><code>
Viewer.js version: X.Y.Z

Browser:
- [x] Chrome (desktop) version 68.0.3440.84
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

**Comment by fengyuanchen** [comment]
Why not just override the existing background color in your own code?

```css
.viewer-backdrop {
  /* Your custom background color here. */
  background-color: rgba(0, 0, 0, .5); 
}
```

**Comment by mygu** [comment]
> Why not just override the existing background color in your own code?
> 
> ```css
> .viewer-backdrop {
>   /* Your custom background color here. */
>   background-color: rgba(0, 0, 0, .5); 
> }
> ```

I tried it, but it changes the overall background color. What I need is some pages, some of which have a black background and some white background.

**Comment by fengyuanchen** [comment]
@mygu A new option `className` has been added to Viewer.js (v1.3.0) for your case.

**Comment by mygu** [comment]
@fengyuanchen Thanks a lot :)
