### ISSUE TITLE
安卓微信端backdrop点击行为奇怪

### ISSUE THREAD

**Issue by leafiy** [fengyuanchen/viewerjs#210]
使用微信浏览官方demo，点击backdrop不能关闭，并且出现奇怪的跳转行为
![gif_20181012_162456](https://user-images.githubusercontent.com/870449/46857488-a4ea2200-ce3b-11e8-9949-0c4cdae73a49.gif)

**Comment by Zefeng666** [comment]
我也遇到了，请问你解决了吗？
