### ISSUE TITLE
可以加入图片加载数量控制功能

### ISSUE THREAD

**Issue by KOHGYLW** [fengyuanchen/viewerjs#214]
首先感谢作者提供这样一款非常好用的图片展示工具。希望该工具能增加图片加载数量的控制功能：例如声明了1000张图片，在初始化viewer时设定最大显示长度为5张。则：
1，初始化viewer并加载初始图片及其两侧各5张图片。
2，用户切换图片时，重新载入图片列表，将要显示的图片和两侧的最多5张图加载为新列表并显示。
3，每次切换迭代2.

这样在图片数目很大且图片体积很大时能够获得更好的体验！

**Comment by fengyuanchen** [comment]
这个功能不应该由 Viewer 来实现，否则 Viewer 将会越来越臃肿。你可以用一个DIV元素把每5张图片包在一起，然后每次在一个DIV元素上调用 Viewer。
