### ISSUE TITLE
rotate events missing

### ISSUE THREAD

**Issue by Kasheftin** [fengyuanchen/viewerjs#215]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report 
[X] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

I've read that the viewerjs currently supports 9 events. For example, it supports zoom and zoomed events. It's a good start. Do you have a plans about implementing all other events as well? I personally need a rotate (or rotated) event to fire when the image was rotated. I want to get the angle and show 'save' button if it's not zero (it will send the request to update an image on server side). Is it currently possible to achieve?  

## Environment

<pre><code>
Viewer.js version: v1.3.0

Browser:
- [X] Chrome (desktop) version 65.0.3325.162
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

</code></pre>

**Comment by fengyuanchen** [comment]
You can customize the toolbar totally and add click event handler for all actions.

Example: https://github.com/fengyuanchen/viewerjs/blob/master/examples/custom-toolbar.html
