### ISSUE TITLE
动态加载图片

### ISSUE THREAD

**Issue by mysea** [fengyuanchen/viewerjs#218]
你好，请教一下，现在的需求是点击缩略图时请求原图数据，成功后显示原图，但是请求数据成功后，使用update无效，第二次点击的时候才显示原图。
其中代码如下：
`
if (data.success == true) {
                        $("#img" + AnnotationId).attr('data-original', "data:image/png;base64," + data.data.DocumentBody);
                        $("#ImgList" + workid).viewer('update');
}
`

**Comment by fengyuanchen** [comment]
请参考：https://fengyuanchen.github.io/viewerjs

**Comment by mysea** [comment]
恕我愚钝，这个网站我看过了，除了没有update方法之外，并没有什么帮助的信息

**Comment by fengyuanchen** [comment]
```html
<!-- src 是默认加载的缩略图，data-original 是点击查看后才加载的原图 -->
<img src="images/thumbnails/tibet-1.jpg" data-original="images/tibet-1.jpg">
```

**Comment by mysea** [comment]
> ```
> 
> <img src="images/thumbnails/tibet-1.jpg" data-original="images/tibet-1.jpg">
> ```

是这样的，一开始在页面上加载时，显示的是缩略图，缩略图的数据放在src属性里，设置data-original为“”，然后点击缩略图的时候请求原图数据，设置原图的数据为data-original属性的值，然后调用update方法

**Comment by fengyuanchen** [comment]
实在无法理解你这种操作。。你这不是多此一举？！

**Comment by mysea** [comment]
> 实在无法理解你这种操作。。你这不是多此一举？！

因为有些图片比较大，列表显示缩略图，点击具体某张图片才请求原图显示，然后update方法没有效果，所以才来请教您的

**Comment by KevinPan** [comment]
试了一下啊data-original 没有其作用，但是首页文档的方法是可以的
<img src="picture.jpg?size=160">
new Viewer(image, {
  url(image) {
    return image.src.replace('?size=160', '');
  },
});

**Comment by fengyuanchen** [comment]
@KevinPan 还需要配置`url`参数：

```js
new Viewer(image, {
  url: 'data-original',
});
```

或者

```js
new Viewer(image, {
  url(image) {
    return image.getAttribute('data-original'),
  },
});
```

**Comment by Choigakay** [comment]
url支持异步返回的数据吗

**Comment by fengyuanchen** [comment]
@Choigakay 不支持。

**Comment by dearzoe** [comment]
> ```js
> url: 'data-original',
> ```

or
```
Vue.use(Viewer);
Viewer.setDefaults({
  url: 'data-original',
});
```
