### ISSUE TITLE
AJAX添加的图片，update出错。

### ISSUE THREAD

**Issue by icyflash** [fengyuanchen/viewerjs#22]
初始化时
```
<ul id="images">
</ul>
```

```
var viewer = new Viewer(document.getElementById('images'), options);
```

然后通过AJAX请求图片，之后update
```
viewer.update();
```

JS报错， update方法里面的 _this.images 为 undefined.

PS：我为什么不在Ajax请求后new Viewer()？因为这个是对话页面，Ajax轮循获取消息，不保证每次请求都有返回，不保证每次返回都是图片消息。所以只能先初始化。

**Comment by fengyuanchen** [comment]
一张图片都没有，这确实是极端情况。你可以先试试每次加载完新图片后，先注销，然后重新初始化。

**Comment by donggaina** [comment]
ajax动态请求加载的图片，图片加载后初始化了viewer,但是图片查看只有第一次有效

**Comment by jiegeng797** [comment]
请问这个问题解决了吗？我遇到了相同的问题，求帮助

**Comment by jiegeng797** [comment]
现在效果已经出来了，但是有个报错
![wxyt11](https://cloud.githubusercontent.com/assets/10555381/23396150/3014a742-fdcd-11e6-9a98-0068135dafad.png)
![wxyt22](https://cloud.githubusercontent.com/assets/10555381/23396151/3023dde8-fdcd-11e6-8f18-6e9c7e3b1d6b.png)

**Comment by donggaina** [comment]
解决了，我的是页面加载后，后续点击ajax请求获取图片，因为有多处请求，所以会出现只有第一次有效。


我在页面加载就初始化了viewer，ajax请求成功后代码如图，就好了。，



在 2017-02-28 10:50:16，"jiegeng797" <notifications@github.com> 写道：


请问这个问题解决了吗？我遇到了相同的问题，求帮助

**Comment by donggaina** [comment]
if(viewer){
                                    viewer.destroy();
                                    viewer = new Viewer(document.querySelector('.docs-pictures'));
                                }

**Comment by jiegeng797** [comment]
非常感谢，问题解决了

**Comment by style65** [comment]
@donggaina 为什么我每次请求都是重新生成一个实例啊，没有注销旧的啊 ！

**Comment by zhangnan666** [comment]
nice
