### ISSUE TITLE
vue ssr项目里报没有loader的错

### ISSUE THREAD

**Issue by anneincoding** [fengyuanchen/viewerjs#224]
ERROR  Failed to compile with 1 errors                            下午7:01:28

            error  in ./node_modules/viewerjs/dist/viewer.css

            Module parse failed: Unexpected token (11:0)
           You may need an appropriate loader to handle this file type.
           |  */
           |
           > .viewer-zoom-in::before,
           | .viewer-zoom-out::before,
           | .viewer-one-to-one::before,

          @ ./src/main.js 33:0-34
          @ ./src/entry-server.js

**Comment by fengyuanchen** [comment]
你用的是Webpack？没有配置`css-loader`？
