### ISSUE TITLE
iOS 點擊 backdrop 無法關閉

### ISSUE THREAD

**Issue by joey91133** [fengyuanchen/viewerjs#226]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
桌機及Android點擊 backdrop 都可以關閉，但唯獨 iOS 不行

## Environment

<pre><code>
Viewer.js version: 1.3.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [x] Safari (iOS) version 12
- [ ] IE version XX
- [ ] Edge version XX

**Comment by fengyuanchen** [comment]
see #210

**Comment by sdhhqb** [comment]
have met similar situation, touch backdrop on the phone can't close dialog 
thanks a lot for fix it so quick.
