### ISSUE TITLE
custom control for toolbar or custom icon

### ISSUE THREAD

**Issue by zmqcherish** [fengyuanchen/viewerjs#228]
I want to add some custom control for toolbar, maybe set cover or delete image.
I can set the toolbar custom function like below:
`toolbar: {reset: myFuncName}`,
but the 'reset' icon does not has the same mean as my func(may be to delete the image),
how can I to realize it, thanks

**Comment by Maryamdeveloper** [comment]
@zmqcherish Hi, how did you fix the problem? I cannot change the icons either

**Comment by fengyuanchen** [comment]
> @zmqcherish Hi, how did you fix the problem? I cannot change the icons either

Just override the icon with CSS styles.
