### ISSUE TITLE
Image Background turn Black when rotate png image and save. 

### ISSUE THREAD

**Issue by ankurmee** [fengyuanchen/viewerjs#23]
Image Background turn Black when rotate png image and save.  you can test it with any png file.
![00001256](https://cloud.githubusercontent.com/assets/18263356/14249324/da3869f6-fa96-11e5-93da-834f89d19187.png)

**Comment by fengyuanchen** [comment]
Were you talk about the Viewer.js?

**Comment by ankurmee** [comment]
Yes

**Comment by fengyuanchen** [comment]
What did you mean the **save**?

**Comment by ankurmee** [comment]
Click on this button.

**Comment by ankurmee** [comment]
May I know the reason to close this Issue ?

**Comment by fengyuanchen** [comment]
Where is the "save" button?!

**Comment by fengyuanchen** [comment]
Can you provide more detail or an online demo?

**Comment by ankurmee** [comment]
Save button is on the zoom window where we have all other options.
