### ISSUE TITLE
Bug: hiding navbar also hides toolbar

### ISSUE THREAD

**Issue by dimsav** [fengyuanchen/viewerjs#230]
Hello, when I set the following configuration to hide the navbar, the toolbar is also gone:

```
{
  navbar: false,
}
```

Tested in 

- Firefox 65
- Chrome 70

Viewer.js version: v1.3.1

**Comment by fengyuanchen** [comment]
Can not reproduce.

**Comment by fengyuanchen** [comment]
Any online demo?
