### ISSUE TITLE
图片预览工具栏增加打印当前图片

### ISSUE THREAD

**Issue by wanggja** [fengyuanchen/viewerjs#231]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report 
[x] Feature request
[x] Documentation issue or request
</code>在工具栏上可以增加打印当前预览图片按钮吗</pre>

## Current behavior
浏览图片时无法直接调用打印程序接口打印图片

## Expected behavior
在图片预览工具栏增加打印图标，点击打印发送异步请求将当前图片信息到服务器或者直接调用打印机程序

## Environment

<pre><code>
Viewer.js version: X.Y.Z

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x ] Firefox version XX
- [x ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

**Comment by fengyuanchen** [comment]
请根据文档自定义工具栏按钮。
