### ISSUE TITLE
使用filter方法之后,点击图片不会从当前位置开始播放

### ISSUE THREAD

**Issue by LongYue9608** [fengyuanchen/viewerjs#232]
不知道你们有没有遇到这种问题-每次我都要自己调view()传下标

**Comment by fengyuanchen** [comment]
请描述清楚一点，或者提供可以复现的在线示例。

**Comment by LongYue9608** [comment]
> 请描述清楚一点，或者提供可以复现的在线示例。

周末我去仔细看下，然后回复你。

**Comment by LongYue9608** [comment]
emmm,应该是因为viewer不会动态刷新里面的图片个数~我添加图片后调用了upload方法导致的。 @fengyuanchen
