### ISSUE TITLE
快速切换图片会有闪烁的情况

### ISSUE THREAD

**Issue by HGleng** [fengyuanchen/viewerjs#233]
有需求要查看序列图片，快速切换效果类似gif
更改了部分功能  使得可以使用鼠标滚轮切换图片
但是发现切换时，会有闪烁，一定程度上影响用户体验
想知道有没有什么办法可以解决

**Comment by fengyuanchen** [comment]
Set the `transition` option to `false`.

**Comment by Myqilixiang** [comment]
> Set the `transition` option to `false`.

现有需求对数百张图片进行快速浏览，已经关闭transition，且在show事件出发后，顺序通过new img()方式讲所需浏览的图片进行预加载，但是快速浏览时候还是会出现闪烁情况，具体表现为张图片浏览之间会有空白闪烁，怀疑是浏览器渲染用时导致，想请教一下有什么好的解决方法
