### ISSUE TITLE
如何实现双击预览图片

### ISSUE THREAD

**Issue by myDancer** [fengyuanchen/viewerjs#234]
我看了文档，有个toggleOnDblclick的选项，但是好像没有用。

然后我自己实现了一个

$('img').dblclick(function(){
                var $image =  $(this);
                $image.viewer({title: false, hidden: function(){
                    viewer.destroy();
                }});
                var viewer = $image.data('viewer');
                viewer.show();
 });

但是感觉不够优雅，请问如何实现比较优雅

**Comment by fengyuanchen** [comment]
这样就可以了。
