### ISSUE TITLE
update()方法的问题

### ISSUE THREAD

**Issue by LongYue9608** [fengyuanchen/viewerjs#238]
页面中有分类的图片,标题如A、B、C图片的容器结构是一样的 我希望点击A标题下面的图片 viewer中的图片全是A类型的,然后点击B，viewer中的图片全是B类型的，我的做法是这样的 如果第一次点击A，则创建一个实例  然后点击B，判断viewer是否存在 存在则调用update方法，但是viewer中缺依然全是A类型的，然后我换了中方法 ，每点击一次都销毁重新创建一个实例  这样虽然可以实现，但是，如果这样，我一删除一张图片 再点击其他的 就会出现 Cannot read property 'length' of undefined的错误

**Comment by LongYue9608** [comment]
初始化 viewer = new Viewer($(this).parent().parent().parent().get(0), {
					filter(image) {
						return $($(image).attr("inx") == "true").get(0);
					},
				});

**Comment by LongYue9608** [comment]
我确定我点击B类型的图片传的this的指向已经变了,但是update()后viewer中的图片还是还是A类型的

**Comment by fengyuanchen** [comment]
点击 => 创建实例
关闭 => 注销实例
不需要调用update方法
