### ISSUE TITLE
close on click

### ISSUE THREAD

**Issue by ddaydd** [fengyuanchen/viewerjs#24]
First, thanks for great plugin.

Can you implement closed by clicking on the picture or outside?

Thanks :)

**Comment by fengyuanchen** [comment]
Sorry, we don't need this feature, but you can folk one and customize it by yourself.

**Comment by disav1** [comment]
var options = {
        viewed: function () {
            var context = $(this);
            $('.viewer-canvas').click(function(e){
                if(e.target.className == 'viewer-canvas') {
                     context.viewer('hide');
                }
            });
        },
        url: 'data-original',
    };

**Comment by kongyajie** [comment]
viewed: function () {
      var context = this;
      $('.viewer-canvas').click(function(e){
        if(e.target.className == 'viewer-canvas') {
          context.viewer.hide();
        }
      });
    }

ps: Viewer.js v0.5.0

**Comment by vishal-chauhan97** [comment]
I am trying to acheive this in 2019 guys, please help. I tried a lot of things any help would be appreciated.

**Comment by shuiRong** [comment]
@befit21  Thanks your code.

**Comment by Skill-For-Kill** [comment]
without jquery:

 ```
 viewerOptions: {
 ...
viewed() {
      const context = this;
      const list = document.querySelectorAll('.viewer-canvas');

      list.forEach(elem => {
        elem.addEventListener('click', (event: any) => {
          context.viewer.hide();
        });
      });
    }
    }
```
