### ISSUE TITLE
多幅快速点击的时候 会卡死

### ISSUE THREAD

**Issue by xiaoyan-hou** [fengyuanchen/viewerjs#243]
## 多幅图片快速点击会卡死

点击的时候会 new viewer() , 同时new 之前会先销毁之前的。 但是快速点击几幅图片的时候 会无法弹出图片，控制台报错  Uncaught TypeError: Cannot read property 'removeEventListener' of null

## 环境
chrome 71 浏览器
vue组件中

**Comment by fengyuanchen** [comment]
无法复现。

**Comment by xiaoyan-hou** [comment]
> 无法复现。

我这边虽然不是固定的，但是很容易复现，方便的话我可以录给视频给您。 另外，我看代码发现报错 是因为 快速点击过程中  先调用 hide,  hidden, resetImage等方法，其中resetimage方法中  this.image = null,  此时不知道哪个触发的异步函数，addListener 的时候， element 为this.image 为null， 所以 报错了
