### ISSUE TITLE
请教如何支持打开PDF文件查看.感谢!

### ISSUE THREAD

**Issue by LLerver** [fengyuanchen/viewerjs#244]
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report 
- [x] Feature request
- [x] Documentation issue or request

## Environment

Viewer.js version: X.Y.Z

Browser:

- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

**Comment by fengyuanchen** [comment]
This is an image viewer, not PDF.

**Comment by Benleie** [comment]
2022了，可以考虑加上这个功能吗:)

**Comment by fengyuanchen** [comment]
@Benleie 这是一个简单的图片查看器，不是万物查看系统。。
