### ISSUE TITLE
请问给viewer.js插件指定某个父容器,并且让其填充整个父容器大小.感谢~因为一直再写后端,前端是重灾区.目前前端是使用easyUI写的JSP页面

### ISSUE THREAD

**Issue by LLerver** [fengyuanchen/viewerjs#245]
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report 
- [x] Feature request
- [ ] Documentation issue or request

## Environment

Viewer.js version: X.Y.Z

Browser:

- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

**Comment by fengyuanchen** [comment]
试试 Inline 模式。
