### ISSUE TITLE
多张图片快速点击 会报错，导致页面卡死现象

### ISSUE THREAD

**Issue by xiaoyan-hou** [fengyuanchen/viewerjs#247]
## 多张图片modal 模式下， 分别快速点击不同的图像或者同一幅图片，连续点击10-30次会出现问题
这个复现最好使用鼠标点击，可以很快复现，但是复现也是随机的，连续点击不要放弃，会出现
(需要快速连续点击确实是业务场景中会这么做，并非故意测试，所以现在也算出现问题了)

## 出错时，控制台报错截图
chrome 71.0，mac pro， 官网demo 报错截图如下

![](http://ww1.sinaimg.cn/large/b0b365f5ly1fzy2cdilx0j227o19o4qp.jpg)

## Environment

Viewer.js version: 官网demo  https://fengyuanchen.github.io/viewerjs/

Browser:

- [ ] Chrome (desktop) version 71.0

**Comment by fengyuanchen** [comment]
因为每点击一张图片，就加载一张图片，多张图片同时加载导致页面卡顿。新版本已修复该问题。
