### ISSUE TITLE
viewer-open class in the body tag

### ISSUE THREAD

**Issue by MartDSam** [fengyuanchen/viewerjs#249]
Adding the viewer-open class in the body tag causes my site scroll to skip to the top. My gallery is on the site footer. The correct one would not add this class to the HTML tag? For it is the HTML tag that has the scroll.

Testing with the class in the HTML tag does not happen.

**Comment by fengyuanchen** [comment]
The `viewer-open` is similar as `modal-open` of [Bootstrap's Modal](https://getbootstrap.com/docs/4.3/components/modal/).

**Comment by fengyuanchen** [comment]
Why the page will scroll to the top after viewer open? Any demo?

**Comment by MartDSam** [comment]
I discovered the source of the problem. My body tag was set to height: 100% and that made the page scroll to the top when I opened the gallery.

I just leave the body with height: auto; that everything is normal.

Now I do not know if this is a library or browser problem. I use the latest version of chrome.
