### ISSUE TITLE
support it like params(currentUrl, urls[])

### ISSUE THREAD

**Issue by OnlyFlyer** [fengyuanchen/viewerjs#251]
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report 
- [x] Feature request
- [ ] Documentation issue or request

## Expected behavior

Invocation methods like as follows:

```
new Viewer('aa.png', ['aa.png', 'bb.png', 'cc.png'])

```
and don't more config, can you ? thanks

## Environment

Viewer.js version: X.Y.Z

Browser:

- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX

Others:

**Comment by fengyuanchen** [comment]
Will not support this, sorry.
