### ISSUE TITLE
Print support?

### ISSUE THREAD

**Issue by carlshe** [fengyuanchen/viewerjs#252]
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report 
- [x] Feature request
- [ ] Documentation issue or request

## Environment

Viewer.js version: X.Y.Z

Browser:

- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version XX
- [ ] Edge version XX

Others:

**Comment by carlshe** [comment]
Could viewerjs support print current image?

**Comment by fengyuanchen** [comment]
Not support that. I'm sorry.
