### ISSUE TITLE
Allow simple markup/drawing.

### ISSUE THREAD

**Issue by MatthewSH** [fengyuanchen/viewerjs#253]
Not sure if this is even possible for the scope of this project.

Is it possible that we could get markup? Like simple drawing. Rectangles, circles, custom lines, etc. Nothing crazy and don't even need to save it. 

Would it have to be converted to canvas to do this? Maybe there's another library that can do what ViewerJS does and allow markup?

**Comment by fengyuanchen** [comment]
You might need an image editor, not this as this is an image viewer.
