### ISSUE TITLE
Fullscreen IE11 works only 1 time

### ISSUE THREAD

**Issue by DerNoirProQrent** [fengyuanchen/viewerjs#254]
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x ] Bug report 
- [ ] Feature request
- [ ] Documentation issue or request

## Current behavior

When i open an image with Fullscreen it works well. But if i open it again, it will not work.

## Expected behavior

It should be shown like the 1 befor.

## Minimal reproduction of the problem with instructions

The Problem is die Object will not be change in IE11:
Befor Fullscreen:
`{
   [functions]: ,
   __proto__: { },
   action: false,
   body: { },
   element: { },
   fading: false,
   fulled: false,
   hiding: false,
   imageClicked: false,
   imageData: { },
   images: [ ],
   index: 0,
   initialBodyPaddingRight: "0px",
   isImg: true,
   isShown: false,
   length: 1,
   options: { },
   played: false,
   playing: false,
   pointers: { },
   ready: false,
   scrollbarWidth: 0,
   showing: false,
   Symbol(rxSubscriber)_g.66p6t24htc9: undefined,
   Symbol(rxSubscriber)_h.66p6t24htc9: undefined,
   Symbol(util.promisify.custom)_i.66p6t24htc9: undefined,
   timeout: false,
   tooltipping: false,
   viewed: false,
   viewing: false,
   wheeling: false,
   zooming: false
}`

After Fullscreen:
`{
   [functions]: ,
   __proto__: { },
   action: false,
   body: { },
   button: { },
   canvas: { },
   containerData: { },
   element: { },
   fading: false,
   footer: { },
   fulled: true,
   hiding: false,
   image: { },
   imageClicked: false,
   imageData: { },
   imageInitializing: false,
   imageRendering: false,
   images: [ ],
   index: 0,
   initialBodyPaddingRight: "0px",
   initialImageData: { },
   isImg: true,
   isShown: true,
   items: { },
   length: 1,
   list: { },
   navbar: { },
   options: { },
   parent: { },
   played: false,
   player: { },
   playing: false,
   pointers: { },
   ready: true,
   scrollbarWidth: 0,
   showing: false,
   Symbol(rxSubscriber)_g.66p6t24htc9: undefined,
   Symbol(rxSubscriber)_h.66p6t24htc9: undefined,
   Symbol(util.promisify.custom)_i.66p6t24htc9: undefined,
   timeout: false,
   title: { },
   toolbar: { },
   tooltipBox: { },
   tooltipping: false,
   transitioning: { },
   viewed: true,
   viewer: { },
   viewerData: { },
   viewing: false,
   wheeling: false,
   zooming: false
}`

If i close the Fullscreen on Chrome or Firefox it will be changed to the Frist Example.
But on IE11 it will stay on the second Example.

## Environment

Viewer.js version: 1.3.2 (It works in 0.10.0)

Browser:

- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x ] IE version 11
- [ ] Edge version XX

**Comment by DerNoirProQrent** [comment]
The error only occurs if you include it twice on the page.

**Comment by fengyuanchen** [comment]
So don't include it twice on the same page!
