### ISSUE TITLE
It not work on my website

### ISSUE THREAD

**Issue by liub1934** [fengyuanchen/viewerjs#257]
## It not work on my website,and the error
![image](https://user-images.githubusercontent.com/29849550/53862459-722b0b00-4022-11e9-821b-41d118992504.png)
![image](https://user-images.githubusercontent.com/29849550/53862490-853ddb00-4022-11e9-8bdd-5bd12878cc46.png)
![image](https://user-images.githubusercontent.com/29849550/53862675-06956d80-4023-11e9-960d-9b80cb8004ac.png)

# my code
```
var $postContent = document.getElementById('post-content');
if($postContent){
  var imgViewer = new Viewer($postContent);
 }
```

- [ x ] Bug report 

## What is the motivation / use case for changing the behavior?

https://liub37.com/28.html
## Environment

Viewer.js version: v1.3.2

Browser:

- [ x ] Chrome (desktop) version 71.0.3578.98

Others:

**Comment by fengyuanchen** [comment]
I think it is not a problem with Viewer.js. Please check your own code.
