### ISSUE TITLE
Ajax content image download for thumbnail and full size of image

### ISSUE THREAD

**Issue by cretara** [fengyuanchen/viewerjs#260]
Hi all,
premise: i use Ajax to download content of both thumbnail and image at full size; the content is retrieved from DB in Base64 format for both of them, while resize and compression are made during upload of content.
My intention is to preview thumbnail format and then, after clicking on it, download it's content to full size to reduce loading time of the page.

Any idea how to implement this? Should use "url" option to obtain what i described? How?

How can i retrieve the index of image selected by user when he parses the gallery?

Regards.

**Comment by fengyuanchen** [comment]
Just read the documentation and try it.
