### ISSUE TITLE
H5端控件icon样式手机屏幕适配问题

### ISSUE THREAD

**Issue by Jeazun** [fengyuanchen/viewerjs#261]
图片查看的控件样式错乱
1.出问题的手机：移动端【iPhone 6/7/8 plus】的414px像素的放大模式或者320px屏幕大小（非375像素或750像素时出现的错乱问题）
2.导致的原因：
    使用移动端rem适配方案后,会自动转换了background-position设置的px像素，导致sprite的图片定位不准确，但是sprite图片的大小并没有改变，所以导致了定位出现了问题。
3.解决方案：
   在引入spritete图的时候设置background-size的大小为图片的原始大小  background-size: 280px，就可适配各屏幕手机，包括414px以及320px下都不会出现控件错乱问题。
以下为问题截图：
![image](https://user-images.githubusercontent.com/36723413/55045805-2811d400-507a-11e9-848d-17e32cd8fc29.png)
解决方案：
 设置background-size的默认值
`
.viewer-zoom-in::before,.viewer-zoom-out::before,.viewer-one-to-one::before,.viewer-reset::before,.viewer-prev::before,.viewer-play::before,.viewer-next::before,.viewer-rotate-left::before,.viewer-rotate-right::before,.viewer-flip-horizontal::before,.viewer-flip-vertical::before,.viewer-fullscreen::before,.viewer-fullscreen-exit::before,.viewer-close::before
 {  background-size: 280px;
}`
设置之后，以下为设置之后的正常截图
![image](https://user-images.githubusercontent.com/36723413/55050385-6499fb80-508b-11e9-848d-583ea1ba2a87.png)

**Comment by fengyuanchen** [comment]
Fixed by #262.
