### ISSUE TITLE
Why click second time can show the picture,if click first time can not

### ISSUE THREAD

**Issue by Angkor-What** [fengyuanchen/viewerjs#271]
**Describe the bug**
When I click the picture at first time,can not see the picture,untill I click second time that show the picture.I see piture had URL when the HTML render already.So I dont know what happen.

![2019-04-18](https://user-images.githubusercontent.com/28755948/56336277-4dee4c80-61d2-11e9-9391-4736ddb32965.png)

**Comment by fengyuanchen** [comment]
I have not idea on this.

**Comment by destus90** [comment]
@Angkor-What see this #203. Maybe it will help you.
