### ISSUE TITLE
navbar does not show the last picture

### ISSUE THREAD

**Issue by EmirCanSANCAR** [fengyuanchen/viewerjs#272]
navbar is hiding it when you click on the last picture.

The viewer-list element has a size limit and does not fit. I solved this problem in this way.
I think the size of the viewer-list element should be removed and centered.

```
<style>
    .viewer-list {
        width: auto !important;
        transform: none !important;
        display: inline-block !important;
    }
</style>
```

![viewer-list](https://user-images.githubusercontent.com/16269350/56492386-573e2880-64f4-11e9-81ab-185e23aa3473.gif)

**Comment by fengyuanchen** [comment]
You can set the `transition` option to `false` and try again.

**Comment by EmirCanSANCAR** [comment]
No animation, the last element is lost again. Is there a way to solve this in an animated way?

**Comment by fengyuanchen** [comment]
I have not idea on this. Try to check your own code again.
