### ISSUE TITLE
使用viewerjs组件，打包项目后导致element-ui样式文件未生成

### ISSUE THREAD

**Issue by gloria912** [fengyuanchen/viewerjs#274]
**Describe the bug**
使用viewerjs组件，打包项目后导致element-ui样式文件未生成

**To Reproduce**
<div id="viewr" class="images" style="display: none;">
    <img :src="currSrc">
</div>

const ViewerDom = document.getElementById('viewr');
this.viewer = new Viewer(ViewerDom, {
          // 相关配置项,详情见下面
          navbar: false,
          title: false,
          toolbar: {
            zoomIn: true,
            zoomOut: true,
            reset: true,
            prev: false,
            next: false,
            play: true,
            rotateLeft: true,
            rotateRight: true,
            flipHorizontal: true,
            flipVertical: true,
          },
});
this.viewer.show();

**Comment by fengyuanchen** [comment]
这是你打包配置问题吧？确定跟 Viewer.js 有关系？
