### ISSUE TITLE
黑色背景的FadeOut效果出不来

### ISSUE THREAD

**Issue by qiangbro** [fengyuanchen/viewerjs#275]
**Describe the bug**
当modal打开后，点击关闭，黑色背景一下子就消失了， 它应该是渐渐消失的。

问题的原因我发现了，代码问题，点击关闭时没有及时移除顶级元素上的viewer-in

**Desktop (please complete the following information):**
 - OS: win7
 - chrome 73

**Comment by fengyuanchen** [comment]
1. 你的浏览器支持 CSS Transition 吗？
2. 你设置 `transition` 参数为 `false` 了吗？
3. 你确定是可以复现的问题吗？

**Comment by qiangbro** [comment]
@fengyuanchen 
1. 浏览器支持
2. transition未设为 false
3. 确定可以复现，请看你的官方示例 https://fengyuanchen.github.io/viewerjs/
付现步骤：1.点击第一张图片 2.等图片展示出来以后，点击右上角叉号 3.黑色背景瞬间就消失了，而不是渐变消失。
