### ISSUE TITLE
display image number on the view

### ISSUE THREAD

**Issue by pdeman** [fengyuanchen/viewerjs#278]
is it possible to display the "image number/total number of image" instead of the title (and increase the size of the text ?)

**Comment by fengyuanchen** [comment]
Try this:

```js
new Viewer(images, {
  title: function () {
    return `(${this.index + 1} / ${this.length})`;
  },
});
```

```css
.viewer-title {
  font-size: 24px;
}
```

> Here is an online example: https://fengyuanchen.github.io/viewerjs/examples/custom-title.html
