### ISSUE TITLE
Update is closing the modal 

### ISSUE THREAD

**Issue by iec989** [fengyuanchen/viewerjs#280]
**Describe the bug**
When you run viewer.update(), it will close the modal. 

If you try to do something like viewer.update().show(true) as a workaround, it doesn't work :( 

Any other alternative? I'm allowing users to delete images by using this system, and I don't want them to exit the modal view. If there is no other choice, I would like to at least be able to manage the "show(true)" right after.

**Comment by fengyuanchen** [comment]
Any demo?
