### ISSUE TITLE
updateSize()?

### ISSUE THREAD

**Issue by adventmedia** [fengyuanchen/viewerjs#281]
ViewerJS handles window resizing just fine. However, if for some reason I decide to change the  size of the containing div for a viewer instance, it does not detect this change. Currently I'm just destroying and recreating the instance, but a more elegant solution would be an updateSize() method that would work like window resizing, to resize the viewer to fit the div.
The use case for this is where the user can switch between 1, 2 or 4 images (for comparison), which means resizing to fit the enclosing area.

**Comment by fengyuanchen** [comment]
You can try to call the internal `resize` method.
