### ISSUE TITLE
Can you still display the exit button in the upper right corner when using inline mode?

### ISSUE THREAD

**Issue by asdfhalkehflkajdhf** [fengyuanchen/viewerjs#286]
When using inline mode, I didn't find out if I quit browsing.
The button parameter is a full-screen button in the upper right corner when using inline mode. No action is performed when clicking on the background.
Although there are exit operations. When using examples, it was unsuccessful.
Can you still display the exit button in the upper right corner when using inline mode?

**Comment by fengyuanchen** [comment]
Will not support that. Sorry.
