### ISSUE TITLE
Inline mode, on opening page issue with zoomTo.

### ISSUE THREAD

**Issue by gorgevweb** [fengyuanchen/viewerjs#287]
I need to run viewer.js inline mode, when I click on a nav-tab. There is no modals. 
When I click on tab, viewer is working, but the first shown image in neither zooming, nor rotating, when I click on another image from navbar, it work fine. Any idea?

**Comment by gorgevweb** [comment]
Here is the code 
var viewer = new Viewer(document.getElementById('imageViewerContainer3'), {
            inline: true,
            url:'data-original',
            minWidth: 900,
            minHeight: 600,
            navbar: true,
            title: true,
            toolbar:{
                zoomIn: 4,
                zoomOut: 4,
                oneToOne: 4,
                reset: 4,
                prev: 4,
                play: {
                    show: false,
                },
                next: 4,
                rotateLeft: 4,
                rotateRight: 4,
                flipHorizontal: false,
                flipVertical: false,
            },
            viewed() {
                this.viewer.zoomTo(1)
            }
        });

**Comment by fengyuanchen** [comment]
I have not idea on this. Can you just provide an online demo?
