### ISSUE TITLE
How do i filter the specified image without using viewer.js?

### ISSUE THREAD

**Issue by jdzhang1221** [fengyuanchen/viewerjs#289]
For example,

i want to filter the an images that contains an onclick event.

'''
<div  id="optPic">

 < data-original="/Images/del.png" src="/Images/del.png" alt="picture" title="picture" class="img-rounded"  />

 < src="/Images/del.png" onclick="Deleteimg()" />

</div>

$(function () {
        $('#optPic').viewer({
            url: 'data-original',
            filter: true,
        });
    })
'''

**Comment by fengyuanchen** [comment]
The `filter` option should be a function!

**Comment by fengyuanchen** [comment]
```js
new Viewer(imageList, {
  filter(image) {
    return !!image.onclick;
  },
});
```
