### ISSUE TITLE
Trouble rotating images programmatically (this.image undefined)

### ISSUE THREAD

**Issue by scottt732** [fengyuanchen/viewerjs#29]
https://jsfiddle.net/scottt732/axftkuup/3/

I'm load images with jquery to test whether they are wider than they are tall.  As they load, I'm setting an attribute on the original `img` tags.  I wire up viewer after all images are loaded and in the viewed.viewer event handler, I'm trying to apply the rotation automatically.

My goal is to render them 90 degrees clockwise rotated so they are always taller than they are wide (convert landscape to portrait).   When I call rotate, I either get `this.image is undefined`.  When I try 'rotateTo', it never performs the rotation because `_this.isViewed` is false in the rotateTo handler (method.js).

**Comment by fengyuanchen** [comment]
The `viewed.viewer` is a event of the jQuery version: https://github.com/fengyuanchen/viewer
