### ISSUE TITLE
there is no close button in the  upper right corner

### ISSUE THREAD

**Issue by jdzhang1221** [fengyuanchen/viewerjs#290]
Popup window is displayed in the specified div,but there is no close button.Only zoom in button.

**Comment by fengyuanchen** [comment]
I don't understand. Any demo?

**Comment by jdzhang1221** [comment]
![image](https://user-images.githubusercontent.com/29417118/58743296-4b357700-8461-11e9-8922-238802f055b5.png)

**Comment by jdzhang1221** [comment]
![image](https://user-images.githubusercontent.com/29417118/58743348-27befc00-8462-11e9-9b75-a20dd05f5404.png)

**Comment by jdzhang1221** [comment]
When the inline property is set, it will be displayed in the specified popup box, but there is no close button, only the zoom in button, and the next time the popup page is opened, a thumbnail will be automatically loaded.
What I want is the close button, and the next time I open the popup layer, don't open the thumbnail automatically. What should I do?

For example code: 
<div class="operation_row  operation_row_detail" id="BushipeiCredential" hidden>
    <div style="padding: 10px;" id="infoPic">加载中..</div>
    <div id="shangpinPic">加载中..</div>
</div>

 $("#infoPic").html(strinfo);
                    $("#shangpinPic").html(strtable);
                    $('#BushipeiCredential').viewer({
                        url: 'data-original',
                        inline: true,
                    });

**Comment by fengyuanchen** [comment]
Not support that. Why not just use the modal mode?

PS: You can customize your close button and call the `hide` method after clicked it.

**Comment by jdzhang1221** [comment]
How can I customize the button?

button
Type: Boolean
Default: true
Show the button on the top-right of the viewer.

No more explanation in the documentation，I only found these

**Comment by fengyuanchen** [comment]
I mean a button element outside the viewer (100% customization).

**Comment by jdzhang1221** [comment]
thank you,this is a good idea,even though i didn't do it.
