### ISSUE TITLE
Code review of assignment to innerHTML

### ISSUE THREAD

**Issue by gdh1995** [fengyuanchen/viewerjs#291]
**Describe the bug**
The Firefox Add-ons has a security check for every extension package, and reports warnings for code like `.innerHTML = render(...)`, with an only exception of `.innerHTML = "a-string-literal"`.

So, because my webextension Vimium C includes this project, I always got such warnings when I published new versions.

**Expected behavior**

There're 2 solutions to avoid such security warnings:
1. replace all assignment code to innerHTML with `document.createElement(...)` and DOM manipulations.
2. or, use DOMParser: `var div = new DOMParser().parseFromString(html, "text/html").body.firstElementChild`.

Considering that `DOMParser` does not exist on IE 9, and `parseFromString` does not exist before Firefox 12, or Chrome 31, I recommend the first method, although it will increase the JavaScript file size for about tens to hundreds of bytes.
 
**Warned Places**

There're 2 sources of Firefox Add-ons' warnings:
https://github.com/fengyuanchen/viewerjs/blob/d1964646d1f1ef0aa653734b2946f21b27c2e9c3/src/js/render.js#L88-L95 and
https://github.com/fengyuanchen/viewerjs/blob/d1964646d1f1ef0aa653734b2946f21b27c2e9c3/src/js/methods.js#L265-L268

I also suggest that, in the second source code `.innerHTML = escapeHTMLEntities(...)` should be replaced with `.textContent = ...`.

**Comment by gdh1995** [comment]
I pushed a demo:
https://github.com/gdh1995/viewerjs/blob/cb70df7c52fc5fb92a3e27620078ba2753c21eaf/src/js/render.js#L82-L90

And I think the DOM manipulations are safe enough, so remove the recently-added `escapeHTMLEntities`. The function has a negative impact that, if there's an `<img>` with an `alt` of `"user <user@qq.com>"`, then the `'<'` and `'>'` may be escaped, and the result text users see will be `"user &lt;user@qq.com&gt;"` - a little ugly.

**Comment by fengyuanchen** [comment]
Good suggestion. Thanks!

**Comment by fengyuanchen** [comment]
I have improved the `escapeHTMLEntities` function for showing the `<` and `>` characters.

**Comment by gdh1995** [comment]
The commit 7118c0c does nothing helpful to the Firefox Add-ons' warnings. It just blames all usages of ".innerHTML = ..."

**Comment by fengyuanchen** [comment]
Maybe I will remove all `innerHTML` usages in the next major version, but not now as they are too many places use it, for example, the big viewer template.

**Comment by gdh1995** [comment]
I find a new regression of escaping text twice: see https://github.com/fengyuanchen/viewerjs/commit/ddd0c3d515dd1d8ea3e0323f486fab7d2cd5631f#r34475671
