### ISSUE TITLE
Not displaying button icons in Microsoft Edge

### ISSUE THREAD

**Issue by Damian-Fiorillo** [fengyuanchen/viewerjs#292]
**Describe the bug**
Not displaying button icons. The circle buttons are, but the icons aren't.

**Screenshots**
![image](https://user-images.githubusercontent.com/38361112/59033441-18172d00-883f-11e9-9e5f-f663ea58753a.png)

**Desktop And mobile -> Microsoft edge

**Comment by fengyuanchen** [comment]
I have not idea on this.

**Comment by gdh1995** [comment]
I think a potential cause is Edge treats the "background-size" property mistakenly:
* in the current source, there's "background-size: 280px" in the styles of `.viewer-<button>::before`
* if we change it to `background-size: 280px 280px`, then all icons disappears
  * the image will be scaled for 14x only by Y-axis, so they are outside the button circle

Of course, it will also cause such a problem if the `data:` image gets broken.

A third probable cause is there're another styles applied on `li` or `[role=button]`, and it sets `background-size: contain`, but on my Edge 18.18362 (64 bits) this rule has no effects.

To test this, @Damian-Fiorillo could you open the problematic page and:
* press `<f12>` to trigger the Developer Tools and switch to "Element" panel
* click the first button on the second line which has a rectangle and an arrow
* click a button in Viewer.js' menu, and:
* give snapshots of all its styles, just like the image below but every group of styles is useful:

![image](https://user-images.githubusercontent.com/5547703/60693393-b238c680-9f0c-11e9-8d56-8c64140315ef.png)

**Comment by Damian-Fiorillo** [comment]
Hi guys,

It was solved by adding position absolute to:

.viewer-close::before, .viewer-flip-horizontal::before, .viewer-flip-vertical::before, .viewer-fullscreen-exit::before, .viewer-fullscreen::before, .viewer-next::before, .viewer-one-to-one::before, .viewer-play::before, .viewer-prev::before, .viewer-reset::before, .viewer-rotate-left::before, .viewer-rotate-right::before, .viewer-zoom-in::before, .viewer-zoom-out::before {
        position: absolute;
    }

**Comment by gdh1995** [comment]
Um, then it seems that somewhere is a `display: inline` (or other inline-like values) applied on these buttons' `:before` styles.

So I think it's blamed to the page you're visiting.

**Comment by fengyuanchen** [comment]
@gdh1995 Thanks for your help!
