### ISSUE TITLE
如何 结合element ui upload 组件使用

### ISSUE THREAD

**Issue by wysdddh** [fengyuanchen/viewerjs#293]
如何和elementui 的这个上传图片放大组件结合使用
https://element.eleme.cn/#/zh-CN/component/upload

element ui的这个点击放大按钮能取到img的src，如何在取到src的情况下直接触发v-viewer的放大事件，求教了！！！

**Comment by wysdddh** [comment]
已解决，参考：https://codesandbox.io/embed/jvv2y26ov9

**Comment by fengyuanchen** [comment]
可参考：https://fengyuanchen.github.io/viewerjs/examples/dynamic-viewer.html
即在JS中参加一个图片元素传给 Viewer。
