### ISSUE TITLE
How to set the viewer width to 50% of the screen?

### ISSUE THREAD

**Issue by bdevika** [fengyuanchen/viewerjs#296]
I tried By setting container width to 50%
.viewer-container{
width:50%;
}
but image margin-left, margin-right dynamically setted. im not able to position the image in center

![Screenshot](https://user-images.githubusercontent.com/40199188/59762508-090b9280-92b5-11e9-88bf-6247f61aa221.png)

**Comment by fengyuanchen** [comment]
You can try this:

```css
.viewer-container {
  right: 50%;
}
```

**Comment by fengyuanchen** [comment]
Or use the inline mode.

**Comment by bdevika** [comment]
Hi,
 @fengyuanchen ,
 Thank you.  I figured out the issue. In my case parent container position-fixed Due to that, it was causing an issue while screening orientation change.
