### ISSUE TITLE
IE problem with url(image) {return image}

### ISSUE THREAD

**Issue by gumacuk15** [fengyuanchen/viewerjs#297]
Hello!

new Viewer(image, {
  url(image) {
    return image.src.replace('?size=160', '');
  },
});

IE error:
SCRIPT1003: Expected ':'

I want to change image src, how can i do it? or can u fix bug in IE?

**Comment by fengyuanchen** [comment]
You should transform the code by Babel as it is written in ES6 syntax.

**Comment by fengyuanchen** [comment]
Or transform it manually:

```js
new Viewer(image, {
  url: function (image) {
    return image.src.replace('?size=160', '');
  }
});
```
