### ISSUE TITLE
Valid url is html escaped

### ISSUE THREAD

**Issue by davidd4** [fengyuanchen/viewerjs#298]
Original image has '&' character in src.
The image src is then html escaped by viewerjs to '&amp;'.
The transformed url is not correct and the image is not shown.

'&' character is valid in urls. It should not be replaced.

E.g:
www.example.com/image?entityid=56435643&contentid=354375
will be transformed to
www.example.com/image?entityid=56435643&amp;contentid=354375

The new url contains the **amp;contentid** query param instead of **contentid**,  and that is an error.

**Comment by fengyuanchen** [comment]
Already fixed this in 6f5dc0c8d3a1cb58f2467ad23d192a1e68765e9c

**Comment by davidd4** [comment]
I tried it in release 1.3.5.
It is still not working.
Please try it with an **img src** containing a _&_ character. It will be still replaced with _&amp;amp;_

**Comment by lisen198859** [comment]
release 1.3.5.
It is still not working. 
and aliyun cdn url & replaced with &amp;

**Comment by louieaa** [comment]
In 1.3.5
I have the same problem.  replace with &amp
Causes the picture to be unable to read the newspaper 403
I don't know why you replaced & with &amp, & in URL is legal
![Snipaste_2019-07-02_19-11-31](https://user-images.githubusercontent.com/42113246/60557900-c9937a80-9d79-11e9-8aad-97964416288a.png)
![Snipaste_2019-07-02_19-05-03](https://user-images.githubusercontent.com/42113246/60557904-cc8e6b00-9d79-11e9-8104-aac528f7a047.png)

**Comment by louieaa** [comment]
@fengyuanchen Please open this question.
