### ISSUE TITLE
viewer on tablet

### ISSUE THREAD

**Issue by b2bstudio** [fengyuanchen/viewerjs#3]
Hi there 

Love the popup by the way, does everything I would like it to do and more.

one question when viewing on a tablet when you click play and go full screen how do you escape from fullscreen and go to normal view?

**Comment by fengyuanchen** [comment]
Good point. It should exit fullscreen when stop playing.

**Comment by b2bstudio** [comment]
also I need to disable certain features, eg rotatable , moveable, thumbnails...  do I need to do this in main.js

**Comment by fengyuanchen** [comment]
Yes.

```js
$().viewer({
    url: 'src',
    movable: false,
    rotatable: false,
    scalable: false
  });
```

**Comment by b2bstudio** [comment]
I have added it in main.js but it doesn't  seam to change, do I need all the js in main.js?

<script>
$(function () {

  'use strict';

  var console = window.console || { log: function () {} };
  var $images = $('.docs-pictures');
  var $toggles = $('.docs-toggles');
  var $buttons = $('.docs-buttons');
  var options = {
        // inline: true,
        url: 'data-original',
        build: function (e) {
          console.log(e.type);
        },
        built: function (e) {
          console.log(e.type);
        },
        show: function (e) {
          console.log(e.type);
        },
        shown: function (e) {
          console.log(e.type);
        },
        hide: function (e) {
          console.log(e.type);
        },
        hidden: function (e) {
          console.log(e.type);
        },
        view: function (e) {
          console.log(e.type);
        },
        viewed: function (e) {
          console.log(e.type);
        }
      };
	  
	$().viewer({
    url: 'src',
    movable: false,
    rotatable: false,
    scalable: false
  });



  

  $images.on({
    'build.viewer': function (e) {
      console.log(e.type);
    },
    'built.viewer':  function (e) {
      console.log(e.type);
    },
    'show.viewer':  function (e) {
      console.log(e.type);
    },
    'shown.viewer':  function (e) {
      console.log(e.type);
    },
    'hide.viewer':  function (e) {
      console.log(e.type);
    },
    'hidden.viewer': function (e) {
      console.log(e.type);
    },
    'view.viewer':  function (e) {
      console.log(e.type);
    },
    'viewed.viewer': function (e) {
      console.log(e.type);
    }
  }).viewer(options);

  toggleButtons(options.inline ? 'inline' : 'modal');

  $toggles.on('change', 'input', function () {
    var $input = $(this);
    var name = $input.attr('name');

    options[name] = name === 'inline' ? $input.data('value') : $input.prop('checked');
    $images.viewer('destroy').viewer(options);
    toggleButtons(options.inline ? 'inline' : 'modal');
  });

  $buttons.on('click', 'button', function () {
    var data = $(this).data();
    var args = data.arguments || [];

    if (data.method) {
      if (data.target) {
        $images.viewer(data.method, $(data.target).val());
      } else {
        $images.viewer(data.method, args[0], args[1]);
      }

      switch (data.method) {
        case 'scaleX':
        case 'scaleY':
          args[0] = -args[0];
          break;

        case 'destroy':
          toggleButtons('none');
          break;
      }
    }
  });

});
</script>

**Comment by fengyuanchen** [comment]
As this issue is under the Viewer.js, I should provide a related example:

```html
<div class="pictures">
  <img src="/path/to/picture-1.jpg">
  <img src="/path/to/picture-2.jpg">
  <img src="/path/to/picture-3.jpg">
</div>
```

```js
var pictures = docuement.querySelector('.pictures');
var viewer = new Viewer(pictures , {
  url: 'src',
  movable: false,
  rotatable: false,
  scalable: false
});
```
