### ISSUE TITLE
Refresh/Reload

### ISSUE THREAD

**Issue by Wyzix33** [fengyuanchen/viewerjs#302]
**Is your feature request related to a problem? Please describe.**
I have a dynamic html element container of images where users can add/remove images and a reload would be awesome.

**Describe the solution you'd like**
After the container of images for viewing changes, has more or fewer children, trigger reload, or i can do it inside my code. 

**Describe alternatives you've considered**
For now i destroy and recreeate the Viewer.

**Comment by fengyuanchen** [comment]
You might try the `update` method of the Viewer.js.
