### ISSUE TITLE
Dynamicly change photos, when selecting one of left side elements

### ISSUE THREAD

**Issue by gorgevweb** [fengyuanchen/viewerjs#303]
**Describe the bug**

**To Reproduce**
1. On this page I need an inline viewer
2. On left side. First element is active at first
3. I need a help with this: When I click on second left sided div, on right side must appear viewer with those images, and so go on with third, fourth
4. Could you provide a simple example for doing it?
![Annotation 2019-07-15 015245](https://user-images.githubusercontent.com/47106257/61189837-0a599080-a6a4-11e9-8756-7d06d45654e7.png)

**Comment by fengyuanchen** [comment]
Just destroy the old viewer instance and restart a new one on the new target element.

**Comment by gorgevweb** [comment]
Could you provide a little examle please, how to destroy one Viewer by clicking on another?

**Comment by fengyuanchen** [comment]
Sorry. I don't have time.
