### ISSUE TITLE
能否支持初始放大尺寸调整

### ISSUE THREAD

**Issue by xzdry1** [fengyuanchen/viewerjs#305]
在工作中遇到需求：图片初始放大尺寸(比如为100x100)有些小。我翻了文档，在viewed(){}里面使用scale(1.6,1.3)来放大长和宽，但是这样会有一个问题：图片的动画会先放大到图片的默认尺寸(100x100)，然后顿一下才会拉伸(160x130)。并且点击reset依然会回到图片的默认尺寸(100x100)
我希望能够点击放大直接过渡到拉伸后的状态(160x130)。
因此希望能设置图片的初始放大尺寸，且reset回到的也是这个事先设置的尺寸。
这一切都是在react中使用。

**Comment by fengyuanchen** [comment]
你可以自己修改初始数据 `viewer.initialImageData`。

> 可以参考 [`reset` 方法的代码](https://github.com/fengyuanchen/viewerjs/blob/master/src/js/methods.js#L865-L872)。
