### ISSUE TITLE
请问怎么过滤掉不想显示的图片

### ISSUE THREAD

**Issue by wzlzking** [fengyuanchen/viewerjs#306]
假如我有五张图片，但只想其中的三张可以用viewer.js进行查看，我应该怎么过滤掉那两张啊，我看了filter函数，但还是不太懂，我是这样写的
window.addEventListener('DOMContentLoaded', function () {
            var galley = document.getElementById('galley');
          
             viewer = new Viewer(galley, {
                url: 'data-original',
                toolbar: {
                    prev: function () {
                        viewer.prev(true);
                    },

                    next: function () {
                        viewer.next(true);
                    },
                },
                title : false,
                 filter:function (image) {
                     return $("img").hasClass('img_not_show');
                 }
            });
        });
这样还是全部的图片都可以用viewer.js查看

**Comment by fengyuanchen** [comment]
请多思考，少问问题！

居然你问了，我也指出你的问题：

```js
viewer = new Viewer(galley, {
  // ...
  filter: function (image) {
    // 1. 传入的参数就是当前相关的图片，不要忽略而使用其他的！！！
    // 2. 既然是筛选（filter，而不是 ignore），返回 true 才会显示图片！！！
    return $("img").hasClass('img_not_show');
  },
});
```

正确版本：

```js
viewer = new Viewer(galley, {
  // ...
  filter: function (image) {
    return !$(image).hasClass('img_not_show');
  },
});
```
