### ISSUE TITLE
onClose event

### ISSUE THREAD

**Issue by Wyzix33** [fengyuanchen/viewerjs#307]
**Is your feature request related to a problem? Please describe.**
I'm trying to destroy the viewer instance and execute some code when user closes the viewer  by X, ESC or click outside the image

**Describe the solution you'd like**
A onClose event that will fire when the viewer is closed so i can execute some code onClose

**Describe alternatives you've considered**
I was thinking of adding a click/keydown listener to the page on ```show``` event and figure it out when the user closes the viewer.

Thanks and great job with viewerjs 👍

**Comment by fengyuanchen** [comment]
There is already a [`hidden`](https://github.com/fengyuanchen/viewerjs#hidden-1) event for that.

**Comment by Wyzix33** [comment]
Ok, thank you, i din't know why i didn't see it...
