### ISSUE TITLE
建议title.innerHTML可以支持标签,而不通过escapeHTMLEntities函数强制过滤转换

### ISSUE THREAD

**Issue by junhsc** [fengyuanchen/viewerjs#309]
作者,您好
1.我们的实现是现在照片上加入除了作者,作品以外的额外信息,从而让用户获取到除了图片以外的更多信息, 
2.在阅读代码时发现此处代码,发现html标签被函数强制转换了
title.innerHTML = escapeHTMLEntities(isFunction(render) ? render.call(_this, image, imageData) : "".concat(alt, " (").concat(imageData.naturalWidth, " \xD7 ").concat(imageData.naturalHeight, ")"));
3.通过文档中提供的title自定义函数也是通过被强制转换了,我们只是暂时通过修改与调整此处代码进行优化

希望这个建议作者你能采纳,让title可以支持标签,让用户个性化展示图片信息。
另外一个建议,底部的按钮的位置,比如prev/next按钮可以自定义到图片的左/边两边

**Comment by fengyuanchen** [comment]
可以通过 `viewed` 事件进行完全自定义，包括使用 HTML：

```js
new Viewer(images, {
  viewed: function (event) {
    this.viewer.title.innerHTML = `<i>${event.detail.image.alt}</i>`;
  },
});
```
