### ISSUE TITLE
Viewer can`t view fullscreen in using bootstrap modal

### ISSUE THREAD

**Issue by TAMMENY** [fengyuanchen/viewerjs#31]
Hi, thank you for providing such a useful plugin, but i have some trouble in using ViewerJS, if the image is inside the bootstrap modal, viewer can`t view fullscreen, how can i solve this problem?

![a](https://cloud.githubusercontent.com/assets/5690568/15354707/771fac78-1d21-11e6-9076-cac56fe2ab4a.png)

Thank U

**Comment by fengyuanchen** [comment]
Not support to use it in modal yet.

**Comment by infeng** [comment]
you should try render Viewer component in document.body

**Comment by MrGorki** [comment]
Changing `$this.after($viewer);` with ` $('body').append($viewer);` should solve it.

**Comment by zhangyangGit** [comment]
If the bootstrap modal dialog can work. You can change the viewerjs class into  "var CLASS_OPEN = 'modal-open'". This works  in my situation.

**Comment by TAMMENY** [comment]
Thank you all.😊

**Comment by fengyuanchen** [comment]
Supports now: https://github.com/fengyuanchen/viewerjs/blob/master/examples/viewer-in-modal.html
