### ISSUE TITLE
On demo, using view with an index superior to the number of images gives an empty viewer

### ISSUE THREAD

**Issue by locness3** [fengyuanchen/viewerjs#312]
**Describe the bug**
Evertything's in the title.

**To Reproduce**
1. Go to https://fengyuanchen.github.io/viewerjs/
2. Enter a value superior to 9 next to viex at the right
3. Click View

**Expected behavior**
it should maybe go to the latest/first image or error

**Screenshots**
![Screenshot_2019-08-02 Viewer js](https://user-images.githubusercontent.com/37651007/62369379-b79b2800-b52f-11e9-9b0f-ad6c4f9f0b08.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version 69.0b9

**Comment by locness3** [comment]
Oh thanks!

**Comment by locness3** [comment]
Doesn't look fixed on the website

**Comment by fengyuanchen** [comment]
This change will be released in the next patch version.

**Comment by locness3** [comment]
Ok. 👍
