### ISSUE TITLE
add an option to show image in fullscreen

### ISSUE THREAD

**Issue by zhangzq** [fengyuanchen/viewerjs#314]
**Is your feature request related to a problem? Please describe.**
目前，显示图片时，图片会比屏幕小一点（目测约90%的屏幕大小）。我希望图片能真正做到全屏。

**Describe the solution you'd like**
增加一个选项，使得图片显示时为100%。

**Comment by fengyuanchen** [comment]
可以尝试在图片显示后调用 `zoomTo` 方法改变图片大小。

**Comment by zoum79** [comment]
hello ! I think it is possible to show titles (alt) when showing images in fullscreen. But how ???
A second wish : I would like to show the tooltip at the opening of images, not only when zooming.
I thank you very much if you can give me solutions.
zoum79

**Comment by fengyuanchen** [comment]
See #526.
