### ISSUE TITLE
请问如何调整图片的默认显示比例？

### ISSUE THREAD

**Issue by siy513** [fengyuanchen/viewerjs#319]
1、如何将图片的默认显示比例修改，比如打开后默认显示100%,而不是为了自适应的比例。
2、第一页图片调整显示比例后，怎么能让翻页后显示比例不还原。

**Comment by siy513** [comment]
我想图片显示比例默认100%
现在的思路是在viewed事件中加zoomTo方法
viewed:function(e){
      this.viewer.zoomTo(1);
 }
但是有明显的延迟切换比例效果。
想请问一下有没有相关的属性进行设置或其他的思路来实现此需求

**Comment by fengyuanchen** [comment]
暂不支持。可 Fork 一份直接修改源码，然后打包使用。

**Comment by siy513** [comment]
谢谢

**Comment by shuiRong** [comment]
@siy513 我也有一样的需求，就是点击预览时，就默认100%，而不是先图片宽度（我这边图片宽度80%），再100%。
我Fork了一份代码然后手动修改了下，解决了。

![image](https://user-images.githubusercontent.com/16076993/80301826-f1584100-87d8-11ea-860e-f32fde484f8e.png)
