### ISSUE TITLE
No event.detail value for viewed event

### ISSUE THREAD

**Issue by ecool2011** [fengyuanchen/viewerjs#32]
I use following codes to bind "viewed" event, 

HTML:
```
<div id="gallary">
	<ul id="images" style="display:none;">
	<li><img src="welcome.jpg" alt="欢迎使用"></li>
	</ul>
</div>
```

JS:
```
var g_viewerOptions = { 
	inline: true, 
	viewed: onViewed
};

$("#images").on({ 'viewed.viewer' : onViewed }).viewer(g_viewerOptions);

function onViewed(e) {
	alert(e.detail.index);
}
```

the onViewed() can be called after viewed one image, but the e.detail is undefined??  
Can you help me? 

 From a Chinese user ^_^

**Comment by fengyuanchen** [comment]
The right event is `viewed`, not need the `.viewer` suffix.

**Comment by ecool2011** [comment]
However,  following codes won't trigger 'viewed' event... I have no idea.. >_<

`$("#images").on({ 'viewed' : onViewed }).viewer(g_viewerOptions);`

**Comment by ecool2011** [comment]
I made mistake, viewer and viewerjs is two different library.... I use viewer, not viewerjs...
