### ISSUE TITLE
Pinch zoom not working in  ipad  pro 13.1 all the  browsers

### ISSUE THREAD

**Issue by bdevika** [fengyuanchen/viewerjs#321]
When I try to pinch zoom in ipad pro 13.1 browsers nothing happens.
Moving the picture is also not working 
I've tested this in both my own project and in your demo page: https://fengyuanchen.github.io/viewerjs.
It seems to be working fine if I use the other device.

Tested operating systems: ipad pro 13.1
Tested browsers: Safari, chrome, Firefox

**Comment by fengyuanchen** [comment]
As of Safari for iOS 13+, it starts to support `PointerEvent` which cause some problem.
