### ISSUE TITLE
右上角button选项，inline模式为何不能是关闭，可否自行配置

### ISSUE THREAD

**Issue by sushuier** [fengyuanchen/viewerjs#322]
inline模式，右上角是全屏按钮；
modal模式，右上角默认是关闭按钮；
为何不能自行配置呢，我现在想inline模式，右上角是关闭，并且执行其他回调，就需要自己用jquery获取元素再写了，请求开放这个回调接口。

**Comment by fengyuanchen** [comment]
1. Inline 模式没有关闭功能。
2. 全屏只是额外为 Inline 模式提供的功能。
3. 目前不会支持自行配置。
