### ISSUE TITLE
在预览开启的情况下，ajax返回的图片无法添加到预览图中，通过update()也没有效果

### ISSUE THREAD

**Issue by zhixiaotong** [fengyuanchen/viewerjs#324]
Version：1.3.6
Desc：在预览开启的情况下，ajax返回的图片无法添加到预览图中，通过update()也没有效果

初始化方式：
`const viewer  = new Viewer(DOM, {`
`          toolbar: true,`
`          url: 'data-original',`
`         show() {`
`         viewer.update()`
`   }`
`})`
       在ajax请求图片的回调中，同时也主动调用了`viewer.update()`，预览图还是无法更新，需要重新关闭打开才能看到新增的图片。

请问如何解决这个问题呢？

**Comment by fengyuanchen** [comment]
由于个人时间有限，请只提 Bug 或者 Feature。

**Comment by zhixiaotong** [comment]
@fengyuanchen 这就是我在实际使用的情况中遇到的bug

**Comment by fengyuanchen** [comment]
你试试在 `shown` 或着 `viewed` 回调中使用 `update` 方法。如果不行，那应该是不支持这种预览状态的更新用法了。

**Comment by zhixiaotong** [comment]
@fengyuanchen 感谢回复，我尝试了下。在shown中使用update方法，会导致点击上一个或下一个切换图片功能失效，一直显示第一个图片。在viewed中使用update方法是会重载刚请求返回的图片，但是之前的图片每一次都会加载出来（update没有把之前的图片清掉，缓存？导致了之前图片的重复加载显示），点击上一个或下一个图片，底部的预览图列表会越来越多。

目前我是在show()和viewed()中均使用了update方法，viewed()是可以显示新加载的图片列表的，但会有上述的bug，我不知道如何手动清掉之前的图片。作者大大知悉一下。再次感谢！

**Comment by HeyJohnnny** [comment]
> @fengyuanchen 感谢回复，我尝试了下。在shown中使用update方法，会导致点击上一个或下一个切换图片功能失效，一直显示第一个图片。在viewed中使用update方法是会重载刚请求返回的图片，但是之前的图片每一次都会加载出来（update没有把之前的图片清掉，缓存？导致了之前图片的重复加载显示），点击上一个或下一个图片，底部的预览图列表会越来越多。
> 
> 目前我是在show()和viewed()中均使用了update方法，viewed()是可以显示新加载的图片列表的，但会有上述的bug，我不知道如何手动清掉之前的图片。作者大大知悉一下。再次感谢！

我也存在类似问题   就是打开一张新图片之后会显示上一次预览的图片 然后再刷新成当前新图片。 不知道您现在有解决的办法吗

**Comment by zhixiaotong** [comment]
@HeyJohnnny 没有，那个问题搁置了，我按照作者的思路试了下，会出现之前描述的问题，现有版本不支持这种预览效果吧，我最近没时间提pr。

**Comment by HeyJohnnny** [comment]
嗯嗯 我最后选择用每次都销毁/创建实例的方法了  这样不会再刷新了  就是不知道是否会对性能有较大的影响

**Comment by HeyJohnnny** [comment]
> @HeyJohnnny 没有，那个问题搁置了，我按照作者的思路试了下，会出现之前描述的问题，现有版本不支持这种预览效果吧，我最近没时间提pr。

嗯嗯 我最后选择用每次都销毁/创建实例的方法了 这样不会再刷新了 就是不知道是否会对性能有较大的影响
