### ISSUE TITLE
能否支持图片加载错误处理

### ISSUE THREAD

**Issue by hthmh** [fengyuanchen/viewerjs#325]
图片加载失败时页面空白，列表中只要有一个图片加载失败就会全部空白而查看不了

是否可以支持图片加载失败时显示一张默认可配置的提示图片

**Comment by MaJiaXuan** [comment]
同问

**Comment by fengyuanchen** [comment]
“列表中只要有一个图片加载失败就会全部空白”？似乎无法复现。如果一张图片失败，其他图片成功下载，那么应该是可以正常查看的。
