### ISSUE TITLE
在富文本中使用图片预览，需要点击第二次才能触发预览

### ISSUE THREAD

**Issue by freedom408443631** [fengyuanchen/viewerjs#328]

**Comment by fengyuanchen** [comment]
富文本是指富文本编辑器？

**Comment by freedom408443631** [comment]
是的

**Comment by freedom408443631** [comment]
![image](https://user-images.githubusercontent.com/42776207/66695256-fe588b80-ecf1-11e9-8fa7-4c54f469da38.png)
![image](https://user-images.githubusercontent.com/42776207/66695263-0f090180-ecf2-11e9-8082-5c9749432db8.png)

**Comment by fengyuanchen** [comment]
也许富文本编辑器本身就控制了点击事件吧。

**Comment by freedom408443631** [comment]
之前我单独拿img出来测试，发现也是这个情况

**Comment by freedom408443631** [comment]
进入该页面后，需要点击第二次才能触发预览。之后的点击就正常了

**Comment by AKclown** [comment]
你好，请问解决了吗？  我也是动态修改图片地址，也是需要第二次点击才生效

**Comment by freedom408443631** [comment]
应该要修改源码，顺序为：获取到url再加载。后来我自己写了，没有用这个组件。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"AKclown"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月8日(星期五) 上午10:03
收件人:&nbsp;"fengyuanchen/viewerjs"<viewerjs@noreply.github.com&gt;;
抄送:&nbsp;"408443631"<408443631@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fengyuanchen/viewerjs] 在富文本中使用图片预览，需要点击第二次才能触发预览 (#328)




你好，请问解决了吗？  我也是动态修改图片地址，也是需要第二次点击才生效
