### ISSUE TITLE
Add an option to enable / disable mouse scroll wheel

### ISSUE THREAD

**Issue by ChoOo7** [fengyuanchen/viewerjs#329]
Add an option to enable / disable mouse scroll wheel

**Comment by fengyuanchen** [comment]
Just control it with the `zoom` event:

```js
new Viewer(image, {
  zoom: functioon (event) {
    if (event.detail.originalEvent.type === 'wheel') {
      event.preventDefault();
    }
  },
});
```

**Comment by ChoOo7** [comment]
I have tested it.
Indead, the event is "stopped" for the viewer, but instead for page scrolling
Try this
Put your player on a page
Add a 
body {
height: 12000px;
}
.viewer-open {
    overflow: auto!important;
}
Disable the scroll using your method.
If your scroll, the page won't scroll
If you comment
addListener(viewer, EVENT_WHEEL, this.onWheel = this.wheel.bind(this), {
      passive: false,
      capture: true
    });

The page will scroll

My real use case if, the viewer is integrated using an iframe in another page. I don't want the scroll in or out the iframe have the same result : scrolling inside the parent page

Thanks

**Comment by fengyuanchen** [comment]
Why not prevent the page scrolling in your document?

```js
document.body.addEventListener('wheel', ...)
```

**Comment by fengyuanchen** [comment]
You can now set the `zoomOnWheel` option to `false` for your case.
