### ISSUE TITLE
About orientation and rotate image, And IOS

### ISSUE THREAD

**Issue by dogrocker** [fengyuanchen/viewerjs#334]
**Describe the bug**
Hello!

My image wrong orientation when open in the popup
(Mac, Windows, Android)
![Imgur](https://i.imgur.com/ov3wE9k.png)
So how to rotate to the correct position ?

And this is same picture open in iOS.
In iOS the image rotate to correct orientation, But it seem stretch.
![Imgur](https://i.imgur.com/zolbCXK.jpg)

**Expected behavior**
The image should rotate to correct orientation.
In IOS device image not stretch.

**Desktop (please complete the following information):**
 - OS: Windows, Mac, Android
 - Browser Chrome, safari
 - Version latest

**Smartphone (please complete the following information):**
 - Device: iPhone6
 - OS: iOS
 - Browser Chrome, safari
 - Version latest

**Comment by mirari** [comment]
I see that you have submitted the same issue to the author of `viewer.js`, waiting for your good news.

**Comment by fengyuanchen** [comment]
#134
