### ISSUE TITLE
能不能只传图片列表,不传元素容器之类的

### ISSUE THREAD

**Issue by lee8519** [fengyuanchen/viewerjs#338]
因为页面上只展示了首张图片,我想通过点击首张图片之后,把其他图片也一并传给插件滑动查看

**Comment by fengyuanchen** [comment]
当点击“封面”图片后，你可以用JS创建一个不放入页面的容器元素，然后再在容器元素上初始化 Viewer。

**Comment by fengyuanchen** [comment]
示例：https://fengyuanchen.github.io/viewerjs/examples/dynamic-viewer.html
