### ISSUE TITLE
移动端优化

### ISSUE THREAD

**Issue by pengxAlone** [fengyuanchen/viewerjs#340]
图片预览的时候，如果是触摸屏，拖动图片经常会图片翻页，能不能给了属性控制触摸滑动翻页，自己可以加按钮翻页。 然后触摸屏翻页，经常会报错， ‘Uncaught TypeError: Cannot read property 'endX' of undefined’

**Comment by fengyuanchen** [comment]
请问报错是在 `viewer.js` 代码文件的哪一行？
