### ISSUE TITLE
container: window.top.window.document.body  problem

### ISSUE THREAD

**Issue by xuejun84** [fengyuanchen/viewerjs#341]
图片在iframe中，设置了 container: window.top.window.document.body 
图片显示、放大、缩小、上一张，下一张都没有问题，
但是有一个问题，不能拖动了

图片在iframe中，设置了 container: window.top.window.document.body 
图片显示、放大、缩小、上一张，下一张都没有问题，
但是有一个问题，不能拖动了

In iframe, set the container: window.top.window.document.body

There are no problems with the picture display, zooming in, zooming out, the previous picture and the next one,

But there's a problem. can't drag pictures

**Comment by crazyguagua** [comment]
1129行 

 改成 var document = this.options.container?this.options.container:this.element.ownerDocument;
可以移动了。
