### ISSUE TITLE
底部图片数组可以是缩略图地址吗,显示的大图片为正常图地址吗?

### ISSUE THREAD

**Issue by 857128237** [fengyuanchen/viewerjs#342]
**Is your feature request related to a problem? Please describe.**
底部图片数组可以是缩略图地址吗,显示的大图片为正常图地址吗?

**Describe the solution you'd like**
加一个缩略图地址?或者还是其他

**Describe alternatives you've considered**

**Additional context**

**Comment by fengyuanchen** [comment]
配置 `url` 参数即可实现，请参考官网示例：https://fengyuanchen.github.io/viewerjs/
