### ISSUE TITLE
Is there a way to gracefully handle images that couldn't be loaded?

### ISSUE THREAD

**Issue by flyingL123** [fengyuanchen/viewerjs#344]
I have found that if I try to initialize the viewer with a bunch of thumbnail image urls, and one of those images doesn't exist (the url returns a 404 or 403 error), it causes the entire viewer not to load. Is there a way to handle this gracefully? It would be nice to just skip that thumbnail or show a placeholder rather than preventing the entire gallery function.

Any advice on that?

**Comment by fengyuanchen** [comment]
Similar to #325

**Comment by fengyuanchen** [comment]
Exactly, I found I can reappear the problem, any available demo?

**Comment by fengyuanchen** [comment]
@flyingL123 A valid online demo is welcome if you still have a problem with this.

**Comment by chemseddine201** [comment]
i wish this helps you!
//
const ImgViewer = new Viewer(document.querySelector('#custom-images-viewer'), {
        timeout: 5000,// add timeout 
        title: (image) => ''
    });
$(document).on('click', 'span#prevImg', async function(e) {
        var data = $(this).data();
        if (data.src === true) {
            await load_image({
                user_id: USER_ID,
                request_uid: data.request_uid,
                card_id: data.card_id
            }).then(response => {
                if (response.status == 200 && response.data.length) {
                    $('img#custom-image-preview').attr('src', response.data);
                    ImgViewer.update();
                    ImgViewer.show();
                    setTimeout(() => (!(ImgViewer.imageData.width > 0)) ? ImgViewer.hide() : () => {}, 6000);
                }
            });
        } else if (data.src.length > 5) {
            $('img#custom-image-preview').attr('src', data);
            ImgViewer.update();
            ImgViewer.show();
//to handle the 404 image if not found just use the setTimeout and check the width or image after loaded if didn't have width just hide the viewer
            setTimeout(() => (!(ImgViewer.imageData.width > 0)) ? ImgViewer.hide() : () => {}, 6000);
        }
    });
