### ISSUE TITLE
On Fullscreen view and window resize, image takes default fullscreen width on exit fullscreen

### ISSUE THREAD

**Issue by kdeeksha** [fengyuanchen/viewerjs#345]
If image is opened in fullscreen and resize window and exit fullscreen, the image takes default fullscreen size (Width of parent div is 50%, on fullscreen i make parent 100%, on exit back to 50%)

**Comment by fengyuanchen** [comment]
When you exit fullscreen, you may need to trigger a `resize` event on the `window`:

```js
// Exit fullscreen...
window.dispatchEvent(new Event('resize', {
  bubbles: true,
  cancelable: true,
));
```

Or try to call the **internal** method `resize` (**not recommended** as this method may be drop or rename in future versions):

```js
cropper.resize();
```
