### ISSUE TITLE
Highlight Zoomout when ZoomIn

### ISSUE THREAD

**Issue by kdeeksha** [fengyuanchen/viewerjs#347]
I need to highlight zoom out button when user zoom-in. Is there anyway i get zoom-in event, so that i can highlight zoom-out if zoom ratio is more than natural image size?

**Comment by fengyuanchen** [comment]
1. You can customize the toolbar.
2. You can use the `zoom` event, and call `event.preventDefault()` to prevent zoom in or zoom out.
