### ISSUE TITLE
在小屏（iphone8尺寸以下）上无法手动缩放和拖动，在大屏上可以，不知道什么原因

### ISSUE THREAD

**Issue by coderben1** [fengyuanchen/viewerjs#348]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fengyuanchen** [comment]
试试把`slideOnTouch`参数设为`false`.

> https://github.com/fengyuanchen/viewerjs#slideOnTouch
