### ISSUE TITLE
能否加多张图片上下页prev,next事件？

### ISSUE THREAD

**Issue by MiyaHeGH** [fengyuanchen/viewerjs#349]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fengyuanchen** [comment]
你可以试试 `view` 和 `viewed` 事件。

**Comment by wangyong991** [comment]
用view 和viewed可以监听到index，我们这个有个需求，就是loop: false情况下，点击上一页到图片首张给予提示，第一次切换到首张，可以通过view或者viewed进行提示，但是在首张图片位置，再次点击上一页，这个view和viewed事件就监听不到了。有没有什么办法可以监听到

**Comment by fengyuanchen** [comment]
@wangyong991 你可以定制自己的 Prev 和 Next 按钮，按需调用相应方法，请查看 `toolbar` 参数。
