### ISSUE TITLE
Viewer Not working on IE9 on Windows 7

### ISSUE THREAD

**Issue by mfarewell** [fengyuanchen/viewerjs#35]
Using an official Windows 7 VM with IE 9 version 9.0.8112.16421
The plugin loads, with the background image and the tool bar, however the zoomable image fails to load. The VM I used is accessible from here https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/. Screen shot attached.
![viewerjsie9issue](https://cloud.githubusercontent.com/assets/17099979/16734881/fa52ad3e-477e-11e6-9580-0fe5b7ca0c15.png)

**Comment by pangtengfei** [comment]
![1](https://cloud.githubusercontent.com/assets/1397432/17043750/74b4b6ce-4fec-11e6-9961-a19211556a83.jpg)
add this

**Comment by fengyuanchen** [comment]
Fixed on #33, will be released soon.
