### ISSUE TITLE
图片放大时，由于图片较大，需要先加载模糊图，当清晰图加载完成后，再加载清晰图，改如何处理？谢谢

### ISSUE THREAD

**Issue by MiyaHeGH** [fengyuanchen/viewerjs#350]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fengyuanchen** [comment]
只接受 “BUG报告” 和 “新功能建议”，谢谢！
