### ISSUE TITLE
请问在查看大图时按delete快捷键删除当前图片，在不关闭查看大图窗口情况下，怎么更新视图？

### ISSUE THREAD

**Issue by xinxiangzhene** [fengyuanchen/viewerjs#351]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fengyuanchen** [comment]
只接受 “BUG报告” 和 “新功能建议”，谢谢！
