### ISSUE TITLE
如果 Viewer 绑定的元素里面的 img 是动态生成的,就无法预览了

### ISSUE THREAD

**Issue by vistwang** [fengyuanchen/viewerjs#356]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fengyuanchen** [comment]
1. 在图片生成之后再初始化Viewer。
2. 在图片生成之后调用 `update` 方法更新 Viewer。
