### ISSUE TITLE
Picture gets minimalized sometimes when Dev konzole open

### ISSUE THREAD

**Issue by El-vira** [fengyuanchen/viewerjs#357]
Sometimes when I open the developer console (or make already opened bigger) or move the browser window from bigger screen to smaller one, the picture gets minimalized (I am using inline version with only one picture). If more Vievers are rendered on screen that time, only one picture remains in right size and all others get minimalized to min-height min-width defined in your img tag.

![minimalized](https://user-images.githubusercontent.com/53125904/71564138-31fab480-2a9c-11ea-9dc8-bbf27dc0e4b6.JPG)
![normal](https://user-images.githubusercontent.com/53125904/71564139-31fab480-2a9c-11ea-88d1-3bca7bd408fd.JPG)

**Comment by fengyuanchen** [comment]
The viewer is responsive. Just check your own code! For example, destroy the viewer, check if your original image or layout is responsive, if not, improve it before using the viewer.

A quick solution:

```css
.image-container > img {
  width: 100%;
}
```
