### ISSUE TITLE
能否接收一个 json 数组作为参数，用于展现图片列表

### ISSUE THREAD

**Issue by xclw2000** [fengyuanchen/viewerjs#359]
现在这种模式不太适合我的需求。
我的预览范围可能包括几百甚至上千个图片。以现在有模式，我这些图片需要先加载到dom里，然后才能预览。那么我的页面加载将会非常慢，甚至会出现卡死的情况。然而这些图片用户可能不会每一张都预览到，我要做的是在界面上显示一些缩略图或者一些表示索引的数字按钮，用户点哪个就从哪个开始预览，当Viewer需要去渲染某个图片的时候，才真的去服务器请求这个图片。
我在想是不是可以把一个数组传过去，然后根据元素对象的属性，按需加载图片，而不是一下子加载所有图片。
比如：
const images=[{src : 'a.png' }, {src: 'b.png'}, {src:'c.png'}........];
const viewer=new Viewer(images);

**Comment by fengyuanchen** [comment]
1. 图片不一定要插入DOM，虚拟DOM也可以。可参考：https://fengyuanchen.github.io/viewerjs/examples/dynamic-viewer.html。
2. 通过 `url` 参数可以配置点击查看的图片，比如原图。可参考：https://fengyuanchen.github.io/viewerjs/。

**Comment by Haiwar** [comment]
@fengyuanchen 多张图片该如何显示呢

**Comment by fengyuanchen** [comment]
@Haiwar 多张图片就用一个 DIV 元素把它们包起来，然后在这个 DIV 元素上初始化 Viewer。

**Comment by Haiwar** [comment]
> @Haiwar 多张图片就用一个 DIV 元素把它们包起来，然后在这个 DIV 元素上初始化 Viewer。

好的吧
