### ISSUE TITLE
Loading image viewer without having to click on the actual image itself

### ISSUE THREAD

**Issue by Physium** [fengyuanchen/viewerjs#36]
Hey i'm just wondering if its possible to load the image viewer via click a button while the images stays hidden in the background or something?

**Comment by Physium** [comment]
to add on. the view() method does not seems to be working as well. not even the demo works.

**Comment by fengyuanchen** [comment]
Call the `show` method after you initialized a viewer.

**Comment by jasminder** [comment]
Hey , Thanks for building the plugin .Its awesome. i have same question . 

```
<div class="thumbnail ">
<img src="thumb.png" class="portrait" alt="Image" />
</div>
<div>
  <ul class="images">
    <li><img src="picture.jpg" alt="Picture"></li>
    <li><img src="picture-2.jpg" alt="Picture 2"></li>
    <li><img src="picture-3.jpg" alt="Picture 3"></li>
  </ul>
</div>
```

I want to show the viewer with class .images on clicking class .portrait. I have initialized the viewer. 
```
$('.images').viewer();
$('.portrait').click(function(){
$('.images').viewer('show');
	});
```

Please tell if i am doing it wrong .

**Comment by fengyuanchen** [comment]
The code is fine, but you put this comment in a wrong place...

> The right place: https://github.com/fengyuanchen/viewer
