### ISSUE TITLE
图片预览器title更新问题

### ISSUE THREAD

**Issue by zxywd** [fengyuanchen/viewerjs#361]
作者：
         您好，当前项目中采用了1.5.0版本，我上传5张图片title分别为： 营业执照(1/5)，营业执照(2/5)，营业执照(3/5)，营业执照(4/5)，营业执照(5/5)，当前浏览的是第1张图片营业执照(1/5)，然后弹窗口中删除第2～5中任意一张，弹窗提交并关闭，发现第一张图片标题还是显示“营业执照(1/5)”。如果弹窗中删除第1张图片，弹窗提交并关闭，图片浏览中显示的是原先的第二张图片，标题显示为“营业执照(1/4)”，这时候显示是正确的。下面是截图：
![1-1](https://user-images.githubusercontent.com/5567567/72145960-7d835b80-33d6-11ea-808b-2ec7c4773494.png)
![1-2](https://user-images.githubusercontent.com/5567567/72145962-7d835b80-33d6-11ea-867d-9886c875e60c.png)
![1-3](https://user-images.githubusercontent.com/5567567/72145963-7e1bf200-33d6-11ea-8c63-5c7db0a75755.png)
![1-4](https://user-images.githubusercontent.com/5567567/72145966-7e1bf200-33d6-11ea-91e9-e705cc341532.png)
![2-1](https://user-images.githubusercontent.com/5567567/72145968-7eb48880-33d6-11ea-8492-e3dd268127f9.png)
![2-2](https://user-images.githubusercontent.com/5567567/72145971-7f4d1f00-33d6-11ea-8252-15d7cf3cc972.png)
![2-3](https://user-images.githubusercontent.com/5567567/72145973-7f4d1f00-33d6-11ea-87f1-3759be52b109.png)
![2-4](https://user-images.githubusercontent.com/5567567/72145974-7fe5b580-33d6-11ea-990c-f32b4739ab28.png)

代码中是下面这样使用的：
watch: {
      // 图片列表监控事件
      imgs() {
        if (this.imgs.length > 0) {
          console.log('this.imgs: %o', this.imgs)
          setTimeout(() => {
            // 存在预览，刷新
            if (this.viewer) {
              this.viewer.update()
              this.viewer.view(this.curIndex)
            } else {
              // 构造预览对象
              this.viewer = window.viewer = new Viewer(document.getElementById('images'), {
                inline: true,
                navbar: false,
                button: false,
                title: true,
                tooltip: false,
                scalable: false,
                transition: false,
                toolbar: {
                  zoomIn: 10,
                  zoomOut: 1,
                  oneToOne: 1,
                  reset: 1,
                  prev: 1,
                  play: 0,
                  next: 1,
                  rotateLeft: 1,
                  rotateRight: 1,
                  flipHorizontal: 0,
                  flipVertical: 0,
                },
                view: (evt) => {
                  this.setImageIndex && this.setImageIndex(evt.detail.index)
                },
              })
            }
          }, 500)
        } else {
          this.viewer = null
          document.querySelector('.viewer-container').style.display = 'none'
        }
      }
    },
在父组件中改变imgs的值：
saveSucceed(params) {
      this.dialogUploading = false

      this.curIndex = 0
      let imgs = []

      let atr = params.listAttachmentTypeResp
      atr && atr.forEach((a, index) => {
        a.listApplyAttachmentResp.forEach((b, index1) => {
          let list = {
            fileByte: b.fileByte,
            index: index,
            index1: index1,
            title: `${a.attachmentTypeName} (${b.attachmentSeq} / ${a.totalPage})`
          }
          imgs.push(list)
          imgs.sort((m, n) => {
            if (m.index === n.index) {//如果index相同，按照index1排序
              return m.index1 - n.index1
            } else {
              return m.index - n.index
            }
          })
        })
      })
      this.imgs = imgs
      this.imgsShower = JSON.stringify(this.imgs)
    },
下面是日志截图：
![3-2](https://user-images.githubusercontent.com/5567567/72146781-21213b80-33d8-11ea-9742-691ee1368533.png)

**Comment by fengyuanchen** [comment]
不是有一个 `update` 方法吗？删了图片就要更新一下，或者注销重新初始化。

**Comment by zxywd** [comment]
> 不是有一个 `update` 方法吗？删了图片就要更新一下，或者注销重新初始化。
解决了，在view: function view()里面，注释掉以下代码：
    // if (this.hiding || this.played || index < 0 || index >= this.length || this.viewed && index === this.index) {
    //   return this;
    // }

    // if (!this.isShown) {
    //   this.index = index;
    //   return this.show();
    // }

    // if (this.viewing) {
    //   this.viewing.abort();
    // }
使其强制性地去浏览图片就可以了。
