### ISSUE TITLE
怎么点击背景关闭

### ISSUE THREAD

**Issue by 104160112** [fengyuanchen/viewerjs#362]

**Comment by fengyuanchen** [comment]
不是默认就已经支持点击模态背景关闭弹窗了吗？

**Comment by 104160112** [comment]
没有啊，只有点击右上角的关闭才能关闭，我要点击除了图片之外的背景关闭




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Fengyuan Chen"<notifications@github.com&gt;; 
发送时间: 2020年1月18日(星期六) 下午2:40
收件人: "fengyuanchen/viewerjs"<viewerjs@noreply.github.com&gt;; 
抄送: "倘若"<1506772167@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [fengyuanchen/viewerjs] 怎么点击背景关闭 (#362)




不是默认就已经支持点击模态背景关闭弹窗了吗？

**Comment by fengyuanchen** [comment]
你用的什么版本？请直接查看官方示例：https://fengyuanchen.github.io/viewerjs/

**Comment by 104160112** [comment]
js版的，但没有这种效果，这是默认就可以点击背景关闭吗？是版本问题吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Fengyuan Chen"<notifications@github.com&gt;; 
发送时间: 2020年1月18日(星期六) 下午2:57
收件人: "fengyuanchen/viewerjs"<viewerjs@noreply.github.com&gt;; 
抄送: "倘若"<1506772167@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [fengyuanchen/viewerjs] 怎么点击背景关闭 (#362)




你用的什么版本？请直接查看官方示例：https://fengyuanchen.github.io/viewerjs/
