### ISSUE TITLE
title参数不接受dom

### ISSUE THREAD

**Issue by 18353230045** [fengyuanchen/viewerjs#363]
**Is your feature request related to a problem? Please describe.**
想要自定义写入某个样式的dom作为title，但是只展示当前dom的字符，没有渲染成dom

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fengyuanchen** [comment]
基于安全考虑（XSS），`title` 参数不支持HTML。可以使用变通方案：

```js
var viewer = new Viewer(images, {
  viewed: function () {
    viewer.title.innerHTML = '<b>Custom title</b>';
  },
});
```
