### ISSUE TITLE
Could please present image with its orientation? 

### ISSUE THREAD

**Issue by carlshe** [fengyuanchen/viewerjs#366]
**Is your feature request related to a problem? Please describe.**
Some images carry orientation info with them. But these images can't be shown correctly in its defined orientation.

**Describe the solution you'd like**
Show the image with correct orientation if it has such info.

**Describe alternatives you've considered**
No.

**Additional context**
No.

Thanks!

**Comment by fengyuanchen** [comment]
Duplicate to #134.
