### ISSUE TITLE
调用自动播放后再触发退出，遮罩层虽然变透明，但没有隐藏。挡在最顶层。

### ISSUE THREAD

**Issue by Fazime** [fengyuanchen/viewerjs#367]
**Describe the bug**
调用自动播放后再触发退出，遮罩层虽然变透明，但没有隐藏。挡在最顶层。

为了实现自动播放。直接调用 $().viewer('show',true) 。之后点击关闭按钮或者遮罩退出，外层的 viewer-container 显示透明，但不隐藏，挡在最顶层，全页面无法点击。

**To Reproduce**
1. $().viewer('show',true) 
2. 点击关闭按钮或者遮罩退出
3. 外层的 viewer-container 显示透明，但不隐藏，挡在最顶层
4. 全页面无法点击

**Expected behavior**
遮罩层能隐藏

**Screenshots**
![image](https://user-images.githubusercontent.com/15311147/75598914-d029eb80-5ada-11ea-8c15-61da7dace57d.png)
![image](https://user-images.githubusercontent.com/15311147/75598916-d6b86300-5ada-11ea-8e17-56c6e4890ce8.png)

**Desktop (please complete the following information):**
 - OS: win10, iOS 13
 - Browser chrome,safari

**Smartphone (please complete the following information):**
 - Device: all

**Comment by Fazime** [comment]
//播放设置
				let setting = storage('setting');
				options.interval = setting && setting.auto_speed ? setting.auto_speed*1000 : 3000;
				//VIEWER
				pics.html(tpl).viewer(options).find('img').lazyload();
				if (setting) {
					if (setting.auto_show) {
						pics.viewer('show',true);
						if (setting.auto_play) pics.viewer('play');
					} else if (setting.auto_play) {
						pics.viewer('show',true).viewer('play');
					}
				}

**Comment by fengyuanchen** [comment]
You should call the `hide` method with its first parameter set to `true` too:

```js
viewer.show(true);
viewer.hide(true);
```
