### ISSUE TITLE
all images loaded again

### ISSUE THREAD

**Issue by zhaixing** [fengyuanchen/viewerjs#368]
When you view a list of images,browser will load all images in the list.
I want to show one image ,when i click it,all images loaded again.
sometimes it did not.
I use cdn both images and viewer.js .

**Comment by zhaixing** [comment]
当我打开列表页面的时候，图片加载了一次。当我点击其中一张图片时，调用了viwerjs，但是所有的图片都是重新从服务器获取的。这是什么原因呢

**Comment by zhaixing** [comment]
我觉得是因为我的Chrome开启了disable cache。
关闭了好像就好了。

**Comment by fengyuanchen** [comment]
Viewer 弹窗底部有缩略图导航栏，会加载所有图片，如果你禁用了缓存，自然是要重新加载一边了。
