### ISSUE TITLE
目前自动播放不支持翻页，也没找到其他方法修改当前页，只能按既定逻辑进行下一页切换，是否可以添加类似百度图片预览，播放模式下可以上下翻页的功能呢

### ISSUE THREAD

**Issue by 1134617484** [fengyuanchen/viewerjs#374]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fengyuanchen** [comment]
Duplicates with #90.
