### ISSUE TITLE
toolbar ignoring size option

### ISSUE THREAD

**Issue by adventmedia** [fengyuanchen/viewerjs#375]
**Describe the bug**
According to the documentation, it is possible to specify the size of the buttons on the toolbar, e.g.:
`prev: {show: 1, size: 'large'},
play: false,
next: {show: 1, size: 'large'},
`
etc. (other buttons except the two rotate buttons are set to false)

However the button always displays at the same size.

**Screenshots**
with 'large' option:
![Kovo 2020-03-24 10-43-22](https://user-images.githubusercontent.com/1529172/77438516-4d840b80-6dbc-11ea-8430-ace2c7fbf008.jpg)
with 'small' option:
![Kovo 2020-03-24 10-44-57](https://user-images.githubusercontent.com/1529172/77438692-83c18b00-6dbc-11ea-9c50-c8650ca6957c.jpg)

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser: Chrome
 - Version: 80.0.x

**Comment by fengyuanchen** [comment]
Do you use the latest version?
