### ISSUE TITLE
页面设置了过滤器 filter: grayscale(1) 弹出层失效

### ISSUE THREAD

**Issue by youhunwl** [fengyuanchen/viewerjs#377]
**Describe the bug**
页面设置了过滤器 filter: grayscale(1) 弹出层失效，应该是定位导致的，可以参考：https://stackoverflow.com/questions/52937708/css-filter-on-parent-breaks-child-positioning

**Additional context**
复现网站具体可以看 [游魂博客](https://www.iyouhun.com) 随便找个图文文章

**Comment by fengyuanchen** [comment]
To fixed this, you can use:

```html
<html  style="filter: grayscale(1);">
  <body>
  ...
  </body>
</html>
```

instead of:

```html
<html>
  <body  style="filter: grayscale(1);">
  ...
  </body>
</html>
```

**Comment by youhunwl** [comment]
> To fixed this, you can use:
> 
> ```
> <html style="filter: grayscale(1);">
>   <body>
>   ...
>   </body>
> </html>
> ```
> 
> instead of:
> 
> ```
> <html>
>   <body style="filter: grayscale(1);">
>   ...
>   </body>
> </html>
> ```

嗯 给html设置确实好了

**Comment by fengyuanchen** [comment]
事实上这个问题不适合在 Viewer 内部处理（也不好处理）。建议在你的项目中处理，毕竟所有用到 `position: fixed` 的组件都是受影响的。
