### ISSUE TITLE
viewerjs + modal bootstrap

### ISSUE THREAD

**Issue by irvanindriyan** [fengyuanchen/viewerjs#378]
viewerjs open in modal bootstrap, modal jumping to top page...

solution:
create new element modal without element modal-content to save tag img target.
then run function to set attribute src img target and declare new viewerjs.
on modal shown, run viewer.open()

result:
modal not jumping.

and viewer.hidden function viewer.destroy()

**Comment by fengyuanchen** [comment]
You can follow this example: https://fengyuanchen.github.io/viewerjs/examples/viewer-in-modal.html
