### ISSUE TITLE
Display Image Viewer in Mobile - Responsive

### ISSUE THREAD

**Issue by haifahrul** [fengyuanchen/viewerjs#379]
**Describe the bug**
When viewerjs on mobile, the style css of padding-right in body is not responsive.
![image](https://user-images.githubusercontent.com/6553704/79353726-a97a2400-7f65-11ea-9afb-5b8fd6880dff.png)

After investigated, i found these :
![image](https://user-images.githubusercontent.com/6553704/79353618-7b94df80-7f65-11ea-8b3c-788d269f9c7c.png)

**Expected behavior**
I want to this plugin responsive on all media. E.g. Desktop and Mobile.
So, I change the css style `padding-right` into 100% not using *px*.
![image](https://user-images.githubusercontent.com/6553704/79354152-3cb35980-7f66-11ea-9bb6-a2c6c35cf951.png)

This is the result :
![image](https://user-images.githubusercontent.com/6553704/79354227-5359b080-7f66-11ea-93d1-08ede773e702.png)

# The question is, whether it is the right way? @fengyuanchen 

Btw, FYI
I made these [ckedtior4-gallery](https://github.com/haifahrul/ckeditor4-gallery) with viewerjs plugins. 

Thanks

**Comment by fengyuanchen** [comment]
Maybe you can change the `padding-right` property of the `body` element's style once the window size changed by JS.
