### ISSUE TITLE
Click any region to exit image view mode ,not only by right top icon.

### ISSUE THREAD

**Issue by J-J-J** [fengyuanchen/viewerjs#38]
As the title,Let users  exit image view mode by click on any region,not only by right top icon.

This can improve user’s effectiveness especially when this plugin be used for management system.

OR,How can I rewrite the template in [template.js](https://github.com/fengyuanchen/viewerjs/blob/master/src/js/template.js) file,For I can just add "`data-action="mix"`" within `<div class="viewer-canvas"></div>`

**Comment by fengyuanchen** [comment]
Why not just use the `hide` method.

**Comment by J-J-J** [comment]
thanks

**Comment by KevinPan** [comment]
where should I call the hide method to hide the viewer if the mouse clicked outside of the image?
