### ISSUE TITLE
[Help]可以动态添加多张图片吗？

### ISSUE THREAD

**Issue by Exrick** [fengyuanchen/viewerjs#380]
官方给了动态添加单张图片的示例，想知道如何动态添加多张图片list

```javascript
var image = new Image();
image.src = 'pic.jpg';

var viewer = new Viewer(image, {
    hidden: function () {
        viewer.destroy();
    }
});

viewer.show();
```

**Comment by xcyxiner** [comment]
第一个对象可以放 图片上传的div..代码里面有获取div下的图片对象的。

// View a list of images
const gallery = new Viewer(document.getElementById('images'));
// Then, show one image by click it, or call `gallery.show()`.

**Comment by Exrick** [comment]
只有这种方式吗....能不从DOM获取吗 @xcyxiner

**Comment by xcyxiner** [comment]
就算弄个div，然后不显示div，动态往div里加img。。把div对象放到Viewer就可以。。。

**Comment by xcyxiner** [comment]
不显示到界面上的div,用viewer就得调 view来显示哪个图片了。。

```
const gallery = new Viewer(document.getElementById('images'));
gallery.view(图片的index)
```

**Comment by Exrick** [comment]
嗯 谢谢 @ @xcyxiner

**Comment by libsgh** [comment]
同问..动态的竟然只能预览一张图片
