### ISSUE TITLE
Unexpected behavior with Next when an image is added before the currently viewed image

### ISSUE THREAD

**Issue by batekulve** [fengyuanchen/viewerjs#381]
**Describe the bug**
If I add an image in the HTML before the currently viewed image, update the viewer, then click the Next button it shows the same image again instead of looping back to the first image. Image loop is on.

**To Reproduce**
1. Initialize a non-modal viewer with one image and loop = true
2. Write a function that triggers on view that adds a new image at the beginning of the list
3. Call viewer.update()
4. Click the button that moves to the next image.
5. Note that the image does not change.

**Expected behavior**
Since loop is true, I expect it to loop to the first image in the collection

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome
 - Version 81.0.4044.113

**Additional context**
I am writing a live-loading image viewer. When the user moves to an image, it loads the next and/or previous image in the sequence and adds it to the image collection.

This can be worked around by calling `viewer.index++` when an image before the current image is added.

**Comment by fengyuanchen** [comment]
If you know where the new image added, update the `viewer.index` property is the right way.
