### ISSUE TITLE
Display HTML tag in title

### ISSUE THREAD

**Issue by pp253** [fengyuanchen/viewerjs#386]
**Is your feature request related to a problem? Please describe.**
I want to add a link in the title by directly setting `<img alt="<a href=''>hi!</a>">`.
However, due to the update v1.3.7 (mentioned in Unsafe HTML hijacking #269), it seems that every html entities will be escaped.

**Describe the solution you'd like**
Is it possible to add an option to omit the `escapeHTMLEntities()` right here?

https://github.com/fengyuanchen/viewerjs/blob/04d8d66b64b3c99d3a24126f10a6b831df29622d/src/js/methods.js#L264

Thanks!
BTW, viewer.js is the best!

**Comment by fengyuanchen** [comment]
You can just edit the title element directly after viewed:

```js
new Viewer(images, {
  viewed() {
    this.viewer.title.innerHTML = '<a href="#">Hi!</a>';
  },
});
```
