### ISSUE TITLE
Add rotate to events

### ISSUE THREAD

**Issue by holmespc** [fengyuanchen/viewerjs#388]
**Is your feature request related to a problem? Please describe.**
I want to record the transformations that occur so I can reapply them when opening the image again, but there is no way to gather the rotations via an event. With an event, I can make an AJAX call and record the rotational values.

**Describe the solution you'd like**
Add an event that gets fired when rotates are performed. Expose the event and the type of rotation that was done, and also, the resulting degrees of the image since it was loaded.

**Describe alternatives you've considered**
I've tried to pull transformations out of the CSS that is applied, but it's not always reliable.

**Additional context**
Thank you for an amazing viewer. I don't have anything else to add to this request.

**Comment by fengyuanchen** [comment]
You can try to customize the whole toolbar and bind the action in your custom handler.

> Example: https://fengyuanchen.github.io/viewerjs/examples/custom-toolbar.html

**Comment by holmespc** [comment]
Thank you, that helped.
