### ISSUE TITLE
Viewer in modal

### ISSUE THREAD

**Issue by Alekzv9** [fengyuanchen/viewerjs#39]
Hi, first of all, you build an amazing component.

I have your component in a modal, inside the modal I use the inline mode (needed that way). When I click to fullscreen the modal became the full screen and not the complete window,  how can I do to the componen use full window and not the modal context?

**Comment by rafaelgrilli92** [comment]
Wow, we are in 2017 and this issue is still opened!

I'm facing the same problem. I need the pictures inside a modal, but when I click on them, the full screen of the viewerjs becomes the modal, so it crops the bottom of the image
