### ISSUE TITLE
在inline mode下，如何让图片默认zoom为视图的宽度，zoom为1图片太大了

### ISSUE THREAD

**Issue by CuteDeng** [fengyuanchen/viewerjs#390]
```
images.addEventListener('viewed', function () {
            viewer.zoomTo(1); // Zoom to 1:1 when each image load completely
        }, false);
```
这样写，会把图片zoom到原图大小，有没有办法可以让图片zoom为视图的大小

**Comment by fengyuanchen** [comment]
你可以根据你的容器宽高和图片宽高计算一个合适的缩放比率。

**Comment by CuteDeng** [comment]
> 你可以根据你的容器宽高和图片宽高计算一个合适的缩放比率。

@fengyuanchen 不行，我弄得是一个相册，每张图片都要计算吗？即使能够计算，怎么设置zoom呢？zoom不是统一设置的吗？

**Comment by fengyuanchen** [comment]
缩放比例在 Viewer 内部也是根据每张图片的实际宽高动态计算的，使用image.naturalWidth 和  image.naturalHeight。
