### ISSUE TITLE
body标签被加上 style无法清理

### ISSUE THREAD

**Issue by Ucer** [fengyuanchen/viewerjs#394]
预览过viewerjs之后， 自动在我的 body层加了个 style，destroy也不能清除，导致页面样式出问题

> `<body style="overflow: hidden; padding-right: 0px;">`

版本信息    ` "viewerjs": "^1.5.0"`

```
    var viewer = new window.Viewer(this.$refs.galleyPhoto, {
              url: 'data-original',
              hidden: function() {
                viewer.destroy()
              }
            })
            viewer.show()
```

![2020-06-03 06-42-01屏幕截图](https://user-images.githubusercontent.com/28194791/83577191-2c7f2a00-a566-11ea-86b1-71c55a96de59.png)

我现在的解决方案是要手动清理一下body样式

```
    var viewer = new window.Viewer(this.$refs.galleyPhoto, {
              url: 'data-original',
              hidden: function() {
                viewer.destroy()
                 document.querySelector('body').removeAttribute('style')
              }
            })
            viewer.show()
```

**Comment by fengyuanchen** [comment]
你说的是 `overflow: hidden` 吧？这个属性不是 Viewer.js 加的，至于 `padding-right: 0px` 应该没有不良影响的吧。

**Comment by fengyuanchen** [comment]
已进行优化，当 `padding-right` 等于 `0px` 时，会将其移除。
