### ISSUE TITLE
zoomRatio lower than 0.1: unable to zoom out after 100% zoom reached

### ISSUE THREAD

**Issue by hiratariq** [fengyuanchen/viewerjs#396]
I am currently working on a project that needs a very small zoom step. So I set zoomRatio to 0.01, and once fully zoomed in I couldn't zoom out again. So I tried commenting these few lines and it worked brilliantly for me. I wanted to know the reasoning behind this condition, I fear that later I may find an issue that may have been the reason why this condition was put in there in the first place.

https://github.com/fengyuanchen/viewerjs/blob/7e7c4ecb8894e94021469c392de6b36f8489c91c/src/js/methods.js#L467-L469

**Comment by fengyuanchen** [comment]
After testing, a `zoomRatio` value great than `0.053` works fine. I will improve this soon.
