### ISSUE TITLE
Simply can not get this to work according to your instructions

### ISSUE THREAD

**Issue by vincentwansink** [fengyuanchen/viewerjs#397]
I've tried including the .js and .css files as instructed.

<link  href="/path/to/viewer.css" rel="stylesheet">
<script src="/path/to/viewer.js"></script>

I've tried including the cdn files instead.

I've tried adding type=module to the script tags and I've spent hours trying to get this to work, but I keep getting errors like:

- module is not defined
or
- 'https://cdnjs.cloudflare.com/ajax/libs/viewerjs/1.6.1/viewer.min.js' does not provide an export named 'default'

Not sure why this is so difficult but some simple instructions that actually work would be greatly appreciated.  I've attached a copy of a simple test file that I've been working with.  Perhaps you can tell me what I'm doing wrong.

[test.txt](https://github.com/fengyuanchen/viewerjs/files/4880356/test.txt)

**Comment by fengyuanchen** [comment]
If you add a `type="module"` attribute on the `script` element, you **SHOULD** import the ES Module version of Viewer.js:

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/viewerjs/1.6.1/viewer.esm.js" type="module"></script>
```
