### ISSUE TITLE
设置 className 的问题。

### ISSUE THREAD

**Issue by a599219798** [fengyuanchen/viewerjs#398]
我设置Options的className参数，并且className设置有 width 和 height, 但是发现只有蒙版层的宽度改变了，图片的位置及底部缩略图的位置不正确，不在蒙版层的中间位置了。有什么办法让他们居中在蒙版层吗 ?

**Comment by fengyuanchen** [comment]
请提供可以在线查看的示例，否则不明白你讲什么。

PS：很大程度上是你设置的className有副作用，不兼容。
