### ISSUE TITLE
how to check if the viewer's modal is open or closed?

### ISSUE THREAD

**Issue by BrendonIwata** [fengyuanchen/viewerjs#399]
Reading the documentation, i cant find anything reference, saying how to check if the viewer modal are open or closed, how i can do this?

**Comment by fengyuanchen** [comment]
Just listen to the `show`, `shown`, `hide`, and `hidden` events.

**Comment by fengyuanchen** [comment]
Or use the builtin `isShown` property:

```js
const viewer = new Viewer(...);

console.log(viewer.isShown);
```

**Comment by BrendonIwata** [comment]
thanks a lot
