### ISSUE TITLE
Changing the sample pictures to make the demo page more welcoming

### ISSUE THREAD

**Issue by searls** [fengyuanchen/viewerjs#4]
Hi! I was just introduced to viewer.js and it seems like a really cool tool. The page I was introduced to was the [demo page](http://fengyuanchen.github.io/viewerjs/) and I have to admit, I was a little concerned that a wall of 9 glamour-shot-style pictures of Emma Watson might make some people feel less welcome/included to the project than a mix of different types of pictures or pictures with a more neutral theme (landscapes, etc.)

It's just a suggestion if you can empathize with this perspective and want to make everyone feel welcome to engaging with the project.

**Comment by samdoiron** [comment]
:+1:

**Comment by fengyuanchen** [comment]
@searls You are right. Thanks. I will replace them with some photographs taked by myself to avoid license problem.

**Comment by fengyuanchen** [comment]
I have replaced all the example images with my own photos. Thanks all of you.

**Comment by searls** [comment]
Awesome, thanks @fengyuanchen!
