### ISSUE TITLE
你好，请问在其它组件中如何关闭图片  或者说触发关闭事件

### ISSUE THREAD

**Issue by lizesheng0313** [fengyuanchen/viewerjs#400]
你好，请问在其它组件中 关闭图片  或者说触发关闭事件

**Comment by fengyuanchen** [comment]
其它组件是什么？

PS：没头没脑的问问题得不到帮助的。

**Comment by fengyuanchen** [comment]
- [How To Ask Questions The Smart Way](http://www.catb.org/~esr/faqs/smart-questions.html).
- [提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/)。
