### ISSUE TITLE
Feature request: Add 'drag' or 'dragged' event

### ISSUE THREAD

**Issue by dearzoe** [fengyuanchen/viewerjs#402]
It would be useful to have an event fire when a 'drag' occurs.

I would like to use viewer in a component, but if the image is dragged the i dont know it be moved;

I am happy to try this and give you a PR if you are open to the idea.

Thank you for a very useful image viewer!

**Comment by fengyuanchen** [comment]
Why not just bind some drag events on the model element of the viewer?

```js
const viewer = new Viewer(image, {
  ready() {
    viewer.canvas.addEventListener('drag', (event) => {
      console.log(event);
    });
    viewer.canvas.addEventListener('dragend', , (event) => {
      console.log(event);
    });
  },
});
```
