### ISSUE TITLE
Cannt  view image if img element has `loading="lazy"` attribute

### ISSUE THREAD

**Issue by RoamIn** [fengyuanchen/viewerjs#403]
**Describe the bug**
Cannt  view image if img element has `loading="lazy"` attribute

**To Reproduce**
```html
<div
		class="c-image-viewer"
		ref="viewer"
	>
		<img
			class="c-image-viewer__image"
			loading="lazy"
			v-for="(src, index) in images"
			:src="src.thumbnail"
			:data-src="src.source"
			:key="src.source"
			@click="handleViewImage(index)"
		/>
	</div>
```

```js
methods: {
	handleViewImage(index) {
		if (!this.viewer) {
			this.viewer = new Viewer(this.$refs.viewer, {
				url(image) {
					return image.src
				},
			})
		}

		this.viewer.view(index)
	},
},
```

**Expected behavior**
should be
![image](https://user-images.githubusercontent.com/11537595/89416617-1e18de80-d760-11ea-8399-0c1b94b535f3.png)

**Screenshots**
but 
![image](https://user-images.githubusercontent.com/11537595/89416273-9501a780-d75f-11ea-837d-8cbb8c780d25.png)

If I remove `loading="lazy"` attribute, everything goes well

**Desktop (please complete the following information):**
 - MacOS
 - Browser Chrome
 - Version  84.0.4147.105

**Comment by fengyuanchen** [comment]
Just remove the `loading` attribute from the [`inheritedAttributes`](https://github.com/fengyuanchen/viewerjs#inheritedattributes) options:

**Comment by jeff-wangzhen** [comment]
> Just remove the `loading` attribute from the [`inheritedAttributes`](https://github.com/fengyuanchen/viewerjs#inheritedattributes) option.

只能这样了吗？是否有优化空间呢？
