### ISSUE TITLE
Viewer 在linux环境下打包 打包过后插件失效

### ISSUE THREAD

**Issue by JiaXueYan** [fengyuanchen/viewerjs#404]
**Describe the bug**
Viewer 在linux环境下打包Vue项目 打包过后插件失效

**To Reproduce**
Jenkins自动化部署在服务器打包，配置打包完成之后部署到域名下无法直接展示图片

**Comment by fengyuanchen** [comment]
这应该跟 Viewer.js 本身没有关系吧？
