### ISSUE TITLE
IE 11 下只能打开小体积图片(大概几百 k)，大体积图片无法打开。

### ISSUE THREAD

**Issue by github177** [fengyuanchen/viewerjs#406]
**Describe the bug**
IE 11 下只能打开小体积图片(大概几百 k)，大体积图片无法打开。

IE具体版本：
![IE不兼容版本](https://user-images.githubusercontent.com/29110310/91113130-68361580-e6b7-11ea-98ff-24c79d38d9eb.png)

控制台无报错

**To Reproduce**
1. 打开网页。
2. 点击一张大体积图片(超过 1.5M )预览。
3. 问题如「Screenshots」。

**Expected behavior**
图片正常展示

**Screenshots**
![无法打开图片](https://user-images.githubusercontent.com/29110310/91113448-307b9d80-e6b8-11ea-92e2-7de7eb376aa5.png)
因涉及敏感信息，所以做了打码处理，请见谅。

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser：IE
 - Version：IE 11.1397.17763.0

  PS：之前看到您在 #264 回复说的是超过内容限制了，但是我看了下他的图片是 7M 左右的，我现在遇到的图片是 2M 左右都打不开了，这个限制好像有点小，不知道您这边有没有其他的解决方法呢？麻烦您了

**Comment by fengyuanchen** [comment]
1. IE按F12进入控制台看看有没有什么报错信息。
2. 如果方便，把你的测试图片邮件发我我看一下能不能复现。
