### ISSUE TITLE
IE11 unresponsive when panning or zooming image

### ISSUE THREAD

**Issue by RabidArts** [fengyuanchen/viewerjs#409]
**Describe the bug**
If click-dragging image or zooming with mouse wheel, the IE 11 window becomes very unresponsive for a while - making it quite unusable. Issue lies with `inline:false` mode only.

**To Reproduce**
1. Use the following config:
```
this._viewer = new Viewer(this.images.nativeElement, {
      url: 'data-original',
      loading: true,
      inline: false,
      backdrop: false,
      button: false,
      ready() {
        this._viewer.show();
      }
    });
```
2. With the image shown, click and drag the image. Notice your browser groan and creak and cry out loud in pain. Same with the zoom button.
3. Open IE11 dev tools (F12), and start a performance profile session. See attached image of what you'll find.

**Expected behavior**
Ability to move and zoom the image smoothly without tears in my eyes (in a bad way) and minutes wasted getting it to respond.

**Screenshots**
IE 11 Performance profiling (notice how a single mouse event handling takes nearly 1 second to finish): ![image](https://user-images.githubusercontent.com/1357985/91967728-e88df380-ed13-11ea-8a30-5ebec3d70515.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: IE11

**Comment by RabidArts** [comment]
Using 'inline:true' works fine, but in this case I require inline:false functionality

**Comment by fengyuanchen** [comment]
Remove the `this._viewer.show();` line from the `ready` hook, and try again.

**Comment by fengyuanchen** [comment]
Cannot reappear your problem after tested on IE 11 in the Windows 10. Can you provide an online demo for testing?
