### ISSUE TITLE
Using ViewerJS in React

### ISSUE THREAD

**Issue by rhc912** [fengyuanchen/viewerjs#41]
Im using a  componentDidMount and the only way to get viewer to work is by setTimeout. Is that not advised? Should I use another method? Heres a sample of the code:

componentDidMount: function(){
    setTimeout(function(){
      var viewer = new Viewer(document.getElementById('slideshow'), {button: true});
      viewer.show()
      viewer.play()
    }, 2000)
    var elems = document.getElementById('slideshow');
    console.log("elems are ", elems);

**Comment by infeng** [comment]
@rhc912 you should try [react-viewer](https://github.com/infeng/react-viewer) which is a react component and similar to viewerjs, welcome try and feedback.

**Comment by kishoreknowapp** [comment]
that is causing error in packaged build
