### ISSUE TITLE
Custom control in caption/title

### ISSUE THREAD

**Issue by amitpandeyjss** [fengyuanchen/viewerjs#412]
@fengyuanchen Thanks a lot for the library.
I want to create a customized caption/title with some input control with the edit feature instead of showing just an image while previewing an image. Currently, the viewer is showing an image name in the popup view for ...
**image.alt** + ' (' + (this.index + 1) + '/' + this.length + ')'
Expecting to customize this section and want to add some control inside this area. Not found and example of this. Is it possible?

Thanks in advance!
Amit

**Comment by fengyuanchen** [comment]
Just edit the title element diectly:

```js
var image = new Image();

image.src = 'https://fengyuanchen.github.io/viewerjs/images/tibet-1.jpg';

var viewer = new Viewer(image, {
  viewed: function () {
    viewer.title.innerHTML = '<input name="title" placeholder="Enter the title" />';
  },
});

viewer.show();
```
