### ISSUE TITLE
viewer.min.js在IE11中，加载时会报错：对象不支持此操作

### ISSUE THREAD

**Issue by xjlqwe** [fengyuanchen/viewerjs#413]
viewer.min.js在IE11中，加载时会报错：对象不支持此操作
报错代码部分：
bt=(wt=!1,t&&(ft=!1,pt=function(){},vt=Object.defineProperty({},"once",{get:function(){return wt=!0,ft},set:function(t){ft=t}}),n.addEventListener("test",pt,vt),n.removeEventListener("test",pt,vt)),wt);

**Comment by fengyuanchen** [comment]
经过测试，无法复现。
