### ISSUE TITLE
 Add the ability to change icons in toolbar

### ISSUE THREAD

**Issue by VictorPullzz** [fengyuanchen/viewerjs#417]
Add the ability to change icons in toolbar. And add custom button, for ex. donwload image, etc.
![image](https://user-images.githubusercontent.com/23406402/95431058-4b972980-0955-11eb-9e68-096e66411b2d.png)

**Comment by fengyuanchen** [comment]
Already support this, just see [this example](https://fengyuanchen.github.io/viewerjs/examples/custom-toolbar.html).

> The download button and its icon is custom totally.

**Comment by VictorPullzz** [comment]
@fengyuanchen Ah, thanks! I will check this!
