### ISSUE TITLE
大佬，支持增加自定义按钮吗

### ISSUE THREAD

**Issue by 1130204153** [fengyuanchen/viewerjs#418]
比如我想要增加一个截图功能，可以传入一个dom进去，并且可以增加相应的事件，这个现在支持吗

**Comment by fengyuanchen** [comment]
你这种情况应该是不支持的。你如果想折腾，可以自己试一试。

**Comment by fengyuanchen** [comment]
简单的自定义按钮还是支持的，不如“下载”按钮，示例：https://fengyuanchen.github.io/viewerjs/examples/custom-toolbar.html
