### ISSUE TITLE
使用viewer.min.js 显示图片分辨率的连接符乱码

### ISSUE THREAD

**Issue by lrzl** [fengyuanchen/viewerjs#419]
**bug描述**
浏览器：chrome 86.0.4240.75（正式版本） （64 位）
系统：windows10
问题如图所示
![image](https://user-images.githubusercontent.com/32292315/96220220-eb3e6280-0fba-11eb-96c2-b39291afa67b.png)

**问题原因**
通过viewer.js中查看对应符号确定连接符为``` \xD7```
但在viewer.min.js中被转码为 ```×```
所以造成浏览器乱码，手动在viewer.min.js替换符号解决。
猜测应该属于js压缩过程中被转码

**Comment by fengyuanchen** [comment]
无法复现。你的HTML页面头部添加 `<meta charset="utf-8">` 这一行了吗？

**Comment by lrzl** [comment]
> 无法复现。你的HTML页面头部添加 `<meta charset="utf-8">` 这一行了吗？

这个添加了的。我使用的是 v1.7.1版本，手动把 viewer.min.js 里的 ```×``` 改为 ```\xD7``` 就不乱码了

**Comment by fengyuanchen** [comment]
直接[在NPM上查看源代码](https://unpkg.com/browse/viewerjs@1.7.1/dist/viewer.min.js)，可以看到 `×` 字符**并未**被替换成  `\xD7`！

所以，你从哪里下载的代码包？
