### ISSUE TITLE
希望对展示模式中的大图增强扩展性

### ISSUE THREAD

**Issue by mirari** [fengyuanchen/viewerjs#420]
**Is your feature request related to a problem? Please describe.**
有些需求希望在图片展示后，对其进行一些附加动作，比如在图片指定位置添加标注，需要通过canvas等方式实现，且能够跟随图片的缩放、拖拽一起运动。但是现在.viewer-canvas下只有一个img标签，缩放拖拽只能直接操作它，没法在img标签里插入其他的元素。

**Describe the solution you'd like**
希望能将 `.viewer-canvas > img` 改成`.viewer-canvas > div > img`这样的形式，在img外面包裹一层div，缩放拖拽等操作的对象是这个div。这样就可以在viewed事件之后在div里进行一些元素操作。

**Describe alternatives you've considered**
如果启用这个功能的实际效果不稳定或者可能附带其他潜在问题，可以作为试验性的配置项，默认关闭。

**Comment by fengyuanchen** [comment]
作为一个**简单**的图片查看器，我一直避免附加太多**特殊**或**不太相关**的功能。所以谢谢你的这个提议，不过目前来说我还不会考虑实现它。

**Comment by zdjzce923** [comment]
mark
