### ISSUE TITLE
(howto) set image grid size

### ISSUE THREAD

**Issue by opto** [fengyuanchen/viewerjs#423]
before showing the viewer, the examples show square image previews in a 3x3 grid (= 9 images in the example).

Howto change the grid size? E.g. 4 horizontal, vertical as many as needed?

Thanks,

Klaus

**Comment by fengyuanchen** [comment]
For your case, I think you may need to learn some basic [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) and [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS) knowledge.
