### ISSUE TITLE
Viewer does not work after AJAX

### ISSUE THREAD

**Issue by amirmp3** [fengyuanchen/viewerjs#424]
Hi, thanks for developing Viewer it is great.
I have a problem after AJAX, generally, viewer work well as an image viewer on my site but I recently added an ajax feature to load more posts without page refresh, it works well but after load image viewer does not work.
In the past, I had the same problem with the click event and I solved it like this 
`$(document).on('click', '.btn', function (){***} `
now I am curious about a way to solve this issue.

I define image viewer like this does it make the problem?
`
Array.from(document.querySelectorAll('.viewer')).map(x => new Viewer(x, {
         className: "imgViewer",    
}));
`

**Comment by fengyuanchen** [comment]
After loading the images, you may need to destroy the previous Viewer instance and initialize a new Viewer instance again.
