### ISSUE TITLE
filter返回false时尽管该图片不能点击放大，但其他图片放大后也会显示该图片

### ISSUE THREAD

**Issue by liuhr-ncu** [fengyuanchen/viewerjs#425]
filter返回false时尽管该图片不能点击放大，但点击其他图片(filter返回true的那些)放大后却可以显示该图片(此时filter返回false的图片也出现在了大图中),预期filter返回false的那些图片不应该出现在图片查看器中

**Comment by fengyuanchen** [comment]
无法复现。我记得之前修复过类似问题了，你用的是最新版本？

**Comment by liuhr-ncu** [comment]
> 无法复现。我记得之前修复过类似问题了，你用的是最新版本？
V1.7.1

**Comment by fengyuanchen** [comment]
不知道你怎么配置 filter 的，能否提供一个示例？
