### ISSUE TITLE
Can i write html on image with Different Placements? 

### ISSUE THREAD

**Issue by MoaizPervaiz** [fengyuanchen/viewerjs#428]
I use this library for showing my gallery images but I want to show html on image with different placements. Below I attached screenshot for clarifying  what can I want .

![image](https://user-images.githubusercontent.com/28903192/100610240-2ad5c980-3331-11eb-9f4f-24d438011375.png)

Please tell me a possible solution so I can get rid of this problem. Thanks.

**Comment by fengyuanchen** [comment]
No support that, buddy! But you can try to inject some elements into the viewer canvas once viewed one image (in the event listener of the `viewed` event) by yourself.
