### ISSUE TITLE
Multiple Galleries on the same page

### ISSUE THREAD

**Issue by SergeyBondarenko91** [fengyuanchen/viewerjs#43]
Hi,

Is it possible to have multiple galleries on the same page? I have one working but can't seem to get more than that?

Thanks!

**Comment by fengyuanchen** [comment]
Supports this by default. But you should keep put each gallery in different containers and initialize each gallery by Viewer.js.

**Comment by SergeyBondarenko91** [comment]
How to initialize each gallery by Viewer.js?

**Comment by fengyuanchen** [comment]
```js
new Viewer(gallery1);
new Viewer(gallery2);
new Viewer(gallery3);
...
new Viewer(galleryN);
```

**Comment by SergeyBondarenko91** [comment]
So simple is
Thanks!

**Comment by SergeyBondarenko91** [comment]
Can you describe in more detail how to initialize a new gallery?
