### ISSUE TITLE
Add image description tag that responds to launch image viewer

### ISSUE THREAD

**Issue by shanmukhateja** [fengyuanchen/viewerjs#430]
**Is your feature request related to a problem? Please describe.**
Add click event to image descriptive tag like`<label>` beside `<img>` such that clicking on either of them should launch Image viewer 

**Describe the solution you'd like**

#### Individual image

```html 
<div>
  <img src="./images/image1.png">
  <label>Fig: Image 1</label>
</div>
```

#### List of images

```html 

<ul>
  <li>
    <img src="./images/image1.png">
    <label>Fig: Image 1</label>
  </li>
  <li>
    <img src="./images/image2.png">
    <label>Fig: Image 2</label>
  </li>
</ul>
```

**Describe alternatives you've considered**
N/A

**Additional context**
The modification is a 3-line change to `src/js/viewer.js` [here](https://github.com/fengyuanchen/viewerjs/blob/7572201fe8c5d5a9d461a46c6a242bdeb2b3359e/src/js/viewer.js#L167)

#### Before:

```javascript
addListener(element, EVENT_CLICK, (this.onStart = ({ target }) => {
        if (target.localName === 'img' && (!isFunction(options.filter) || options.filter.call(this, target))) {
          this.view(this.images.indexOf(target));
        }
}));

```

#### After:

```javascript
addListener(element, EVENT_CLICK, (this.onStart = ({ target }) => {
        const finalTarget = target.localName === 'label' ? target.parentElement.querySelector('img') : target;
        if (finalTarget.localName === 'img' && (!isFunction(options.filter) || options.filter.call(this, finalTarget))) {
          this.view(this.images.indexOf(finalTarget));
        }
}));
```

**Comment by fengyuanchen** [comment]
Thanks for your suggestion, but:
1. It seems the `<label>` element is used in a pair with the form control elements (`<input>`, `textarea`, etc), but not used for the `<img>` element.
2. This is an unnecessary feature for most people, in order to keep this library simple and maintainable, I will not add this feature as well.
