### ISSUE TITLE
Download option in image view

### ISSUE THREAD

**Issue by abhishekbadola** [fengyuanchen/viewerjs#431]
Can you please provide an option to download the image.

**Comment by fengyuanchen** [comment]
You can add one by yourself with the `toolbar` option, follow this example:

> https://fengyuanchen.github.io/viewerjs/examples/custom-toolbar.html

**Comment by abhishekbadola** [comment]
Do we have specify all toolbars to customize? or if we just want to add one more button to the existing toolbar?

**Comment by fengyuanchen** [comment]
@abhishekbadola Read the doc, have a try, and then you will understand it.

> https://github.com/fengyuanchen/viewerjs#toolbar
