### ISSUE TITLE
Fire event for reset action

### ISSUE THREAD

**Issue by Cheyenne55** [fengyuanchen/viewerjs#432]
Hi,

Would be a nice addition if an event could be fired when clicking on the reset button in the toolbar.
I feel like it is not complicated to add (line 1066 of methods.js call dispatchEvent ?).

What do you think ?

**Comment by fengyuanchen** [comment]
I will think about this, but there are too many events currently.

**Comment by Leon0402** [comment]
Would need this as well! I have some custom logic to save the zoom level and other properties of an image and apply it to the next image in modal model (to allow better comparison of images). But when the reset Button is used, there is no way to reset my variables saving these configurations.

**Comment by fengyuanchen** [comment]
It supports to customize the toolbar and watch the reset action:

```js
new Viewer(images, {
  toolbar: {
    oneToOne: true,

    prev: function() {
      viewer.prev(true);
    },

    play: true,

    next: function() {
      viewer.next(true);
    },

    reset: function() {
      // Do something before reset...

      viewer.reset();

      // Do something after reset...
    },
  },
});
```

**Comment by ghostman-git** [comment]
> It supports to customize the toolbar and watch the reset action:
> 
> new Viewer(images, {
>   toolbar: {
>     oneToOne: true,
> 
>     prev: function() {
>       viewer.prev(true);
>     },
> 
>     play: true,
> 
>     next: function() {
>       viewer.next(true);
>     },
> 
>     reset: function() {
>       // Do something before reset...
> 
>       viewer.reset();
> 
>       // Do something after reset...
>     },
>   },
> });

Good👍
