### ISSUE TITLE
图片显示的问题

### ISSUE THREAD

**Issue by zuosenyu** [fengyuanchen/viewerjs#433]
我的一条数据中附带了多张图片，拿出来的时候，图片显示时竖排显示的，怎么改成横向显示呢，求告知
![image](https://user-images.githubusercontent.com/47630519/101970543-f84b9b00-3c65-11eb-83f7-9c7c9f038ca6.png)

**Comment by fengyuanchen** [comment]
你不会自己调整一下 CSS 样式啊！
