### ISSUE TITLE
Multiple Galleries on the same page

### ISSUE THREAD

**Issue by SergeyBondarenko91** [fengyuanchen/viewerjs#44]
Hi,

Is it possible to have multiple galleries on the same page? I have one working but can't seem to get more than that?
Please describe as detailed as possible.

I know that
new Viewer(gallery1);
new Viewer(gallery2);
new Viewer(gallery3);
...
new Viewer(galleryN);

I can not introduce

Thanks!

**Comment by josundin** [comment]
It would be a great addition to have multiple galleries. I am sure more people than we two are  interested to have this feature.
Any ideas or pointers how to implement multiple galleries support?

**Comment by fengyuanchen** [comment]
http://codepen.io/chenfengyuan/pen/bwqjGQ

**Comment by josundin** [comment]
Awesome. Perfectly explained :D Thank you.

**Comment by deterenkelt** [comment]
Excuse me, I am concerned with the same issue and the example doesn’t seem to work. Nothing happens on click.

![1487928064](https://cloud.githubusercontent.com/assets/2245254/23297795/5ad70ed4-fa94-11e6-97e5-e42dc1faa03c.png)
