### ISSUE TITLE
toolbar property, does not accept custom properties

### ISSUE THREAD

**Issue by seahindeniz** [fengyuanchen/viewerjs#440]
> You can add one by yourself with the `toolbar` option, follow this example:
> 
> > https://fengyuanchen.github.io/viewerjs/examples/custom-toolbar.html
> 
_Originally posted by @fengyuanchen in https://github.com/fengyuanchen/viewerjs/issues/431#issuecomment-740590279_

Hi @fengyuanchen,

The suggested example is no longer valid, or it's actually not possible with Typescript. 
The `ToolbarOptions` interface only accepts specified toolbar props and rejects addition of custom properties.
https://github.com/fengyuanchen/viewerjs/blob/b8a0fd4e69f4710f9c2bfd2ca1c8d0bc2b39d989/types/index.d.ts#L22-L34

There is also another problem with the given example is that with the Viewer instance. It's type definition doesn't have `.image` property, yet that property have provided in the given example.

**Comment by fengyuanchen** [comment]
Fixed this in #441.
