### ISSUE TITLE
Change Position / zoom level of images before they appear

### ISSUE THREAD

**Issue by Leon0402** [fengyuanchen/viewerjs#442]
**Is your feature request related to a problem? Please describe.**
It does not seems possible to modify the image in any way before it actually shows up on the screen. If I set some zoom leve with the zome function in `viewed()` in modal mode, then the image will first show up normally and then will be zoomed. Rather than show up directly zoomed. 

**Describe the solution you'd like**
Support to call alle functions modifying images before they are visible i.e. call them in the `view` event rather than the `viewed`event. This would allow to bring images in an inital position.

**Comment by fengyuanchen** [comment]
You may need to set the `transition` option to `false`.
