### ISSUE TITLE
How to change size of the image?

### ISSUE THREAD

**Issue by SmoothJM** [fengyuanchen/viewerjs#444]
I would like to change the img size in the viewr-container. I set the container 380px*380px. I see the source code change the img size like that width*0.9. So, could you please tell me how to set the size of img?
![image](https://user-images.githubusercontent.com/44306149/106088740-6668f600-611e-11eb-8d44-fba2f9c245a0.png)
![image](https://user-images.githubusercontent.com/44306149/106088762-6f59c780-611e-11eb-9aa1-8f233ab7c6bd.png)
![image](https://user-images.githubusercontent.com/44306149/106088778-7680d580-611e-11eb-923b-41091207ef2a.png)

**Comment by fengyuanchen** [comment]
Just use the `zoom` or `zoomTo` methods to scale the image after it is viewed.
