### ISSUE TITLE
移动端混合开发嵌入APP的H5页面全屏预览切换图片时触发浏览器的后退操作，返回了上一页

### ISSUE THREAD

**Issue by zhangqiangzgz** [fengyuanchen/viewerjs#447]
**Describe the bug**
移动端混合开发，嵌入APP的H5页面中，全屏预览图片时，右滑切换图片容易触发浏览器的后退操作，切换到了前一页

**To Reproduce**
1. 点击图片列表中的某个图片进入全屏预览模式
2. 向右滑动切换图片
3. 页面返回了上一页

**Smartphone (please complete the following information):**
 - Device: iPhoneSE
 - OS: iOS13.3
 - Version 13.3

**Comment by fengyuanchen** [comment]
这应该是你要在你的应用中的上一层禁用滑动返回上一页吧。

**Comment by zhangqiangzgz** [comment]
您好，没太理解，可以明确下吗，谢谢。之前用的一个vue的预览库是一个禁用掉滑动返回的，但是有兼容问题，所以弃用了。希望咱们也可以支持下禁用滑动返回的交互。

**Comment by fengyuanchen** [comment]
1. 你要确定一下具体哪个触摸屏事件导致滑动返回。
2. 在Viewer的父级元素监听这个事件，禁用滑动返回。
