### ISSUE TITLE
Viewer can't open in IE when on a page with 90 images

### ISSUE THREAD

**Issue by glennax** [fengyuanchen/viewerjs#45]
Hi there,
Thank you for creating such an awesome library. However, I found that when there are many images, such as my application which has 90 images on one page, the viewer just seems to stuck in IE 11 (no image is shown). Works fine in Chrome. Any ideas? 

the error I am getting in IE is "Not enough storage is available to complete this operation."
Thanks!

**Comment by fengyuanchen** [comment]
You may need to limit the number of the images.

**Comment by NivarnaRen** [comment]
Hi Chen,
This library you created is so awesome .But I found it is not suported by IE8 ,IE9 .Do you have any plan to update ?

**Comment by fengyuanchen** [comment]
@NivarnaRen Try the jQuery version please: https://github.com/fengyuanchen/viewer
