### ISSUE TITLE
不可以修改点击后图片出现的初始尺寸

### ISSUE THREAD

**Issue by AnbolKing** [fengyuanchen/viewerjs#450]
Is your feature request related to a problem? Please describe
想问一下现在是还没有图片点击后一开始出现的尺寸自定义是吗，希望可以自定义一开始图片出现的尺寸而非通过放大缩小

**Comment by fengyuanchen** [comment]
You can call the `zoom` or `zoomTo` methods after the image has been viewed (in the `viewed` event handler).
