### ISSUE TITLE
Inline模式下有图片加载出错时，整个viewer都无法正常运行

### ISSUE THREAD

**Issue by mirari** [fengyuanchen/viewerjs#456]
**Describe the bug**
图片列表中存在无法显示的图片时，inline模式无法正常运行

**To Reproduce**
在线demo：
https://codepen.io/mirari/pen/yLVrpNd
当前例子为viewer的inline模式正常显示状态。
将脚本12行的异常URL注释取消，即可看到viewer无法正常运行

**Expected behavior**
除了无法显示的图片，viewer应该能够显示。

**Additional context**
发现之前也有几个issue反馈类似问题，但没有提供在线例子。
#325 
#344

**Comment by liuxsen** [comment]
我也遇到这个问题了，请问你解决了吗？

**Comment by DazhiFe** [comment]
请问这个问题有解决了吗，同样遇到这个问题

**Comment by CuiYuXi** [comment]
这个问题解决了吗？我有时候还会出现图片都正常加载但是浏览界面没有展开的情况如图
![image](https://user-images.githubusercontent.com/20012604/149750627-6bc23533-c5ef-4799-a6b2-4cc6ce39d3fc.png)

**Comment by fengyuanchen** [comment]
目前无法复现了。
