### ISSUE TITLE
Viewer.js and Swiper.js conflict?

### ISSUE THREAD

**Issue by dave1981** [fengyuanchen/viewerjs#458]
**Describe the bug**
I have a page with two main components:
- viewer.js displaying an image
- swiper.js displaying a list of thumbnails; when the user click on one of them, viewer.js should show the full image

**Expected behavior**
It seems that viewer.js does not allow scroll or click events to be captured in swiper.js, in fact the functions that should manage the click is never called. If I remove the creation of the viewer, the scroll and click events are correctly managed.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome or firefox
 - Version: latest

**Comment by fengyuanchen** [comment]
You can bind a click event on the image by yourself to show the viewer, for example:

https://fengyuanchen.github.io/viewerjs/examples/dynamic-viewer.html
