### ISSUE TITLE
当页面上有video的时候 点击底部的播放按钮，会全屏播放视频

### ISSUE THREAD

**Issue by Undo101** [fengyuanchen/viewerjs#459]
**Describe the bug**
当页面上有video的时候 点击底部的播放按钮，会全屏播放视频

**Screenshots**
![image](https://user-images.githubusercontent.com/26062774/113384629-0a8a4a00-93b9-11eb-9b6d-3103922eae2a.png)
![image](https://user-images.githubusercontent.com/26062774/113384724-402f3300-93b9-11eb-907d-fdbe281f542b.png)

**Comment by fengyuanchen** [comment]
我在官方示例页面中插入一个视频后（`<video src="https://vjs.zencdn.net/v/oceans.mp4" controls></video>`），并没有复现该问题。推测可能是你使用的视频播放插件监控了全屏事件。

**Comment by Undo101** [comment]
viewerjs的dom节点index的css层级低于视频时就可以稳定复现。

**Comment by fengyuanchen** [comment]
**推测可能是你使用的视频播放插件监控了全屏事件。**

> 你可以将 Viewer.js 的 `fullscreen` 参数设置为 `false` 以避免触发全屏。
