### ISSUE TITLE
Not able to get preview on dynamic load of images

### ISSUE THREAD

**Issue by sandhoter** [fengyuanchen/viewerjs#46]
My image sources is in  `<tbody>  <tr> <td><span><img src='abc'>` this was populated dynamically where viewer.js is not picking up on preview.

Static files working good

**Comment by fengyuanchen** [comment]
Call the `update` method to add those images dynamically!

**Comment by KevinPan** [comment]
I get an error if I initialize viewer with no image in the target element.
e.g:
var viewer = new Viewer(document.getElementById('imageContainer'), { title: false });

And later, I add images to imageContainer, then I call viewer.update();
there is an exception in line 2172: _this.length = _this.images.length;
the _this.images is undefined.

Uncaught TypeError: Cannot read property 'length' of undefined
    at Viewer.update (viewer.js:2172)
    at <anonymous>:1:8

**Comment by fengyuanchen** [comment]
If no image at all, why not just init the viewer after the images loaded?!
