### ISSUE TITLE
add/move to the side, right and left navigation button #460

### ISSUE THREAD

**Issue by marcarc** [fengyuanchen/viewerjs#461]
Hi!
I was wondering, if there is an option, to add, or move the navigation (right & left) buttons on the side, instead of at the button in the toolbar, like that:

![button](https://user-images.githubusercontent.com/63582018/114007659-d358e480-9861-11eb-9a5e-4f7098aa85cb.png)

Or should I just override the "toolbar" CSS and move the buttons? Or any better ideas?

Thank you for your reply :)

**Comment by fengyuanchen** [comment]
No support it.

You can try to insert some custom buttons into the viewer after it is shown.

> PS: Console the viewer instance, and you will find the root element of the viewer.
