### ISSUE TITLE
在nuxt 使用了这个插件  

### ISSUE THREAD

**Issue by cplcurry3035** [fengyuanchen/viewerjs#463]
好像不能使用使用new的形势 会报错 因为我想要获取他点击事件 默认展开对应视图的方法 如下  this.$viewer = new Viewer(this.$el, this.options)   this.$viewer.view(0)  view 方法   急！！！！

**Comment by fengyuanchen** [comment]
你不看文档吗？这个 `view` 方法必须在 `shown` 事件处理函数中调用！

> https://github.com/fengyuanchen/viewerjs#methods

**Comment by cplcurry3035** [comment]
> 你不看文档吗？这个 `view` 方法必须在 `shown` 事件处理函数中调用！
> 
> > https://github.com/fengyuanchen/viewerjs#methods

**Comment by cplcurry3035** [comment]
主要是在服务端使用这个插件好像不能使用new的形势 会报错  就是  new viewer 更不用说使用里面的api了

**Comment by fengyuanchen** [comment]
Viewer.js 依赖浏览器环境，不支持服务端使用，请在浏览器端进行初始化。
