### ISSUE TITLE
Basic ES import not working

### ISSUE THREAD

**Issue by issimissimo** [fengyuanchen/viewerjs#465]
**Describe the bug**

ViewerJS don't work when imported.
No errors in the console, but the Viewer is not created

**To Reproduce**

-- index.html --

 <div id="ImageViewer" style="width: 500px; height: 300px;
    background-color: red;"></div>

-- index.js --

`import 'viewerjs/dist/viewer.css';
import Viewer from 'viewerjs';
import imgTest from './imageTest.jpg';

const viewer = new Viewer(document.getElementById('ImageViewer'), {
    inline: true,
    view(event) {
        console.log("view")
    },
    viewed(event) {
        console.log("viewed")
    },
    url() {
        return imgTest;
    },
});`

**Comment by issimissimo** [comment]
my fault, solved

**Comment by vaibhav-bkit** [comment]
@issimissimo  can you please tell me what worked for you?
