### ISSUE TITLE
Add endless mode

### ISSUE THREAD

**Issue by BoBRoID** [fengyuanchen/viewerjs#47]
Hi! How about add endless mode for viewer?
It seems as if you on last image, the next image is first image
Please, add that feautere, or some event for this. Thanks

that on russian (sorry for my bad english, maybee some program can translate it from russian better than me):
Привет! Как насчёт добавить бесконечный режим для viewer'а?
Это должно быть так: когда ты доходишь до последнего изображения, нажатие на стрелку "дальше" должно отправлять на первое изображение (так, чтобы они повторялись по кругу)
Пожалуйста, добавьте возможность включить такой режим (например, какой-то флаг в опциях), или какой-то event, когда пользователь достигает последнего изображения.

**Comment by fengyuanchen** [comment]
As of v0.9.0, the `prev` and `next` methods support loop mode.

**Comment by fengyuanchen** [comment]
Here is an example for customizing toolbar with loop prev and next behaviour:
https://github.com/fengyuanchen/viewerjs/blob/master/examples/custom-toolbar.html
