### ISSUE TITLE
关于插入多个viewer标签，图片显示错乱的问题

### ISSUE THREAD

**Issue by Ma-web1010** [fengyuanchen/viewerjs#471]
作者呀，或者有没有大佬能帮我解决一下，我是个刚入门的菜鸟，项目功能需求是要有六个上传图片的地方，传上来的图片需要点击查看图片并能放大缩小旋转，于是我用了v-viewer插件。现在我把打开图片预览放在了一个按钮点击事件里，点击了按钮之后通过回调触发图片显示，ref我也绑定了，inited事件也定义了，点击事件里的代码：this.$viewer.show()和this.$viewer.view(index)，可是因为页面中有多个需要查看图片的地方，所以我就创建了多个<viewer>，都分别绑定了@inited事件，bug是：比如当我在第二个<viewer>上传完图片并点击第二个<viewer>来显示它绑定的数组里的图片时 显示正常，然而当我在点击第一个<viewer>时，显示的还是第二个<viewer>里面的数据也就是图片，除非我在第一个<viewer>里面重新上传一张新的图片，再点击新图片的预览第一个<viewer>里所有的图片才会显示正常(也就是显示第一个viewer绑定数组里的图片)，然后同样第二个以及其余的<viewer>同样的显示的是第一个viewer绑定的数组里面的图片，（也就是说只有我重新触发预览按钮，它才会重新绑定数组）真的研究好长时间了还是没有解决明白，有没有能帮忙的呀，困扰死我这个菜鸟了

**Comment by Ma-web1010** [comment]
已解决

**Comment by ImmerTry** [comment]
怎么解决的
