### ISSUE TITLE
How to update size manually?

### ISSUE THREAD

**Issue by yunyuyuan** [fengyuanchen/viewerjs#472]
Thanks for the project.
I use the `inline mode` in my project, and viewer container can be resize by user,how do I update size of viewer manually like this:
```js
const viewer = new Viewer(...);
viewer.updateSize();
```

**Comment by fengyuanchen** [comment]
You can call the internal method `resize`:

```js
const viewer = new Viewer();

viewer.resize();
```

**Comment by yunyuyuan** [comment]
> You can call the internal method `resize`:
> 
> ```js
> const viewer = new Viewer();
> 
> viewer.resize();
> ```

Please add this to README

**Comment by fengyuanchen** [comment]
The `resize` method is an **_internal_** function that will be called on the window resized. It is not recommended to call it manually!

**Comment by yunyuyuan** [comment]
> The `resize` method is an **_internal_** function that will be called on the window resized. It is not recommended to call it manually!

Well,someone need it, like me...

I recommend to add a `updateSize` method,distinguishes it from **internal**  `resize`.
