### ISSUE TITLE
1.10还是有模态窗口内存溢出问题。

### ISSUE THREAD

**Issue by lucifer8900** [fengyuanchen/viewerjs#486]
var viewer = new Viewer(objDiv, {
                    inline: false,
                    modal: true,
                    navbar: false,
                    title: false,
                    keyboard: false,
                    fullscreen: false,
                    tooltip: false,
                    focus: false,
                    loop: false,
                    transition:true,
}
当在模态窗口中打开viewer.js用modal :true时，依然会内存溢出
我自己弹出一个模态窗口，然后里面放入viewer.js.

**Comment by lucifer8900** [comment]
![image](https://user-images.githubusercontent.com/1785356/123025379-22e49080-d40d-11eb-90c3-3c1596bc9b23.png)
![image](https://user-images.githubusercontent.com/1785356/123025439-32fc7000-d40d-11eb-8e45-40433ed629a4.png)
很 奇怪的问题，我在一个弹出窗口中使用，只要我把focus设为true就会提示溢出，设为false就没问题。
但是在主页面没有这个问题。

**Comment by fengyuanchen** [comment]
你用的什么弹窗组件？弹窗根元素上没有[设置 `tabindex` 和 `aria-modal` 属性](https://github.com/fengyuanchen/viewerjs/blob/4ac8bd335e38a68343db2cbd9b5cb344f2f307cb/src/js/others.js#L50)？

> PS: 实在不行，就把 `focus` 设置为 `false` 吧……
