### ISSUE TITLE
Method update() : TypeError: Cannot read property 'removeAttribute' of undefined

### ISSUE THREAD

**Issue by Xavlight** [fengyuanchen/viewerjs#491]
Hi,
I am trying to refresh the viewer window after deleting an image.

I dynamically create my list of images.
And I delete some.

```
<div id="gallery" class="d-none">
	<img src="vue/26-v-1625755012144081.jpg" alt=" " data-id="1">
	<img src="vue/24-v-1624618719704697.jpg" alt="Hall d'entrée" data-id="3">
</div>
```

```
viewer = new Viewer(images);

//On button click
photocurrent.remove();
viewer.update();
```

When I delete a line with the image in jquery.
I run the update() method.
It removes the image in the bottom navigation bar, and generates an error :

Uncaught TypeError: Cannot read property 'removeAttribute' of undefined
    at i.view (viewer.min.js:10)
    at i.update (viewer.min.js:10)
    at removeCurrentImg (Viewer.js.html:102)

Thanks

**Comment by Xavlight** [comment]
Hi,
I solved this bug, when I delete an image, and I want update for refresh viewer.

in line 2020 :
```
var activeItem = this.items[this.index];
if (activeItem) { //Just add this condition
	removeClass(activeItem, CLASS_ACTIVE);
	activeItem.removeAttribute('aria-selected');
}
addClass(item, CLASS_ACTIVE);
item.setAttribute('aria-selected', true);
```

If an expert can confirm that there are no side effects, and that this is correct.

Thanks

**Comment by cnhuye** [comment]
I have the same error,  I'm using v-viewer, and upgraded viewerjs from 1.5.0 to 1.10.0. after that, I have this problem, when remove the last image.
In the source, #2024:
```
      var activeItem = this.items[this.index];
      removeClass(activeItem, CLASS_ACTIVE);
      activeItem.removeAttribute('aria-selected');
      addClass(item, CLASS_ACTIVE);
      item.setAttribute('aria-selected', true);

```
seems viewerjs removing class from prev image, but when I removed last image, and use update(), ```this.items[this.index]``` will be undefined.

In npm ,I can not fix this from source. Please help ~
