### ISSUE TITLE
inline模式下,full函数，再点击全屏时没有触发

### ISSUE THREAD

**Issue by breakkkk** [fengyuanchen/viewerjs#495]
$('#fullImage').viewer({
                        inline: true,
                        fullscreen:false,
                        show: function() {
                            console.log(123)
                            window.top.$(".layui-layer-close.layui-layer-close2").hide()
                        },
                        hide: function() {
                            window.top.$(".layui-layer-close.layui-layer-close2").show()
                        }

                    });

**Comment by fengyuanchen** [comment]
jQuery 版已废弃。

PS: `show` 和 `hide` 事件仅在 modal 模式中可用，在 inline 模式中无效。
