### ISSUE TITLE
Can the plugin be reset? Reload 

### ISSUE THREAD

**Issue by lllomh** [fengyuanchen/viewerjs#511]
reset()  reset is invalid

thanks 
![image](https://user-images.githubusercontent.com/20123291/140008872-2a42afd9-c9f4-4522-a4bc-07c6d48ec6a8.png)

**Comment by lllomh** [comment]
<div>
  <img id="image" src="picture.jpg" alt="Picture">
</div>  

How to update the picture if it is modified?

**Comment by fengyuanchen** [comment]
Just call the `update` method.
