### ISSUE TITLE
mac双指滑动被识别成放大缩小，是不是可以弄个选项关闭这个呢

### ISSUE THREAD

**Issue by cqmonly** [fengyuanchen/viewerjs#512]
感觉双指滑动一般用于调整位置，但是现在是放大缩小图片了

**Comment by fengyuanchen** [comment]
Just set the `zoomOnWheel` to `false` on MacOS.

> PS: You can also set the `zoomOnTouch` to `false` on a touch screen.

**Comment by cqmonly** [comment]
> Just set the `zoomOnWheel` to `false` on MacOS.
> 
> > PS: You can also set the `zoomOnTouch` to `false` on a touch screen.

但是这样的话，双指的放大缩小就不起作用了
