### ISSUE TITLE
Cannot find name 'FullscreenOptions'

### ISSUE THREAD

**Issue by JaiKumaresh** [fengyuanchen/viewerjs#522]
I used this package in my angular application.
```
Angular CLI: 7.3.10
Node: 10.22.1
OS: darwin x64
Angular: 7.2.16
```
I got the below error after the `ng serve`
```
ERROR in node_modules/viewerjs/types/index.d.ts(91,28): error TS2304: Cannot find name 'FullscreenOptions'.
node_modules/viewerjs/types/index.d.ts(150,31): error TS2304: Cannot find name 'FullscreenOptions'.
```

If anybody have this solution, Kindly share that in here. Thank you :)

**Comment by fengyuanchen** [comment]
You may need to list the `"dom"` lib in the `tsconfig.json` of your project:

```json
{
  "compilerOptions": {
    "lib": ["dom"]
  }
}
```

**Comment by fengyuanchen** [comment]
The `FullscreenOptions` interface is defined in the `node_modules/typescript/lib/lib.dom.d.ts` file.

**Comment by 18353230045** [comment]
遇到相同的问题，node_modules/typescript/lib/lib.dom.d.ts 文件里没发现FullscreenOptions的声明，是TS的版本不对吗

**Comment by fengyuanchen** [comment]
@18353230045 应该是你使用的 `typescript` 版本太低了，我本地的 `typescript@4.6.3/lib/lib.dom.d.ts` 中就有如下定义：

```ts
interface FullscreenOptions {
    navigationUI?: FullscreenNavigationUI;
}
```
