### ISSUE TITLE
建议添加一个下载的功能

### ISSUE THREAD

**Issue by WFL-Tian** [fengyuanchen/viewerjs#525]
**Describe the solution you'd like**
It is recommended to add a download function

It is suggested to add a download function to tell users that they can click to download instead of right clicking to save the picture download.

**Comment by jsuzsj** [comment]
\docs\examples\custom-toolbar.html 里面有例子

**Comment by fengyuanchen** [comment]
自定义下载按钮示例：https://fengyuanchen.github.io/viewerjs/examples/custom-toolbar.html
