### ISSUE TITLE
为什么 width 要乘 0.9 呢？

### ISSUE THREAD

**Issue by liangbus** [fengyuanchen/viewerjs#526]
```
width = Math.min(width * 0.9, naturalWidth);
height = Math.min(height * 0.9, naturalHeight);
```

modal 模式下我想占满屏幕宽度，看了下源码这里似乎没法配置呀？除了改源码，或者手动 zoomTo （动画会有停顿一下的效果，不太理想），还有什么更好的方法？

**Comment by jsuzsj** [comment]
有故障图片么

**Comment by jsuzsj** [comment]
> 

默认是全屏的，而且图片位置也似乎是全屏居中的。

**Comment by liangbus** [comment]
> > 
> 
> 默认是全屏的，而且图片位置也似乎是全屏居中的。

是居中没错，但是图片两侧有 margin，我是移动端用，我随便找一张图（我目前主要用的是 1:1 的图）都不会宽度占满哦，看了下源码确实会有个0.9系数

**Comment by liangbus** [comment]
> > 
> 
> 默认是全屏的，而且图片位置也似乎是全屏居中的。

@jsuzsj 而且手动改源码之后把 0.9 删除确实是正常的了。。。

**Comment by Zeus-Iqd** [comment]
@liangbus

**Comment by fengyuanchen** [comment]
尺寸按 90% 显示，是为了在四周留下空白，以使视觉更加舒适。后期可能会将默认的 0.9 改成可配置参数。

**Comment by liangbus** [comment]
> 
@Zeus-Iqd 拉下来自己改下源码（哭笑，不然只能等作者优化了，之前记得用 reset 方法好像可以，太久了忘记了，可以自己尝试下
