### ISSUE TITLE
移动端双击放大后无法移动图片查看

### ISSUE THREAD

**Issue by jeff-wangzhen** [fengyuanchen/viewerjs#527]
但是如果是双指缩放放大的图片，就可以。看的是这里的例子https://fengyuanchen.github.io/viewerjs/

**Comment by fengyuanchen** [comment]
具体复现步骤3是怎么样的？什么手机？什么浏览器和版本？

**Comment by jeff-wangzhen** [comment]
荣耀9x，自带浏览器,内核92。用电脑chrome（dev, 99）切到移动端模式也可以看出来,双击左键放大图片，会把左上角放大，就不能移动图片看右下角。附件有录屏。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fengyuanchen/viewerjs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月30日(星期天) 下午2:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fengyuanchen/viewerjs] 移动端双击放大后无法移动图片查看 (Issue #527)





 
具体复现步骤3是怎么样的？什么手机？什么浏览器和版本？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

QQ录屏20220130154253.mp4 (1.87M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=2c643264c46dd7ceaf9289481563071e03560754515203524c070451024e010805511f055757561c5951045d0b570d5750545050337b356030a68ea2f251050353540357035200055351014a5e1301315c&t=exs_ftn_download&code=ad2d3c51

**Comment by jeff-wangzhen** [comment]
确定吗。。现在在手机是正常了，不过在电脑上，移动端模式，双击鼠标左键不能放大图片了。。

**Comment by fengyuanchen** [comment]
暂不支持“电脑端浏览器 + 移动端模式”。

**Comment by jeff-wangzhen** [comment]
> 双击暂不支持“电脑端浏览器 + 移动端模式”。

也不是，发现如果一开始先启动移动端模式，再打开网页的话，是正常的效果。如果是先打开网页， 切到移动端不刷新，就不正常。。那行吧，不算啥大问题。
