### ISSUE TITLE
在使用model的时候，我不想全屏显示，只想在一个固定高宽的div里面显示

### ISSUE THREAD

**Issue by guimeisang** [fengyuanchen/viewerjs#53]
但是问题是，里面的图片不会居中显示，这个问题怎么解决？请帮忙~~~

**Comment by infeng** [comment]
viewerjs的父节点css加入transform试试，这样就能固定在model里面显示

**Comment by guimeisang** [comment]
后来我的解决方案就是：在初始化之前将initContainer的源码改了
var viewBox=document.getElementById('viewBox')；
Viewer.prototype.initContainer=function(){
        var _this = this;
        this.containerData = {
             width: viewBox.offsetWidth,
             height: viewBox.offsetHeight
        };
};
