### ISSUE TITLE
viewer的按钮可做优化，我希望加入viewer的开发优化

### ISSUE THREAD

**Issue by chen-ccy** [fengyuanchen/viewerjs#532]
**viewer的作者您好，viewer是个不错的框架，但我觉得有些部分可以稍加优化**
**1.切换图片的按钮在下边，而且比较小点起来很麻烦，能否出个简单模式，按钮在图片的左右俩边**
**2.关闭viewer的按钮在右上角，有些手机是显示不出来的**
**viewer是个不错的框架，我愿意为它贡献自己的一份力，不知道您是否允许我加入开发**

**Comment by fengyuanchen** [comment]
多谢你的好意。如有兴趣，可以提交 PR。如果功能设计合理，代码质量合格，我们会考虑合并进来的。可以先阅读一下我们的[贡献指南](https://github.com/fengyuanchen/viewerjs/blob/main/.github/CONTRIBUTING.md)。

- 功能1：之前有人提过，我好像提供了自定义左右按钮的方案。
- 功能2：如果更好方案，欢迎提交 PR。注意各种边界情况的兼容性。

**Comment by chen-ccy** [comment]
收到，感谢您的回复。
目前我还有一个疑问：
图片在预览时，会出现的默认的加载，呈现不完成的图片和loading，而且图片宽度很大。图片加载完成后，loading消失，图片以动画的形式重新展示。
我希望图片在完成加载之后才显示，就是一开始只有loading，加载完成后以再展示图片，我打算自己先优化一下。
以下是示例图片：
[图片未加载完成之前](http://120.24.92.39/image/photo1.png)
[图片加载完成之后](http://120.24.92.39/image/photo2.png)

**Comment by fengyuanchen** [comment]
图片加载时从上到下逐渐显示是为了提升用户体验，避免大图下载长久未给用户视觉反馈。

**Comment by chen-ccy** [comment]
好的，感谢您的回复
