### ISSUE TITLE
Custom html source

### ISSUE THREAD

**Issue by aneesdev** [fengyuanchen/viewerjs#533]
**Is your feature request related to a problem? Please describe.**
Hi @fengyuanchen,

First of all, thank you so much for the great package. Always appreciate the hard work that you have put into it.

is there a way I can give viewerjs any HTML (iframe, div, anything) ? and its add it inside: 

```html
<div class="viewer-canvas" data-viewer-action="hide">
    <!--  my HTML here -->
</div>

```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fengyuanchen** [comment]
Not support that.
