### ISSUE TITLE
After zooming in the picture, after the picture is slid out of the view area, you need to switch to the next picture

### ISSUE THREAD

**Issue by wll8** [fengyuanchen/viewerjs#535]
**Describe the bug**
After zooming in the picture, after the picture is slid out of the view area, you need to switch to the next picture

**To Reproduce**
  Open the official website and click to enlarge the picture. Drag the picture out of the window.
2. See error
  It becomes a blank area, making people think that a malfunction has occurred.
**Expected behavior**
When the image leaves the view area after a certain threshold:
1. When it is allowed to switch to the next sheet, switch directly to the next sheet.
2. If it is not allowed to switch the picture, it is not allowed to drag the picture outside the view area.

**Screenshots**

![image](https://user-images.githubusercontent.com/28223260/156514075-f2d8afda-5a85-41aa-8422-60e2c55e2a7e.png)

![image](https://user-images.githubusercontent.com/28223260/156514097-2eda9d2b-60bf-40c7-bb8b-0927200eab92.png)

**Desktop (please complete the following information):**
 - OS: win10x64
 - Browser: chrome 98.0.4758.102 x64
 - Version: 1.10.4

**Comment by fengyuanchen** [comment]
Just check out this example: https://fengyuanchen.github.io/viewerjs/examples/moving-range-limit.html
