### ISSUE TITLE
照片宽度比高度大时，在笔记本上显示会自动旋转

### ISSUE THREAD

**Issue by haichao0817** [fengyuanchen/viewerjs#537]
**Describe the bug**

一个照片，本身是歪的（拍摄完之后，是横向显示的），这时候放到插件里面，在笔记本上查看是正向显示的，在台式机是横向显示的（原本的样子），这会是什么问题呢。。。

注：这个原图就是歪的，因为用adb导出拍摄命令的时候有bug，导致拍出来的照片就是歪的。

**Comment by fengyuanchen** [comment]
笔记本的浏览器比较先进，会自动修图？

**Comment by fengyuanchen** [comment]
也许可以看看是不是配置了 `image-orientation` 属性：https://developer.mozilla.org/en-US/docs/Web/CSS/image-orientation
