### ISSUE TITLE
增加图片点击事件

### ISSUE THREAD

**Issue by chen-ccy** [fengyuanchen/viewerjs#538]
**增加图片点击事件**
我希望点击大图就关闭Viewer，但似乎没有图片点击事件，不知是否可以添加这个事件

**Comment by fengyuanchen** [comment]
你全局注册一个点击事件不就行了吗？

**Comment by chen-ccy** [comment]
您好，这我确实实现了，不过我觉得这是个不错的功能点，如果您觉得合适就添加

**Comment by fengyuanchen** [comment]
现在自定义事件已经有点多了，暂时不考虑增加了。
