### ISSUE TITLE
使用 container 配置父页面打开后，图片和底部导航位置不对，并且图片没法移动了，点击播放按钮变成显示iframe页面了

### ISSUE THREAD

**Issue by kai800** [fengyuanchen/viewerjs#546]
**Expected behavior**
使用 container 配置父页面打开后，图片和底部导航位置不对，并且图片没法移动了，点击播放按钮变成显示iframe页面了

**Screenshots**
container: $('body', top.window.document)[0]

![image](https://user-images.githubusercontent.com/31036533/167236053-31038031-1a4f-430a-b0c7-968fc3dc9420.png)

**Comment by fengyuanchen** [comment]
不支持在 iframe 中使用。请在顶层窗口初始化 Viewer.js.
