### ISSUE TITLE
iOS 15 zoom bug

### ISSUE THREAD

**Issue by alienwave1** [fengyuanchen/viewerjs#550]
On iOS 15, when zooming in, the image twitches or returns to its original size. What should I do? Video:
https://drive.google.com/file/d/1KL96OEDSIabS3LPFjS5yA5kQWa18AQ37/view?usp=sharing

**Comment by fengyuanchen** [comment]
Can you reproduce it in [the official demo](https://fengyuanchen.github.io/viewerjs/)?

**Comment by alienwave1** [comment]
Interesting, but no. It works fine in the demo

**Comment by alienwave1** [comment]
iOS 15.5. UPD: https://drive.google.com/file/d/1Bld7ksu-61D5TE7Hx4S1evcX_dxwYG36/view?usp=sharing, https://drive.google.com/file/d/1ksleS1uZP5LjuKGOktf8EvVwa4qV24S2/view?usp=sharing

**Comment by fengyuanchen** [comment]
OK. I will close this now.
