### ISSUE TITLE
如何在play时如何获取当前图片的信息

### ISSUE THREAD

**Issue by Phyday** [fengyuanchen/viewerjs#552]
**Is your feature request related to a problem? Please describe.**
我想要在播放的过程中，能够获取到当前播放照片的信息，如detail/index等

**Describe the solution you'd like**

**Describe alternatives you've considered**
试过viewed和play，只会调用一次。

**Additional context**

**Comment by fengyuanchen** [comment]
不支持。可 fork 一份自己改造。
