### ISSUE TITLE
[req] want to large image natural size view and stop page element click event 

### ISSUE THREAD

**Issue by DandyClubs** [fengyuanchen/viewerjs#560]
**Is your feature request related to a problem? Please describe.**
**Q1**
i use thumbs to large image

some large image height is window size over

viewer.js is fit image size for window 

i try zoom and move top

**Q2**
if tag a > img 

a.href has javascript or target blank or onclick
page include img click event zoom event 

how to stop event?

**Describe the solution you'd like**
if image size large
i want image naturalHeight size and show image's top

**Comment by fengyuanchen** [comment]
1. Call `viewer.zoomTo(1)` after ready.
2. Use the `filter` option to exclude images.
