### ISSUE TITLE
iOS 15 zoom bug

### ISSUE THREAD

**Issue by alienwave1** [fengyuanchen/viewerjs#561]
In Safari on iOS 15, where the search bar is located at the bottom, there is a problem that when the image is enlarged, this search bar also interacts

https://drive.google.com/file/d/1ksleS1uZP5LjuKGOktf8EvVwa4qV24S2/view?usp=sharing

**Comment by fengyuanchen** [comment]
You can try to prevent the zoom or wheel event by yourself.

**Comment by alienwave1** [comment]
what do you mean? event.preventDefault() on scroll?

**Comment by fengyuanchen** [comment]
Yes. Just try to fix it by yourself.
