### ISSUE TITLE
ESC button doesn't close the image in inline mode

### ISSUE THREAD

**Issue by alhuber1502** [fengyuanchen/viewerjs#563]
There is no obvious way to close an opened image in inline mode. The
ESC button doesn't close the image in inline mode.

**Comment by fengyuanchen** [comment]
For inline mode, you should destroy the viewer to "close" it.

**Comment by alhuber1502** [comment]
Why is there no close button in the interface (similar to modal mode) so the user can trigger that "destroy"?

**Comment by fengyuanchen** [comment]
Because it is not a dialog...
