### ISSUE TITLE
Method `destroy()` doesn't work propably with div click

### ISSUE THREAD

**Issue by MCErtan** [fengyuanchen/viewerjs#566]
**Describe the bug**
Method `destroy()` doesn't work propably.

**To Reproduce**
1. Create a gallery that opens on clicking the div.
2. Click on the div and viewerJS will open.
3. Use any method to turn it off.
4. Randomly resize window size.
5. Click the div again and use a close method again.
6. Open Inspect > Elements. 
7. At the bottom, you will see that the element created by viewerJS is not deleted.

**Expected behavior**
The element must be deleted even if the window is resized.

**Screenshots**
https://i.imgur.com/we4o3rB.gif
Codepen: https://codepen.io/lastofdead/pen/JjZPRPV

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Chrome
 - Version 106.0.5249.119

HTML
```
<div id="viewImages" class="exampleclass1" onclick="CustomizeViewer(this)">
    <ul class="pictures">
        <li><img data-original="../../users/image1.png" alt="Example Title 1"></li>
        <li><img data-original="../../users/image2.png" alt="Example Title 2"></li>
    </ul>
</div>
<div id="viewImages2" class="exampleclass1" onclick="CustomizeViewer(this)">
    <ul class="pictures">
        <li><img data-original="../../users/image3.png" alt="Example Title 1"></li>
        <li><img data-original="../../users/image4.png" alt="Example Title 2"></li>
    </ul>
</div>
<div id="viewImages3" class="exampleclass1" onclick="CustomizeViewer(this)">
    <ul class="pictures">
        <li><img data-original="../../users/image5.png" alt="Example Title 1"></li>
        <li><img data-original="../../users/image6.png" alt="Example Title 2"></li>
    </ul>
</div>
```

JS
```
function CustomizeViewer (elem) {
    const imageAttr = elem.getAttribute("id");
    const imageList = document.getElementById(imageAttr);

    var viewer = new Viewer(imageList, {
        url: 'data-original',
        button: false,
        loop: false,
        keyboard: false,
        navbar: true,
        rotatable: false,
        toolbar: {
            zoomIn: 4,
            zoomOut: 4,
            oneToOne: false,
            reset: 4,
            prev: true,
            play: false,
            next: true,
            rotateLeft: 4,
            rotateRight: 4,
            flipHorizontal: 4,
            flipVertical: 4,
        },
    });
    viewer.show();

    imageList.addEventListener('hidden', function () {
        viewer.destroy();
    });
}
```

I'm using lastest version of viewerJS.

**Comment by fengyuanchen** [comment]
Can you provide an online demo? For example use codepen.io?

**Comment by MCErtan** [comment]
> Can you provide an online demo? For example use codepen.io?

I added it now. Here is an image from the codepen:
https://i.imgur.com/PyNahNI.png

Codepen: https://codepen.io/lastofdead/pen/JjZPRPV

**Comment by MCErtan** [comment]
The problem is when the 'hidden' EventListener is not cleared and there is more than one hidden Event Listener., I guess. The problem seems to be solved with the code below.

```
var hideViewer = function () {
    imageList.removeEventListener('hidden', hideViewer);
    viewer.destroy();
}
imageList.addEventListener('hidden', hideViewer);
viewer.show();
```

**Comment by fengyuanchen** [comment]
OK, you may also need to destroy the instance with `viewer = null` after calling the `destroy` method.
