### ISSUE TITLE
how can I keep the inline viewer visible when scrolling?

### ISSUE THREAD

**Issue by dodumosu** [fengyuanchen/viewerjs#573]
hello. thanks for the great work @fengyuanchen! i'm using the viewer in inline mode in a page with Bootstrap 4 and split.js, with the page split horizontally, as below:

![WC0o356453](https://user-images.githubusercontent.com/1408662/200592096-4a76ac43-7de9-45e5-9272-882846cb56cf.png)

the issue I'm trying to resolve is that I want to keep the viewer visible while I can scroll the rest of the page. I've tried to add the `sticky-top` class from Bootstrap using the `className` property, but it doesn't seem to work. any ideas on how I could do this?

thanks again.

**Comment by fengyuanchen** [comment]
Split your solution into two steps:

1. Make the image(s) container visible when scrolling.
2. Use Viewer.js on the container.
