### ISSUE TITLE
控制栏的图标图片分辨率过低，建议2x图

### ISSUE THREAD

**Issue by uoau** [fengyuanchen/viewerjs#574]
控制栏的图标
![image](https://user-images.githubusercontent.com/41247996/201280501-927d4cf1-859e-4df0-bce9-f5f729c26f43.png)
目前是1x图，建议使用2x图，不然在高分辨率下有点糊

**Comment by SusieWen777** [comment]
Hello @fengyuanchen , I am a beginner in contributing to open-source projects and am very interested in this issue. I believe I have some ideas on how to approach it. Could I work on it?

**Comment by richex-cn** [comment]
Perhaps using SVG would be better?

**Comment by fengyuanchen** [comment]
Resolve in #637.
