### ISSUE TITLE
multiple images on dynamic viewer mode

### ISSUE THREAD

**Issue by xs275** [fengyuanchen/viewerjs#580]
sorry, i'm poor in english
how can i do dynamic viewer with multiple images?

https://fengyuanchen.github.io/viewerjs/examples/dynamic-viewer.html
like this..

------
$('body').on('click', '.ck-content-view img', function () {
	var image1 = new Image();
	var image2 = new Image();
	var src1 = $(this).attr('src');
        var src2 = $(this).data('src');
	image1.src = src1;
        image2.src = src2;
	var images = [image1, image2];
	var viewer = new Viewer(images, {
		hidden: function () {
			viewer.destroy();
		},
	});
	viewer.show();
})
-----
it does not work

**Comment by fengyuanchen** [comment]
Show a viewer with multiple images dynamically on click a button:

```js
window.addEventListener('DOMContentLoaded', function () {
  document.getElementById('button').addEventListener('click', function () {
    var image = new Image();
    var image2 = new Image();
    var image3 = new Image();

    image.src = '../images/tibet-1.jpg';
    image2.src = '../images/tibet-2.jpg';
    image3.src = '../images/tibet-3.jpg';

    var gallery = document.createElement('div');

    gallery.appendChild(image);
    gallery.appendChild(image2);
    gallery.appendChild(image3);

    var viewer = new Viewer(gallery, {
      hidden: function () {
        viewer.destroy();
      },
    });

    // image.click();
    viewer.show();
  });
});
```

**Comment by xs275** [comment]
> Show a viewer with multiple images dynamically on click a button:
> 
> ```js
> window.addEventListener('DOMContentLoaded', function () {
>   document.getElementById('button').addEventListener('click', function () {
>     var image = new Image();
>     var image2 = new Image();
>     var image3 = new Image();
> 
>     image.src = '../images/tibet-1.jpg';
>     image2.src = '../images/tibet-2.jpg';
>     image3.src = '../images/tibet-3.jpg';
> 
>     var gallery = document.createElement('div');
> 
>     gallery.appendChild(image);
>     gallery.appendChild(image2);
>     gallery.appendChild(image3);
> 
>     var viewer = new Viewer(gallery, {
>       hidden: function () {
>         viewer.destroy();
>       },
>     });
> 
>     // image.click();
>     viewer.show();
>   });
> });
> ```

thank you
