### ISSUE TITLE
移动端 预览图片 关闭功能

### ISSUE THREAD

**Issue by Ricky816845** [fengyuanchen/viewerjs#585]
手机端点击操作基本一定会有move事件,所以很难关得掉
我这边临时处理是记录了pointdown和pointup事件的timestamp作为依据 ,来判断是否为点击.

**Comment by Ricky816845** [comment]
手机是三星S10 Andriod 12
Edge浏览器 应该是最新的，最近才装的
类库也是最新的 不过不是直接使用，
我创建了一个仓储来演示复现情况，（用PC浏览器是没法复现的，不会出现移动）
[https://github.com/Ricky816845/viewerjs-mobile-temp-demo](https://github.com/Ricky816845/viewerjs-mobile-temp-demo)

**Comment by fengyuanchen** [comment]
我用手机上 Chrome 浏览器试了，你的示例是有问题，但是官网示例好像就没问题。

**Comment by fengyuanchen** [comment]
v1.11.3 可能已经修复该问题。
