### ISSUE TITLE
Allow initial image rotation

### ISSUE THREAD

**Issue by M393** [fengyuanchen/viewerjs#586]
**Is your feature request related to a problem? Please describe.**
I need to display images that have separate rotation information, but there doesn't seem to be a way to set a rotation before an image is viewed.
E. g. I have an image that needs to be displayed with a 90° rotation.

**Describe the solution you'd like**
Allow setting the rotation in the `view` handler.

**Describe alternatives you've considered**
Allow configuring  a rotation with the image.

**Comment by fengyuanchen** [comment]
How about this solution?

```js
new Viewer(image, {
  // ...
  viewed: function () {
    this.viewer.rotate(90);
  },
});
```

**Comment by M393** [comment]
Thanks for your time.

Your example will show the image, then rotate it. I'm looking for a solution that will show the image as if it is not rotated.

**Comment by fengyuanchen** [comment]
Maybe it is not supported.
