### ISSUE TITLE
45%屏幕预览展示的图片未居中

### ISSUE THREAD

**Issue by extending** [fengyuanchen/viewerjs#590]
右侧45%屏幕展示的图片未居中展示，margin-left值过大，帮忙确认下是我代码问题还是怎么？
<img width="993" alt="截屏2023-03-07 19 31 02" src="https://user-images.githubusercontent.com/10007289/223410203-d6b19a03-ea34-4a72-bc6c-fd5aeed40089.png">

**Comment by extending** [comment]
需要更改当前预览img的 style margin-left，请问是这样子么？@fengyuanchen

**Comment by fengyuanchen** [comment]
一般都是自动居中的，建议仔细排查一下代码。
