### ISSUE TITLE
用手机微信网页浏览器、windows电脑微信浏览器打开demo首页无法点开大图

### ISSUE THREAD

**Issue by qiangbro** [fengyuanchen/viewerjs#591]
**Describe the bug**
用微信访问https://fengyuanchen.github.io/viewerjs/ 什么都不调，直接点击页面中央的小图，无任何效果，展不开大图

**To Reproduce**
1. 用安卓微信访问https://fengyuanchen.github.io/viewerjs/
2. 点击页面中央的小图
3. 无任何效果，展不开大图

**Expected behavior**
点击小图，展开大图浏览

**Screenshots**
![288124b4dd7b2ac3c7f640fa6e72ee9](https://user-images.githubusercontent.com/4646469/223724620-5561a502-a58f-4b02-b50c-56dd1cdf3c75.jpg)
![3ed9fd9dec0e3d4926d55828bf9d129](https://user-images.githubusercontent.com/4646469/223727813-014889a6-46ca-4aa8-8d53-def36797a2ca.jpg)

win10 微信电脑版3.9.0.28

**Smartphone (please complete the following information):**
 - Device: iqoo neo5
 - OS: 安卓13 
 - Browser 微信安卓版8.0.32
 - Version Viewer.js v1.11.3

**Additional context**
手机浏览器无此问题，仅手机微信、电脑微信有此问题

**Comment by fengyuanchen** [comment]
iOS 版微信、macOS 版微信都没有这个问题。请检查一下是不是部分资源加载失败，或者有没有报错。

**Comment by qiangbro** [comment]
推测不是代码本身的问题，我自己部署了viewerjs的本地demo，微信端打开都正常。
我觉得是因为网络问题导致js或css没有来得及加载完成，
微信网页端没法打开f12看network，也没有任何提示说是否全部js、css已经加载完成或加载失败了，所以用户就没法判断是为什么打不开了
