### ISSUE TITLE
窄屏情况下出现的一种问题，不确定是不是bug.

### ISSUE THREAD

**Issue by AlanYiNew** [fengyuanchen/viewerjs#595]
**Describe the bug**

**To Reproduce**
1. 窄屏情况下，在 view中动态加载图片后调用update导致width变成auto, 缩略图下的li元素就会换行，导致显示不出来
![image](https://user-images.githubusercontent.com/12409161/231109096-67b83d76-db23-4b29-9738-4757c2dfc2a0.png)
![image](https://user-images.githubusercontent.com/12409161/231110417-4b19a146-c760-4294-ab16-9514aa12e10c.png)
![image](https://user-images.githubusercontent.com/12409161/231110416-3ec4f9da-cc83-4af6-b388-86bc26771ae8.png)

2. 是不是可以判断一下没有width的时候才添加width:auto, 问题是在vue3中出现的，找到的原因就是插入图片时发现图片变化了，会去调用update. 请问是不是用法有问题，如果不是，请教一下怎么做才正确。
https://codepen.io/AlanYiNew/pen/qBJdJGq

**Comment by fengyuanchen** [comment]
你是不是问错地方了？你用的 `v-viewer` 不是我提供的。

**Comment by AlanYiNew** [comment]
我知道，但底层好像是viewjs的问题，想问问你这边能不能解决。底层像是viewerjs的问题
