### ISSUE TITLE
debounce move event.preventDefault无效

### ISSUE THREAD

**Issue by Mojie-Wang** [fengyuanchen/viewerjs#598]
[https://github.com/fengyuanchen/viewerjs/pull/429](url)
图片移动到屏幕外优化 move函数加防抖后 limit  event.preventDefault 无效 不加防抖移动端体验较差
Microsoft Edge: 112.0.1722.58
viewerjs: 1.11.3
lodash.js: 4.17.21

demo: https://codepen.io/mojie-wang/pen/gOBgdjR?editors=0010

**Comment by fengyuanchen** [comment]
请再描述清楚一点。

PS: 移动端图片能移动到屏幕外吗？
