### ISSUE TITLE
Pinch zoom not working

### ISSUE THREAD

**Issue by ravitejasbl** [fengyuanchen/viewerjs#60]
In this pinch zoom not working.Is it have?

**Comment by ravitejasbl** [comment]
can any one reply plz

**Comment by ravitejasbl** [comment]
Thanks

**Comment by fengyuanchen** [comment]
More detail?

**Comment by ravitejasbl** [comment]
It is not working fine in mobile, if i zoom using fingers it effects the image and not zooming.

**Comment by fengyuanchen** [comment]
Try the latest version please.

**Comment by ravitejasbl** [comment]
Is it have pinch zooming in mobile?

**Comment by ravitejasbl** [comment]
Yes, it is working
Thanks.
