### ISSUE TITLE
Custom event to show modal

### ISSUE THREAD

**Issue by evan-xy-hu** [fengyuanchen/viewerjs#600]
**Is your feature request related to a problem? Please describe.**
I want to show modal by double clicking the img element.

**Describe the solution you'd like**
A new option to set the custom click event to trigger the modal display.

**Describe alternatives you've considered**
A new option or a small changes to an existing option is also ok.

**Additional context**
When viewjs is set inline:false.

**Comment by fengyuanchen** [comment]
Follow this example: https://fengyuanchen.github.io/viewerjs/examples/dynamic-viewer.html
