### ISSUE TITLE
Backdrop

### ISSUE THREAD

**Issue by es5es5** [fengyuanchen/viewerjs#601]
你好，

感谢你创建这个库。我有一个问题/建议。

backdrop 在iOS上运作良好，但在Android上，即使是微小的移动，图片也会开始移动，查看器也无法正常关闭。

是否有可能修复这个问题？例如，我们是否可以仅在单击图像时使其移动？

期待你的回复。谢谢！

--

Hello,

Thank you for creating this library. I have a question/suggestion.

The backdrop function works well on iOS, but on Android, the image starts moving with even a slight movement and the viewer doesn't close properly.

Is it possible to fix this issue? For example, could we make the image move only when it's clicked?

I would appreciate your response. Thank you!

**Comment by fengyuanchen** [comment]
使用的最新版本（v1.11.3）？

**Comment by es5es5** [comment]
![image](https://github.com/fengyuanchen/viewerjs/assets/24954436/a331bb3b-1242-4fe8-900e-876d01e49972)

当然

**Comment by es5es5** [comment]
检测触摸事件，只有在点击图像时才进行`zoom`操作，
其他情况下作为`backdrop`背景。下面的代码怎么样？

Detect touch events and only `zoom` the image when clicked,
otherwise use it as a `backdrop` as shown in the code below. How does it look?


```typescript
showViewer(url: string) {
  const _this = this
  this.imageElement = new Image()
  this.imageElement.src = url
  this.viewer = new Viewer(this.imageElement, {
    toolbar: {},
    navbar: false,
    title: false,
    backdrop: true,
    viewed(event) {
      nextTick(() => {
        dimElement?.addEventListener('touchstart', (event) => {
          if (!(event.target instanceof HTMLImageElement)) {
            _this.viewer?.hide()
          }
        })
        dimElement?.addEventListener('touchmove', (event) => {
          if (!(event.target instanceof HTMLImageElement)) {
            _this.viewer?.destroy()
          }
        })
        dimElement?.addEventListener('touchend', (event) => {
          if (!(event.target instanceof HTMLImageElement)) {
            _this.viewer?.destroy()
          }
        })
      })
    },
    hidden(event) {
      setTimeout(() => {
        _this.viewer?.destroy()
      }, 100)
    },
    hide(event) {
      _this.imageElement = null
    },
  })
  this.viewer?.show()
  let dimElement = document.getElementsByClassName('viewer-backdrop')[0]
},
hideImageViewer() {
  this.viewer?.hide()
  this.imageElement = null
},
```

**Comment by fengyuanchen** [comment]
每一次 viewed 都要注册 3 个 touch 事件？相互冲突了吧。。
