### ISSUE TITLE
Missing title attribute on img tag

### ISSUE THREAD

**Issue by sklawin** [fengyuanchen/viewerjs#605]
**Describe the bug**
We are currently introducing title attributes for our images. For this we set the Viewer option title to "true"
**To Reproduce**

1.  set title option in any usage to true or go to [Viewer.js Demo](https://fengyuanchen.github.io/viewerjs/examples/custom-title.html )
2. zoom your image
3. inspect the source code
4. img tags have no title attribute

**Expected behavior**
images created by viewer.js have a title attribute, in default mode based on the alt - attribute of the image

**Screenshots**
![image](https://github.com/fengyuanchen/viewerjs/assets/108871544/fe87253f-d112-40ba-8c4e-464f23aa5648)

**Comment by fengyuanchen** [comment]
The "title" option is not suitable for your purpose. Please read the documentation carefully.
