### ISSUE TITLE
关于组件式API用v-viewer 怎么新增个下载或者提交按钮，调用methods的方法失败

### ISSUE THREAD

**Issue by GIS90** [fengyuanchen/viewerjs#607]
请问各位，关于组件式API用v-viewer ，怎么新增个下载按钮，主要实现当前数据的获取，而且用methods的方法，调用失败，说not a function，请大神指点下，HTML代码：
<viewer ref="viewer" :options="viewerOption">
  <img v-for="img in images" :key="img.id" :src="img.url" class="viewer-box-image">
</viewer>

配置：
 // v-viewer options
      viewerOption: {
        inline: false, // 线上模式（区域内展示，非全屏覆盖）
        title: false, // 图片名称
        button: true, // 关闭按钮
        // toolbar: true, // 工具栏
        toolbar: { // 工具栏（boolean | Visibility(0 | 1 | 2 | 3 | 4) | ToolbarButtonSize('small' | 'medium' | 'large') | Function | ToolbarButtonOptions | undefined;）
          zoomIn: 'large', // 缩小
          zoomOut: 'large', // 放大
          oneToOne: 'large', // 100%
          prev: 'large', // 上一个
          play: 'large', // 播放
          next: 'large', // 下一个
          rotateLeft: 'large', // 左旋转
          rotateRight: 'large', // 右旋转
          flipHorizontal: 'large', // 水平翻转
          flipVertical: 'large', // 垂直翻转
          reset: 'large', // 重置
          // 自定义按钮: 下载
          download: {
            click: function(event) {
              console.log(event)
            },
            show: false,
            size: 'large'
          }
        },
        navbar: true, // 缩略图导航栏
        fullscreen: true, // 播放全屏
        loading: true, // 加载
        loop: true, // 循环浏览
        movable: true, // 拖动【toolbar】
        rotatable: true, // 旋转【toolbar】
        scalable: true, // 翻转【toolbar】
        toggleOnDblclick: true, // 双击还原大小
        transition: true, // 动画过渡
        keyboard: true, // 键盘操作
        focus: true, // 导航栏聚焦
        zoomable: true, // 缩放【toolbar】
        zoomOnTouch: true, // 触摸缩放
        zoomOnWheel: true, // 鼠标缩放
        tooltip: true, // 缩放百分比提示
        zoomRatio: 0.1, // 鼠标滚轮缩放比例
        maxZoomRatio: 10, // 鼠标滚轮缩放最大比例
        minZoomRatio: 0.1, // 鼠标滚轮缩放最小比例
        backdrop: true, // 预览modal背景
        interval: 2800 // 播放时间间隔
      },

**Comment by fengyuanchen** [comment]
你问错地方了，请移步：https://github.com/mirari/v-viewer
