### ISSUE TITLE
Blinking title

### ISSUE THREAD

**Issue by Mikilll94** [fengyuanchen/viewerjs#609]
**Describe the bug**
When opening the image the title is blinking

https://github.com/fengyuanchen/viewerjs/assets/17653648/b2f944f7-30ce-4c77-9301-74f2d86d5dc0

**To Reproduce**
1. Go to this page https://fengyuanchen.github.io/viewerjs
2. Click on any image.
3. Observe how the title is blinking.

**Expected behavior**
Title should not blink.

**Desktop**
 - OS: MacOS Ventura 13.3.1
 - Browser: Brave
 - Version 1.56.14 Chromium: 115.0.5790.114 (Official Build)  (x86_64)

**Comment by fengyuanchen** [comment]
It seems work fine on Chrome for MacOS.

**Comment by Mikilll94** [comment]
@fengyuanchen I have figured out that it happens only when you open the image SECOND TIME.

Reproduction:
1. Click the image.
2. Click outside to close it.
3. Click again on the image. You will see the blinking title.

It happens also on Chrome for MacOS. I have checked it.

**Comment by Mikilll94** [comment]
@fengyuanchen 
Thanks. When will you release the version with the fix?

**Comment by fengyuanchen** [comment]
See v1.11.5.

**Comment by fengyuanchen** [comment]
See v1.11.5.
