### ISSUE TITLE
Add `isShown` to TypeScript annotations

### ISSUE THREAD

**Issue by CodeF53** [fengyuanchen/viewerjs#610]
**Is your feature request related to a problem? Please describe.**
I use the `isShown` attribute of my viewer to disable my programs hotkeys while the viewer is open:
```ts
function hotkey(e: KeyboardEvent) {
  // disable hotkeys while viewer is open
  if (viewer.isShown)
    return

  const { key, ctrlKey, shiftKey } = e
  ...
```
But typescript thinks `isShown` isn't a value on viewer, despite it being one. 
```
Property 'isShown' does not exist on type 'Viewer'
```

**Describe the solution you'd like**
When it comes to variables that could be useful to people, like `isShown` add them to TypeScript annotations

**Describe alternatives you've considered**
If you don't want people writing to them, mark them [private](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields) and add getters so we can still use them in a readonly manner (ie: `getIsShown()`)

**Comment by fengyuanchen** [comment]
The `isShown` property of the viewer instance is an internal property, not a public property. If you still want to use it, try `(viewer as any).isShown` please.

**Comment by CodeF53** [comment]
Can you give a good reason for why you can't give us a getter like `getIsShown()`? 

`as any` is severe malpractice.

**Comment by CodeF53** [comment]
> Can you give a good reason for why you can't give us a getter like `getIsShown()`?
> 
> `as any` is severe malpractice.

@fengyuanchen

**Comment by fengyuanchen** [comment]
There are too many internal properties (about 30). I don't think it is a good idea to expose any one of them as they may be changed later.
