### ISSUE TITLE
全屏播放图片时，图片会先铺满屏幕，再变为正常比例

### ISSUE THREAD

**Issue by coJwx** [fengyuanchen/viewerjs#613]
在点击全屏播放图片时，图片会先铺满屏幕，再变为正常比例，我希望的是一个等比例放大的过程（如果无法实现，能否仅去掉这个全屏过程的transition）。

https://github.com/fengyuanchen/viewerjs/assets/74973096/d13baf28-56c3-4b4d-bc7f-9f21c9dbc95a

**Comment by fengyuanchen** [comment]
因为图片需要先下载。下载过程中宽度是100%。下载完成还能计算适配尺寸。目前设计是允许下载过程可见，避免网速过慢时，用户无法收到下载进度及时反馈。

如需变更交互，可以自行重写 `Viewer.prototype.play` 原型方法一下。
