### ISSUE TITLE
Images with `loading="lazy"` attribute break the viewer in Safari

### ISSUE THREAD

**Issue by malinowskip** [fengyuanchen/viewerjs#614]
**Describe the bug**
In Safari, if an image possesses a `loading="lazy"` attribute, then it fails to properly show up in the viewer. The interaction (whatever it is) occurs because the attribute is [inherited from the target image by the image displayed in the viewer](https://github.com/fengyuanchen/viewerjs/blob/cf6fb29a6bef0577cecad18a25770403c89a579d/src/js/methods.js#L245C1-L251C8).

**To Reproduce**
Try clicking on the image using Safari: https://codepen.io/malinowskip/pen/mdavgGP?editors=1010.

The issue seems to be limited to Safari (browser & mobile versions). I have tested it in Safari 17.0.

**Possible solution**
This issue could be resolved by preventing the `loading` attribute from being passed down from the target image to the one displayed in the viewer.

**Comment by malinowskip** [comment]
Just found a solution in another issue: https://github.com/fengyuanchen/viewerjs/issues/403#issuecomment-671005049. Still, it took me some time to figure out that `loading` was causing the problem. Is there a reason why this attribute is inherited?

**Comment by QINDlute** [comment]
omg,you saved my life!
