### ISSUE TITLE
如何监听图片切换事件 next()与 prev()

### ISSUE THREAD

**Issue by AlanCorn** [fengyuanchen/viewerjs#617]
需求是做一个页数显示，就是指示当前显示的是第几张
但移动端的 touchmove 触发（[slideontouch选项](https://github.com/fengyuanchen/viewerjs#slideontouch)）的next()与 prev()无法监听到，有什么方式能解决吗？

**Comment by fengyuanchen** [comment]
重写 `Viewer.prototype.prev/next` 方法？
