### ISSUE TITLE
能否支持 3 / 10， 这样的分页标记，底下的navbar固然好看，但是不够直观当前预览的是多少张图片

### ISSUE THREAD

**Issue by wangh1998** [fengyuanchen/viewerjs#625]
能否支持 3 / 10， 这样的分页标记？底下的navbar固然好看，但是不够直观当前预览的是多少张图片

**Comment by fengyuanchen** [comment]
Follow the [Viewer with custom title](https://fengyuanchen.github.io/viewerjs/examples/custom-title.html) example.
