### ISSUE TITLE
Pinch zoom not working in some phone browsers

### ISSUE THREAD

**Issue by kristianjohansson** [fengyuanchen/viewerjs#63]
When I try to pinch zoom in some phone browsers nothing happens.
Moving the picture is also not working unless you tap the picture multiple times, which causes the picture to move just a little.

I've tested this in both my own project and in your demo page: https://fengyuanchen.github.io/viewerjs.
It seems to be working fine if I use the Chrome browser on my phone.

Tested operating systems: Android 6.0.1(Samsung s7) and  iOS 8.3(iPhone 6)
Tested browsers: Internet, version 4.0.20 and Safari

**Comment by uggrock** [comment]
I can confirm this with Android 6 on Samsung s7.

**Comment by fengyuanchen** [comment]
It is the problem of the default `dragstart` event behaviour.

**Comment by kristianjohansson** [comment]
Still not able to pinch zoom or move the images in the new version (6.0.1).
Tried on both phones and tablets.

**Comment by uggrock** [comment]
Same for me

**Comment by kristianjohansson** [comment]
I debugged your script to see if I could find the problem.
It seems like it is some bug with TouchEvents.

When I changed this line:
`  if (e.changedTouches) {
      each(e.changedTouches, function (touch) {
        extend(pointers[touch.identifier], getPointer(touch), true);
      });
    }`

to this: 
`if (e.changedTouches) {
      each(e.changedTouches, function (touch) {
        extend(pointers[touch.identifier], getPointer(touch, true), true);
      });
    }`
it started working for both pinch zoom and moving the images.

**Comment by fengyuanchen** [comment]
@kristianjohansson Thanks you very much. You just found the core mistake:
`getPointer(touch), true)` is wrong, it must be `getPointer(touch, true))`

**Comment by uggrock** [comment]
Now it works, thank you!
