### ISSUE TITLE
父级组件频繁在 display:none 和 display:block 之间切换，viewer.js 无法获取父级宽度

### ISSUE THREAD

**Issue by zpl11** [fengyuanchen/viewerjs#631]
获取父级宽度的方法仅在 init() 中加载一次
// build asynchronously to keep `this.viewer` is accessible in `ready` event handler.
          timeout = setTimeout(() => {
            this.delaying = false;
            this.build();
          }, 0);
造成当 viewer 嵌套在 dialog 中的时候，在 dialog 关闭的情况下最大化页面，会触发 viewer.js 的  initViewer: function initViewer() 方法，导致  
viewerData = {
          width: Math.max(parent.offsetWidth, options.minWidth),
          height: Math.max(parent.offsetHeight, options.minHeight)
        }; 
这个方法中 parent.offsetWidth  = 0 所以只能使用  DEFAULTS 这里默认的宽度和高度。
还需要在自己的代码中手动的触发一次 resize 方法才能得到 dialog 弹出之后正常的宽和高

**Comment by fengyuanchen** [comment]
在对话框中使用 Viewer.js 可参考这个示例（打开页面后右键查看源码）：https://fengyuanchen.github.io/viewerjs/examples/viewer-in-modal.html
