### ISSUE TITLE
api方式 本地可以，线上不行引入方式报错， import { api as viewerApi } from "v-viewer"

### ISSUE THREAD

**Issue by gaun168753** [fengyuanchen/viewerjs#634]
Named export 'api' not found. The requested module 'v-viewer' is a CommonJS module, which may not support all module.exports as named exports. CommonJS modules can always be imported via the default export, for example using: import pkg from 'v-viewer'; const { api } = pkg;。 import { api as viewerApi } from "v-viewer" 本地使用可以的，线上

**Comment by gaun168753** [comment]
使用： const showImagesInViewer = (url: string)=> {
    viewerApi({
      options: {
        movable: false,
        title: false,
        fullscreen: false,
        toolbar: false,
        zoomable: false,
        navbar: false,
        transition: false,
      },
      images: [url]
    })
}

**Comment by gaun168753** [comment]
急 急 急

**Comment by fengyuanchen** [comment]
你说的 `v-viewer` 和我这的 `viewerjs` 是同一个项目吗？
