### ISSUE TITLE
initViewer初始方法 看图页面 页面 parent 元素偶尔会拿不到 抛异常

### ISSUE THREAD

**Issue by YouthguyZ** [fengyuanchen/viewerjs#636]
**Describe the bug**
initViewer初始方法 看图页面 页面 parent 元素偶尔会拿不到 抛异常 

**To Reproduce**
点击数据选中弹出视图框 页面没有其他操作 偶会突然 initViewer 方法里 parent 元素访问报错

**Expected behavior**
正常获取视图parent 元素

**Screenshots**
![微信图片_20240827150138](https://github.com/user-attachments/assets/1eda3509-e456-48a8-b501-8467ebaa1fe7)
![Snipaste_2024-08-27_15-14-53](https://github.com/user-attachments/assets/1ea082ad-917e-4afe-b567-57281ea26d3f)

代码错误定位是这段

**Desktop (please complete the following information):**
 - Browser [ chrome ]
 - Version [ 103.0.5060.134 ]

**Additional context**

**Comment by fengyuanchen** [comment]
parent 为空，说明父级元素已经被删掉了，viewer 不在 DOM 中了，属于使用问题。自己排查一下。
