### ISSUE TITLE
toolbar icons

### ISSUE THREAD

**Issue by Some14u** [fengyuanchen/viewerjs#637]
I have made a better quality toolbar icons (svg).

You're welcome to use them. These icons are 200bytes lighter and much more crisp than your embedded ones:)
![toolbar_icons](https://github.com/user-attachments/assets/d896027d-2b7e-41c1-bbec-5117621ab646)

**Comment by Some14u** [comment]
let me know if you add them, i will remove an override in my projects.

**Comment by Some14u** [comment]
also, please, add an option to scale up the interface (or toolbars).

**Comment by fengyuanchen** [comment]
Well done. Thanks for your icons.
