### ISSUE TITLE
支持隐藏蒙层

### ISSUE THREAD

**Issue by guoyuexu** [fengyuanchen/viewerjs#638]
能否支持 隐藏蒙层 的配置呢？项目中现在使用css样式强制覆盖，能实现蒙层消失了，但无法操作原蒙层下的输入框（即输入框不能获得焦点），查看源码猜测是enforceFocus方法导致的。

**Comment by fengyuanchen** [comment]
奇怪的需求，不支持。

**Comment by Mcc420** [comment]
I dont have enough information to understand this. Please help me
understand thank you
