### ISSUE TITLE
Feature request: opening a web page when you click on an image

### ISSUE THREAD

**Issue by Nasdaq7** [fengyuanchen/viewerjs#64]
Hi,

At the moment you have a little magnifying glass with a + sign. If you click it, you are shown a larger version of the thumbnail image. Is it possible that you can open a specific web page if you click on the larger image again?

So lets say you have thumbnail 1. You open thumbnail 1 and view the larger image. If you click on the larger image, can you open a specific website - say http://www.myexamplewebsite1.com/page70.html?

and for:
image 2 - http://www.examplewebsite2.com/page33.html
image 3: - http://www.examplewebsite3.com/page553.html
image 4: - http://www.examplewebsite3.com/page1.html

So is it possible to add the feature where you can open a unique website when you click on every image?

Real life example:

you have a thumbnail, it shows you an image, but you want to learn more about the website that showed you the large image - so by clicking on the enlarged image in the gallery, you are taken to the website.

Is that possible with coding? 

Thanx

**Comment by fengyuanchen** [comment]
You can just customize it in your own code. The Viewer.js will not support this. Sorry.
