### ISSUE TITLE
如果旋转圈数超过360°，那么点击重置时会转很多圈才会回到原始位置

### ISSUE THREAD

**Issue by undefined303** [fengyuanchen/viewerjs#641]
### Viewer version

1.11.7

### Link to minimal reproduction

https://fengyuanchen.github.io/viewerjs/

### Steps to reproduce

点击顺/逆时针旋转多次，超过360°后再点击还原，还原时会转很多圈

### What is expected?

还原时的旋转在一圈内

### What is actually happening?

转了很多圈

**Comment by fengyuanchen** [comment]
如果不需要过渡动画效果，可以将 `transition` 选项设置为 `false`.
