### ISSUE TITLE
How to save the image to the local

### ISSUE THREAD

**Issue by caishengmao** [fengyuanchen/viewerjs#65]
How to save the image to the local？

**Comment by fengyuanchen** [comment]
Click the right button of the mouse, and then choose the download button?

**Comment by gaona0704** [comment]
Can we add a download button to save the image to the local?

**Comment by fengyuanchen** [comment]
You can implement it with [HTMLAnchorElement](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a)'s `download` attribute, but only works for [same-origin URLs](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy).

**Comment by jaychapani** [comment]
Can we download the rotated images ?

**Comment by fengyuanchen** [comment]
@jaychapani Not support that~

**Comment by jaychapani** [comment]
Any plans to support that in near future?

**Comment by fengyuanchen** [comment]
@jaychapani Checkout [this example](https://github.com/fengyuanchen/viewerjs/blob/master/examples/custom-toolbar.html) which has a custom download button.

**Comment by CircleOnCircles** [comment]
try <https://fengyuanchen.github.io/cropperjs/>

**Comment by fengyuanchen** [comment]
A custom download button is provided in the toolbar of this online demo: https://fengyuanchen.github.io/viewerjs/examples/custom-toolbar.html
