### ISSUE TITLE
Problem with paddingRight..

### ISSUE THREAD

**Issue by manikshakya** [fengyuanchen/viewerjs#66]
Before opening an issue:

- [Search for duplicate or closed issues](https://github.com/fengyuanchen/viewerjs/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- Read the [contributing guidelines](https://github.com/fengyuanchen/viewerjs/blob/master/CONTRIBUTING.md)

When asking general "how to" questions:

- Please do not open an issue here
- Instead, ask for help on [StackOverflow](http://stackoverflow.com/)

When reporting a bug, include:

- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
- Reduced test cases and potential fixes using [JS Bin](https://jsbin.com), [JSFiddle](https://jsfiddle.net/) or [CodePen](https://codepen.io/)

When suggesting a feature, include:

- As much detail as possible for what we should add and why it's important to Viewer.js
- Relevant links to prior art, screenshots, or live demos whenever possible

**Comment by manikshakya** [comment]
the image is being viewed properly but the viewer is not in the proper position. its width is more than the body and padding-right is 102px; i tried to change the padding with the following code.
`$('.viewer-open').css({
	'paddingRight': '0px'
});`

The padding is solved but the problem is that it is loading padding-right: 102px first, then the padding is changed to 0px. My jquery code is running after 102px padding.


Is there a solution to this? Would be a great help.

Thanks

**Comment by fengyuanchen** [comment]
You might have to fix it by yourself.

**Comment by manikshakya** [comment]
Okay.. thanks.
