### ISSUE TITLE
ipad issue

### ISSUE THREAD

**Issue by b2bstudio** [fengyuanchen/viewerjs#69]
Hi there, I have an issue with the light-box not appearing in the center of the iPad when its in portrait mode, any ideas why this is happening, its fine in landscape mode? I tried overriding with css bellow and it has no effect.

/* Portrait */
@media only screen  and (min-device-width: 768px)  and (max-device-width: 1024px)  and (orientation: portrait)  and (-webkit-min-device-pixel-ratio: 1) {
.docs-galley, .docs-galley2 {
	float: left;
	margin: 0 auto;
	width: 100%;
}
.viewer-canvas > img {
    height: auto !important;
    margin: 15px auto !important;
	margin-top: 200px !important;
    max-width: 90% !important;
    width: 90% !important;
}
}

**Comment by fengyuanchen** [comment]
Upgrade to the latest version and try again.
