### ISSUE TITLE
关闭会卡死如果我在退出动画完成之前点击背景

### ISSUE THREAD

**Issue by KevinPan** [fengyuanchen/viewerjs#70]
通过按ESC退出，或者点击右上角的关闭按钮，当前显示的图片会有一个缩小变无的过程，如果在这个过程中，我点击页面任何位置，图片会正常消失，但图片消失后，背景和其他的东西都没有消失

**Comment by fengyuanchen** [comment]
什么浏览器？什么版本？

**Comment by KevinPan** [comment]
试了一下最新的chrome和IE都有这个情况

**Comment by fengyuanchen** [comment]
无法复现：https://fengyuanchen.github.io/viewerjs/

**Comment by mirari** [comment]
使用过程中遇到了类似情况，按下ESC后快速在图片缩小过程中点击图片，很容易复现。此时图片以外的组件均没有消失，而且点击右上角的关闭也无效。但是可以滚动鼠标滚轮，会发现图片先被放大到1%然后整个组件都被关闭。
