### ISSUE TITLE
navbar list may have more than one active elements

### ISSUE THREAD

**Issue by gdh1995** [fengyuanchen/viewerjs#75]
I find a bug: `.viewer-list`  may have more than one `.viewer-active` elements.

The bug is caused by https://github.com/fengyuanchen/viewerjs/blob/master/src/js/methods.js#L121 :
> ``` javascript
> if (self.viewed) {
>   $.removeClass(self.items[self.index], 'viewer-active');
> }
> ```

Here, `self.viewed` is not a reliable variable to detect if there's an element matching `.viewer-active`, because:
* it is set `false` at once whenever an nav-image is clicked
* it becomes `true` only if `image.onload ->proxy: load -> initImage -> renderImage` successes (at https://github.com/fengyuanchen/viewerjs/blob/master/src/js/handlers.js#L121)

Considering that an image might need too many seconds to load  if an image is too large or the network situation is bad, a user will be impatient and click another nav-image before the current one gets loaded. And then this bug will occur.

I have no idea safe enough to fix it, maybe `if (self.index !== index)` is better.

**Comment by meteoric199** [comment]
对，我也遇到过这个问题。
