### ISSUE TITLE
how to use viewerjs in anuglarjs?

### ISSUE THREAD

**Issue by zhujinhu21** [fengyuanchen/viewerjs#81]
my controller
function weixinConsultCtrl($rootScope, $scope, $state, $filter, $uibModal, $stateParams, SweetAlert, recordService) {
 setTimeout(function () {
            var Viewer = window.Viewer;
            Viewer.noConflict();

            var pictures = document.getElementById('#pictures')

            var options = {
                url: 'data-original',
                navbar: true
            };
            var viewer = new Viewer(pictures, options);
        }, 300);
}
TypeError: element is null
viewer.js (第 446 行，第 1 列)

**Comment by WangHao1221** [comment]
@ zhujinhu21我在angularJS中集成了，但是少一点缺陷，就是没有上一张下一张，还没配置出来
