### ISSUE TITLE
Really slow down with 50 images

### ISSUE THREAD

**Issue by elysiopires** [fengyuanchen/viewerjs#84]
Hello Everyone,

I'm experiencing a really slow down with 50 images resolution(1190x1586). Is there any approach that helps the viewer work better?

Thx,
Elysio

**Comment by fengyuanchen** [comment]
Show the thumbnails first and download the full image only when view it in the viewer window, check out the [demo](https://fengyuanchen.github.io/viewerjs) for detail.
