### ISSUE TITLE
使用vue更新了<ul>里面的图片list，但是show的时候内容还是更新之前的内容

### ISSUE THREAD

**Issue by mawenge** [fengyuanchen/viewerjs#85]
`<div style="display: none">
        <ul id="images">
            <li><img src="/new2/image/part4.png"></li>
            <li v-for="item in photoList" ><img v-bind:src="item.path|filterPath"></li>
        </ul>
    </div>`
这样子更新之后里面的内容之后，调用show方法，内容没有更新

**Comment by xuqihua** [comment]
hohoho  不知道怎么用在vue里面，这个还是jquery时代的，API里应该提供set图片列表的功能

**Comment by fengyuanchen** [comment]
Try the `update` method:

```js
// change the list
this.$nextTick().then(() => {
  viewer.update()
})
```

**Comment by mawenge** [comment]
@fengyuanchen 这个是什么原理啊，$nextTick().then调用需要引入新的js插件吗？

**Comment by fengyuanchen** [comment]
@mawenge https://github.com/vuejs/vue/pull/3967

**Comment by mirari** [comment]
vue组件在挂载和卸载时DOM元素可能会被重建，直接执行update方法有可能会报找不到el.viewer对象的错误，为了稳妥起见，不如选择destroy和重新初始化
