### ISSUE TITLE
请问有计划做图片lazyLoad吗

### ISSUE THREAD

**Issue by meteoric199** [fengyuanchen/viewerjs#89]
我们公司的项目，普遍都有几百张图片。图片加载速度很慢。我使用了lazyLoad加载图片。

Modal Mode 使用 lazyLoad的库https://github.com/verlok/lazyload
Inline Modei 先根据nav bar 宽度和图片宽度计算当前能显示多少图片。然后当监听到view事件时，加载这些图片。

假如您有计划做的话，我可以使用这种方式提交pull request吗？
或者其他更好的方法。

**Comment by fengyuanchen** [comment]
暂时没有考虑做。不过你可以把你们公司的实现的PR上来给需要的人做参考。

**Comment by meteoric199** [comment]
嗯

**Comment by undefinedESC** [comment]
@meteor199 能分享一下你的方法吗？

**Comment by undefinedESC** [comment]
> 我们公司的项目，普遍都有几百张图片。图片加载速度很慢。我使用了lazyLoad加载图片。
> 
> Modal Mode 使用 lazyLoad的库https://github.com/verlok/lazyload
> Inline Modei 先根据nav bar 宽度和图片宽度计算当前能显示多少图片。然后当监听到view事件时，加载这些图片。
> 
> 假如您有计划做的话，我可以使用这种方式提交pull request吗？
> 或者其他更好的方法。

@meteor199 按照你的方法可以减少内存消耗，thanks

@fengyuanchen 建议提供lazyload。
