### ISSUE TITLE
when play the image gallary, if could change the showed image through the keyboard pre/next

### ISSUE THREAD

**Issue by ismallboy** [fengyuanchen/viewerjs#90]
when play the image gallary, if could change the image showed curent, through the keyboard pre/next.because i need the img show full screen.

**Comment by fengyuanchen** [comment]
What are you mean?

**Comment by eliblanco87** [comment]
Probably means that in Play mode, pressing arrow-left or arrow-right doesn't change the current image

**Comment by fengyuanchen** [comment]
@eliblanco87 I see, thanks.
