### ISSUE TITLE
Add Close icon/button to navigation bar

### ISSUE THREAD

**Issue by Kabronzky** [fengyuanchen/viewerjs#91]
I am using the plugin for a mobile app and showing the viewer on an iframe, causes the close button (top right) to overlap the  scroll bar. This may be a very specific scenario, but do you think it would be useful to add a close button to the navigation bar?

Also disable the play button from the bar. I am using your viewer to display document pages  as images.

This is so far the most useful plugin I found. 

![issue](https://user-images.githubusercontent.com/30536905/28735556-5d3dead6-73ab-11e7-98df-72fa494b3e29.PNG)

**Comment by fengyuanchen** [comment]
Hide the built-in close button and create a custom button by yourself.
